### ISSUE TITLE
Updating donation builder copy

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1030]
**User Story:**
As a donor
I want to know that the amount I'm donating will be matched
So that my donations will be matched

**Acceptance Criteria**
- Adding 1 line of copy under the "Submit your donation" button

**Product & Design Links:**
- [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=3180%3A85249&t=GbhISJ168BQoz6ps-4)

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by gravityblast** [comment]
@melissa-neira I'm closing this one, or is it something we still need?

**Comment by michellema1208** [comment]
@gravityblast - this is an outdated ticket, let's keep it closed, thank you!
