### ISSUE TITLE
home in Amplify your donation links to undefined (404)

### ISSUE THREAD

**Issue by ligi** [gitcoinco/grants-stack#1034]
this link:

![image](https://user-images.githubusercontent.com/111600/213960242-9d43654b-ba3c-4798-8ef7-ac5301cb7c6b.png)

ends up in a 404

**Comment by gravityblast** [comment]
@michellema1208 is this stil something to fix?

**Comment by michellema1208** [comment]
@gravityblast - I'm not able to replicate this issue, let's close this out for now!
