### ISSUE TITLE
Manager: add ability to preview Additional Questions

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1120]
### Background 
**Problem:** We received feedback from round operators that they wanted to have the ability to add custom questions on their round applications . Currently, all questions/answers on a  are by default text fields

**Solution:** We are giving round operators additional customizability on a round application by: 
-  enabling different question types (i.e. short/long answer, dropdown, checkboxes, etc.)
- determine if a question is required / optional 
- determine if a question is encrypted / not encrypted
- determine if the answer to a question will be visible on a project's Grant Explorer page 

**Goal:** Give round operators customization and control over their grant round applications. 

--------------
### User Story & Acceptance Criteria 

**User Story**
As a round operator, 
I want to be able to preview my Additional Questions 
so I can how my questions look on the grant round application from a project owner POV 

**Acceptance Criteria**
GIVEN that I am a **_round operator_** 
WHEN I look at the Additional Questions section 
THEN I see a CTA to "Preview" 

GIVEN that I click on "Preview" 
WHEN I look at the page
THEN I see a modal showing me what my additional questions look like on the round application 

GIVEN that I select "Close Preview" 
WHEN I look at the page 
THEN I am back on the Additional Questions section 

**UI Checklist**
Please see Figma for details. 

--------------
### Product, Design, & Engineering Notes 

**Product**
* This can be scoped out if needed - others in this milestone should be prioritized first 

**Design**
* Loom: https://www.loom.com/share/fcbd167f80664375ba78901c18032975
* Figma: https://www.figma.com/file/U4uRlyJJn92QiNUuyRxSvX/%5BWIP%5D-Grants-Application-%2F-Edit-Flow?node-id=65%3A2108&t=VrorsgN0AdIRBv3Y-0

**Engineering**
*

**Comment by gravityblast** [comment]
@michellema1208 is this still relevant?

**Comment by michellema1208** [comment]
@gravityblast we can close it for now!
