### ISSUE TITLE
Add fund contract functionality

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1147]
**User Story:**
As a program manager
I want to put my funding pool in the round contract
So that I can pay out my grantees

**Acceptance Criteria**
GIVEN that I am on the Fund Contract tab
WHEN I click into the "Amount to Fund" box
THEN I am able to enter a number of the pool tokens to add to the contract

GIVEN that I am on the Fund Contract tab
WHEN I enter a number of pool tokens in the "Amount to Fund" box
THEN I see those tokens' value in USD next to the amount

GIVEN that I have entered an amount in the Amount to Fund box
WHEN I click the "Fund the Contract" button
THEN I see the Confirmation State modal 
WITH the details of my intended transaction

GIVEN that I am looking at the Confirmation State modal
WHEN I click cancel
THEN the modal closes
AND I still see the amount I entered in the "Amount to Fund" box

GIVEN that I am looking at the Confirmation State modal
WHEN I click Confirm
THEN I see the Heads Up modal

GIVEN that I am looking at the Heads Up modal
WHEN I click continue
THEN I am prompted to sign the transaction in my wallet

GIVEN that I have signed the transaction to fund the contract in my wallet
WHEN the transaction is in progress
THEN I see the transaction in progress view of the page

GIVEN that I have signed the transaction to fund the contract in my wallet
WHEN the transaction completes
THEN the Amount in Contract and Amount left to fund rows update with the new amounts

**Product & Design Links:**
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=208%3A16807&t=flkAYfWJH8i2T4Ua-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
@bhargavaparoksham this is still in progress, there's progress in the branch and the draft PR, not sure what the agreement is here - if there's wip branch and draft PR, do we keep in progress or todo?

**Comment by vacekj** [comment]
Got it, thanks for clearing that up 🤝
