### ISSUE TITLE
PLACEHOLDER: Add Round Status Indicators

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1150]
**User Story:**
As a program manager
I want to know what stage my round is in 
So that I know what I need to be done

**Acceptance Criteria**
GIVEN that I am on a round dashboard
WHEN I look at the top of the dashboard
THEN I see the appropriate round status indicators

**Product & Design Links:**
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=105%3A13156&t=XaW223fxpkYxwR5k-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
@nfrgosselin is this still a relevant/open ticket? re: "placeholder" 

and was this a P0 or P1 for the fund + payout flow milestone?
