### ISSUE TITLE
round manager & grants hub: add website question type and validation on application form

### ISSUE THREAD

**Issue by KurtMerbeth** [gitcoinco/grants-stack#1163]
Users should not be able to make obviously false statements in forms. Therefore input validation of email, URLs and addresses should be implemented.

Update on 2/23: I've scoped down this request to be specific to website - we were able to add email and wallet address validation as part of existing changes.

**Comment by michellema1208** [comment]
@KurtMerbeth are we currently adding a "website" question type?

**Comment by codenamejason** [comment]
Still need to add verification
