### ISSUE TITLE
Pay unpaid grantees (contract interaction)

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1193]
**User Story:**
As a program manager
I want to know who I have left to pay
So that I can manage my to-do list

**Acceptance Criteria**
GIVEN that I have Unpaid Grantees selected
WHEN I click Pay Out Funds
THEN I see the Confirmation State modal

GIVEN that I am looking at the Confirmation State modal
WHEN I click confirm
THEN I am prompted to sign a transaction

GIVEN that I have signed a transaction to pay out grantees
WHEN that transaction is in progress
THEN I see the transaction processing state

GIVEN that I have signed a transaction to pay out grantees
WHEN that transaction completes
THEN I return to the page

**Product & Design Links:**
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=208%3A17502&t=iww3YC9UOXq8yF2Q-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
there is a util function in round.ts on 1194-populate-unpaid-grantees-table which has the util isReadyForPayout function available
