### ISSUE TITLE
spike: researching how to update subgraph schema to support new/multiple applications 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1226]
**User Story:**
As an engineer
I want to update the graph schema and redeploy
So that we can update our project/application edit flow and re-application flow

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
[Redeployment Link](https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/#redeploying-a-subgraph)
- When making changes to your subgraph definition, for example, to fix a problem in the entity mappings, we  would just redeploy to deploy the updated version.
- Any update of a subgraph requires that Graph Node reindexes your entire subgraph, again starting with the genesis block.

It looks like there should not be an issue updating the schema or entity mappings and just redeploying.

Next Steps: 
- Decide how to update contracts - application status on-chain 
- Update subgraph to new schema

**Comment by nfrgosselin** [comment]
Completed
