### ISSUE TITLE
Error running Grants Explorer locally

### ISSUE THREAD

**Issue by ricksentnt** [gitcoinco/grants-stack#1230]
**Overview**
So when we try to run it on local host we facing this error and when we try to launch the staging site it's also showing the same error. The first screenshot image is from local host, and the second screenshot image is from the staging site.

**Steps To Reproduce**
1. After we run the PNPM install on monorepo
2. Run the pnpm re-start
3. It showing the error on console log 
 

**Observed  behavior**
Uncaught Error: `useClient` must be used within `WagmiConfig`.

**Expected behavior**
We expect to see the gitcoin grants run on the screen, so we can start to develop the grants collection features.

**Screenshots**
Localhost
![image4](https://user-images.githubusercontent.com/72134152/225072128-7f7165f7-2c8c-4bf0-8439-436156601e27.png)
Staging site
![image3](https://user-images.githubusercontent.com/72134152/225071966-9ca0cdfd-30ed-4d9e-b213-9a3a6f4d9f34.png)

**Additional context**
We trying to develop the grants collection features, so we need to deploy and run it locally first

**Comment by vacekj** [comment]
Couldn't replicate using latest main, please reopen if this still occurs.
