### ISSUE TITLE
Builder: add WYSIWIG editor for rich text

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1232]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gravityblast** [comment]
@michellema1208 we already have markdown enabled, we need to explicitly tell users about it

**Comment by michellema1208** [comment]
@gravityblast agreed, let's keep this open -- I have it tagged under a "Product Backlog" milestone
