### ISSUE TITLE
All: add support to verify GitHub username ownership without GitHub organization

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1246]
**User Story:**
As a project owner 
I want to be able to verify my Github username ownership solely 
So that I can have a verified Github credential even if I am not part of an organization 

**Acceptance Criteria**

_All_
GIVEN that I have successfully verified only my Github username 
WHEN I look at a page with my verification badge* 
THEN I see the verified badge next to my Github username 

GIVEN that I have successfully verified both my Github username and organization
WHEN I look at a page with my verification badge* 
THEN I see a verified badge next to both my Github username and organization 

*Pages with verification badge: 
- Builder: Project Details, Application Preview page 
- Manager: Project Application page (when approving/rejecting) 
- Explorer: Project page

_Builder_
GIVEN that I am on Create Project > Project Socials page 
WHEN I look at the page 
THEN I see a field to enter Github username 
AND have the ability to verify just ownership of my Github username 
and a checkbox to indicate that my project is part of a Github organization

GIVEN that my project is part of a Github organization
WHEN I check the box 
THEN I see an additional field for Github organization 
AND have the ability to verify ownership of my Github username and membership to my Github organization 

GIVEN that I enter my Github organization without Github username 
WHEN I I click Verify 
THEN I see an error requiring me to add Github username (this should already exist in the app) 

GIVEN that I no longer want to add my Github organization
WHEN I uncheck the box 
THEN the Github organization field disappears 
AND the verify button is back next to Github username field 

GIVEN that I am on Edit Project > Project Socials page 
WHEN I look at the page
THEN I see the same options to verify just my Github username and/or Github username and organization 

GIVEN that I don't have any Github verifications 
WHEN I look at the application page for a round that requires either/or verification of Github username and organization
THEN I see what verifications I am missing 

_Manager_
GIVEN that I am creating a round 
WHEN I am configuring social verifications
THEN I see an option to require Github username and/or Github organization 

GIVEN that I want to require verified Github organization 
WHEN I toggle on/off Github organization
THEN it also toggles on/off Github username (since you need Github username to be able to verify membership to a Github organization)

**Product & Design Links:**
* Figma: https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=4936-40277&t=8LI5GJY4oBsWx0Ad-4 

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by gravityblast** [comment]
@michellema1208 do we still need it?
