### ISSUE TITLE
Wireframes for Linear QF v2 - post round

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1255]
**Context**
[Outcome Brief](https://www.notion.so/gitcoin/Linear-QF-Flow-v2-ae8793b2a9c34153863b36e574a017f1)

**Acceptance Criteria**
- Wireframes for post-round flows

**Comment by melissa-neira** [comment]
(wip) wireframes live [here](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=709-31644)
