### ISSUE TITLE
Update Builder stats to work with indexer

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1259]
**Overview**
Now that the indexer is up and running we need the project stats in Builder to pull from that service instead of the subgraph. 

**Details**
Say more

**Comment by hmrtn** [comment]
Ready to go once https://github.com/gitcoinco/allo-indexer-client/pull/6 is merged

**Comment by gravityblast** [comment]
@hmrtn we can already use the data in `/data/1/rounds/0xD95A1969c41112cEE9A2c931E849bCef36a16F4C/projects.json` fetched with `client.getRoundApplications` without fetching all the votes

**Comment by michellema1208** [comment]
@gravityblast is this already completed?
