### ISSUE TITLE
Update Explorer card design

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1279]
**User Story:**
As a donor
I want to see a cart-style button on a project's Explorer card
So that I have a better understanding of how to interact with the cards

**Acceptance Criteria**
GIVEN that I am on the All Projects page of an Explorer
WHEN I look at a project's card
THEN I see the updated Card layout
AND I see the new cart button

GIVEN that I am on the All Projects page of an Explorer
WHEN I click on the cart button
THEN the project is added to my cart
AND the cart button changes to the checkmark icon

GIVEN that I am on the All Projects page of an Explorer and have a project in my cart
WHEN I click on the checkmark icon
THEN the project is removed from my cart
AND the checkmark button turns back to the cart icon

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-4439&t=javk4LDbEb4uXiO3-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This doesn't include adding the header icon interactions for the cart
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Fixed by https://github.com/gitcoinco/grants-stack/pull/1325
