### ISSUE TITLE
Update Project Details cart button

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1280]
**User Story:**
As a donor
I want to know how to add a project to my cart
So that I can proceed with my donations

**Acceptance Criteria**
GIVEN that I am on a project's detail page and **it is not** in my cart
WHEN I click the Add to Cart button
THEN the project is added to my cart
AND the button changes to the "Added to Cart" state

GIVEN that I am on project's detail page and **it is** in my cart
WHEN I click the Added to Cart button
THEN the project is removed from my cart
AND the button changes to the "add to cart" state

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-6422&t=javk4LDbEb4uXiO3-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
fixed via https://github.com/gitcoinco/grants-stack/pull/1325
