### ISSUE TITLE
Change cart icon header interactions

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1281]
**User Story:**
As a donor
I want to be able to easily check my cart
So that I know what I have added to my list

**Acceptance Criteria**
GIVEN that I am on a round's Explorer
WHEN I don't have projects in my cart
THEN I see the empty cart icon in the header

GIVEN that I am on a round's Explorer
WHEN I do have a project in my cart
THEN I see the cart icon in the header
AND an indicator of how many projects are in my cart

GIVEN that I am on a round's explorer
WHEN I add a project to my cart
THEN I see the cart drawer open
AND I see the contents of my cart

GIVEN that I am looking at the cart drawer
WHEN I click on view my cart
THEN I am taken to the cart

GIVEN that I am looking at the cart drawer
WHEN I click on continue shopping OR the X icon
THEN the cart drawer closes

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-8023&t=javk4LDbEb4uXiO3-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Fixed via https://github.com/gitcoinco/grants-stack/pull/1325

> WHEN I click on continue shopping OR the X icon

The x icon is something which is not there on the other dropdown for help section.
Would suggest keeping it consistent and hence that piece has been ignored as the code is reused
