### ISSUE TITLE
Update checkout experience

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1282]
**User Story:**
As a donor
I want a simplified checkout experience
So that I can quickly make my donations

**Acceptance Criteria**
GIVEN that I am on the checkout page
WHEN I do not have projects in my cart
THEN I see the Empty Cart state

GIVEN that I am on the checkout page
WHEN I do have projects in my cart
THEN I see the list of projects 

GIVEN that I am on the checkout page AND have projects in my cart
WHEN I change my donation value in the project list
THEN the "Your Contribution" amount in the Summary box updates with my total contribution

GIVEN that I am on the checkout page
WHEN I click on "Submit your donation"
THEN the donation flow begins

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-5813&t=javk4LDbEb4uXiO3-4)

**Tech Details:**
- this is removing the concept of a shortlist on the app

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
fixed via https://github.com/gitcoinco/grants-stack/pull/1325
