### ISSUE TITLE
update the indexer to output the data needed in the input tables described by Grants Ops

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1286]
https://docs.google.com/spreadsheets/d/1WygH89qMJAL_f_WrfrHldg8x5M78Mw2SszM5JjYXzvA/edit#gid=0

We could even write an endpoint of the indexer server that generates this tables based on the json data from the filesystem.

**Overview**
What's the goal

**Details**
Say more

**Comment by nfrgosselin** [comment]
After chatting with @baokiddy we're good with this story
