### ISSUE TITLE
Write a generic QF library to handle qf calculations with all the options needed

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1287]
https://www.notion.so/gitcoin/Linear-QF-Flow-v2-ae8793b2a9c34153863b36e574a017f1#d89e725a9b86433b9b3d05fd87e3aed8

**Overview**
What's the goal

**Details**
Say more

**Comment by vacekj** [comment]
https://github.com/gitcoinco/pluralistic.js
