### ISSUE TITLE
feat: update subgraph for new contract

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#1302]
### Description

This relies on simply updating the subgraph to point to the new goerli contracts + updating the ABI.
No new functions would need to be added BUT 
- update the application status to account for new application status  
- remove any breaking changes due to the application

note: update this on a test subgraph and not the original goerli one to make sure nothing breaks

**Comment by bhargavaparoksham** [comment]
This is done as part of this PR, https://github.com/allo-protocol/graph/pull/2
