### ISSUE TITLE
Fund contracts tab not displaying correct balances

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-stack#1319]
**Overview**
After finalizing the round, the `Fund contract` tab shows `Amount in contract: 0` and gives the impression that the contract still needs funding.

**Details**
![image](https://user-images.githubusercontent.com/9419140/229166726-80a0f830-1427-4563-800c-672e884f161f.png)

**Comment by thelostone-mc** [comment]
Yup we'd need to new behaviour where once the contract is ready for payout (AKA fee is deducted) , either this tab is disabled / we need a new behaviour

**Comment by thelostone-mc** [comment]
https://discord.com/channels/562828676480237578/1095744572870623363/1097561584110424176

**Comment by bhargavaparoksham** [comment]
design ref:

![Image](https://user-images.githubusercontent.com/22616592/233652663-8de2bc7d-4671-4a7e-a921-79abfb516cfe.png)
