### ISSUE TITLE
Fund contract: USD values (NaN) shouldn't be shown when fetching the price failed

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-stack#1321]
**Overview**
Showing NaN when there is no price data

**Details**

- [ ] Check if the price is valid and show, otherwise hide the USD 

![image](https://user-images.githubusercontent.com/9419140/229168257-71734b8a-ba37-4f87-98b0-3e9d919d8292.png)

**Comment by thelostone-mc** [comment]
@willsputra Can we do away with the USD amount ? :P

**Comment by DanieleSalatti** [comment]
> could we plan to look for an alternative solution and add it back in the future when we have more bandwidth? since this is one of the most-requested feature during usability testing.

As a first step we can make it optional and just hide it if we fail to fetch the price - would that be confusing? We could say "failed to fetch USD price" or something like that.

**Comment by thelostone-mc** [comment]
> As a first step we can make it optional and just hide it if we fail to fetch the price - would that be confusing? We could say "failed to fetch USD price" or something like that.

That works as well
