### ISSUE TITLE
Builder branding updates

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1330]
**Acceptance Criteria**
- [x] update header fonts and branding assets
- [x] update landing page fonts, imagery, and branding assets
- [x] change "Grants Hub" -> "Builder" (aka app name) in help dropdown menu
- [x] change app name on Create a project page
- [x] change app name in wallet connection toast
- [x] change app name on application page
- [x] change app name on Edit project page

**Product & Design Links:**
[Figma with imagery and assets](https://www.figma.com/file/78IRtNC6ZRZP8wg6Y2v01U/GPC-x-MMM?node-id=272-2404&t=3a2gk9smsfknDtnd-4)

Help dropdown menu
![Image](https://user-images.githubusercontent.com/15041635/229553599-4378bcc0-0c12-459b-957a-1e1e5b22461a.png)

Create a project
![Image](https://user-images.githubusercontent.com/15041635/229553962-37e6d054-a6f0-47b9-8350-759b2ea7bd86.png)

Wallet connection toast
![Image](https://user-images.githubusercontent.com/15041635/229554091-42d90a9f-7b53-4bd5-905e-a0cb51050f4a.png)

Application page
![Image](https://user-images.githubusercontent.com/15041635/229554170-80f2d5f2-ddad-4be5-931b-28596052e7ea.png)

Edit project
![Image](https://user-images.githubusercontent.com/15041635/229554295-5efcab87-7ac0-4b91-afd4-4189f71a2def.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by hmrtn** [comment]
The URL update will need to be done by whoever controls the domain.
