### ISSUE TITLE
Manager branding updates

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1331]
**Acceptance Criteria**
- [x] update landing page app name to "Manager"
- [x] update header branding / assets 

**Product & Design Links:**
[Figma with assets](https://www.figma.com/file/78IRtNC6ZRZP8wg6Y2v01U/GPC-x-MMM?node-id=272-3769&t=3a2gk9smsfknDtnd-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by hmrtn** [comment]
We don't have a light or dark toggle on round manager. So I implemented the light version only. 

If we want that, there should be a separate ticket.
