### ISSUE TITLE
Builder: Disable Apply button on Round Landing page after application end date has passed

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1333]
**User Story:**
As a project owner 
I want to know that the application end date has passed and that I can't apply 
So that I don't waste time writing an application 

**Acceptance Criteria**
GIVEN that I am on the Round Landing page
WHEN I look at the page 
THEN I see a disabled Apply button 
AND copy that the application period has ended. 

**Product & Design Links:**
Figma: https://www.figma.com/file/U4uRlyJJn92QiNUuyRxSvX/%5BWIP%5D-Grants-Application-%2F-Edit-Flow?node-id=687-5686&t=mq8i1cuP9Z7NxGxE-0 

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by codenamejason** [comment]
It looks like we are already doing this @michellema1208 

Line 42 in  `/builder/src/components/rounds/Show.tsx`

```typescript
const applicationEnded = roundState
      ? (roundState.round?.applicationsEndTime || now - 1000) < now
      : true;
```

![Screenshot 2023-04-04 at 11 30 34 AM](https://user-images.githubusercontent.com/9419140/229842686-0098f200-9321-4f54-9cd4-cd53ed8bd19f.png)

**Comment by thelostone-mc** [comment]
Closing this out as this is already implemented 🤚🏼
