### ISSUE TITLE
Chore: text / code cleanup on pre-round QF config

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1340]
**User Story:**
As a program manager
I want to configure my QF round
So that I can distribute my funds the way my community desires

**Acceptance Criteria**
Per discussion in the issue, we've merged these ACs into 1341. This is now a chore for text / code cleanup

~~GIVEN that I am on the first step of the round creation flow~~
~~WHEN I look at the page~~
~~THEN I **do not** see the QF settings section~~
~~AND I see the revised "Round Details" page title and subheading in the top left corner~~

~~GIVEN that I am on the first step of round creation flow AND have entered the required information~~
~~WHEN I click Next~~
~~THEN I am brought to a **new** second step called "Funding Settings"~~

~~GIVEN that I am on the new Funding Settings step~~
~~WHEN I look at the page~~
~~THEN I see the page title and subhead in the top left corner~~
~~AND I see the original QF settings and Matching Cap configurations WITH the same validations~~

~~GIVEN that I am on the new Funding Settings step AND have entered in the required information~~
~~WHEN I click on Next~~
~~THEN I am brought to the Round Eligibility step~~

**Product & Design Links:**
[Figma](https://www.figma.com/file/guY5OKIgM18SNa62OysBoe/%5BWIP%5D-Linear-QF-Flow-v2?node-id=21-7183&t=Bp1q2s1xor6pkPmE-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
The ACs were changed to only include the first one, rest are implemented in #1341
