### ISSUE TITLE
[Spike/AIP] Add contract-level enforcements to prevent users from reapplying or applying after application end date

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1347]
**User Story:**
As a 
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
This is something which should go on the AIP ! Not sure if this is something we want implemented at the contract level

**Comment by michellema1208** [comment]
@thelostone-mc got it - I'm marking this as a spike and will make it lower priority for now
