### ISSUE TITLE
Explorer: when a project is added, show confirmation in Nav cart bar

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1354]
**User Story:**
As a donor 
I want to see a confirmation when I've added a project to my cart 
So that I know that it's in my cart 

**Acceptance Criteria**
GIVEN that I click on the cart icon for a project 
WHEN I look at the page 
THEN I see the cart nav bar expand to show include the project I just added 

**Product & Design Links:**
* Figma: https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-5933&t=Rn9lxtji4roRkH1n-0 
* Loom from Melissa: https://www.loom.com/share/ced52f8ff54741dfae6406129cf86416 

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
@melissa-neira Wouldn't this be jarring when the cart opens up for every addition to the grant.
We've already got the visual aid in the form of :
- count on the cart
- the add icon changing 

Having that popout for every grant being added might be a jarring experience

**Comment by melissa-neira** [comment]
@thelostone-mc This is a feature that through user research and feedback, is meant to add delight to the overall UX of the donation experience - variations of this interaction occur in almost all traditional e-commerce sites, so I mirrored it in our UX. A lot of feedback we've gotten from users has them wanting more visual cues during the browsing experience. Happy to jam about this though! 🏄‍♀️

**Comment by thelostone-mc** [comment]
Hmm could we get more details on this ?

Such as 
- how do we handle multiple projects in cart 
- does the user have to dismiss it manually

**Comment by melissa-neira** [comment]
@thelostone-mc This interaction is meant to show the project most recently added to the cart. To view all of the projects in the cart, the user would just click on the cart icon to go the cart (no flyout menu would appear)

**Comment by michellema1208** [comment]
@thelostone-mc was this ticket already in addressed in your last batch of work around donation flow? 

if not, rereading the thread and @thelostone-mc 's questions, I would second @melissa-neira 's UX research here and recommend: 

- every time a project is added to cart, show popout with new project added 
- only close cart popout if user manually closes it 

This is pretty common in other ecommerce experiences, and since we're moving back towards the cart/checkout flow, it makes sense to keep it consistent

**Comment by thelostone-mc** [comment]
Had a discussion on standup last week with @nfrgosselin  + @willsputra  ! 
Decided not to do the confirmation modal as it would be adding friction. Will have a to explore a nicer solution if we feel the number bump up isn't evident enough (maybe a toast)

**Comment by michellema1208** [comment]
@thelostone-mc got it, thank you Aditya! Sounds good to me
