### ISSUE TITLE
Explorer: Update Cart Nav Bar to include confirmation message and option to "Continue shopping" 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1355]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**
Figma: https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-4438&t=Rn9lxtji4roRkH1n-0

See below designs - want to make sure the design is consistent: 
<img width="717" alt="Screen Shot 2023-04-05 at 2 52 32 PM" src="https://user-images.githubusercontent.com/26017180/230003479-b7402a88-7389-4532-9196-c9e887582e93.png">

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Would like to sync with design on why we are calling the this Shopping. Users aren't shopping for projects during a round but more like donating / contributing. Maybe we use something more generic like checkout. ?

**Comment by michellema1208** [comment]
@thelostone-mc @melissa-neira maybe we can change the secondary CTA to say “continue browsing” instead?

**Comment by melissa-neira** [comment]
@thelostone-mc @michellema1208 omg lol good catch - it's definitely supposed to say "continue browsing"! Fixed :)

**Comment by thelostone-mc** [comment]
Question : What happens when you click continue browsing ? 
If it's just closing the box -> does it need to be added cause we don't have a close option for other fly our menu in the navbar

**Comment by melissa-neira** [comment]
@thelostone-mc tbh it doesn't need to be there, clicking outside of the box could make it go away or even have the interaction show for a few seconds and it fades away.

**Comment by thelostone-mc** [comment]
closing this out based on above conversatoin
