### ISSUE TITLE
Explorer: Add mobile views for new donation flow 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1357]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**
* Figma: https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=526-14125&t=O6tCtF2DHicKhYDx-0

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Do we need to show the description on mobile ? It feels very congested in the current view

**Comment by thelostone-mc** [comment]
Still waiting for the updated design / ack that we aren't changing the design
