### ISSUE TITLE
Builder branding updates

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1366]
Fixing up some discrepancies on the Builder branding updates.

**Acceptance Criteria**

- [ ] Add "Gitcoin" text above "Builder" header [Figma](https://www.figma.com/file/78IRtNC6ZRZP8wg6Y2v01U/GPC-x-MMM?node-id=323-4350&t=jncZbJWWhfcqF5Ef-4)
- [ ] Margins should be 80px left and right for everything except the image. The image should be aligned to the right. [Figma](https://www.figma.com/file/78IRtNC6ZRZP8wg6Y2v01U/GPC-x-MMM?node-id=272-2404&t=jncZbJWWhfcqF5Ef-4)

**Comment by michellema1208** [comment]
closing this for now!
