### ISSUE TITLE
audit: fix excess ETH scenario on voting contract

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#1367]
### Description

- Handle scenario where excess funds are send while invoking voting contract
- Ensure if a single vote fails in the batch transaction -> funds are not stuck on the voting contract
- Ensure changes are raised against the beta-round branch

**Comment by KurtMerbeth** [comment]
PR: https://github.com/allo-protocol/contracts/pull/13

**Comment by KurtMerbeth** [comment]
AIP: https://github.com/allo-protocol/aips/pull/5/files
