### ISSUE TITLE
spike: create new Passport scorer for each new round

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1388]
**Overview**

**User Story**
As a 
I want to ... 
So that ... 

**Problem**: Given new Passport API changes, we want to have one scorer for each round, and this cannot be done in the FE because we would be exposing the key. We may want to explore having a backend application (similar to Indexer) that every time a new round is created, we automatically create a new scorer in the Passport API and enable users to add themselves to the scorer when they vote. 

**Goal:** The goal of this spike is to explore how we might want to integrate with the new Passport API and how we might want to create a scorer per round. 

**Details**
Context from Jeremy, Passport Product Lead (Discord thread: https://discord.com/channels/562828676480237578/1114274942188523600) 

**What is the benefit of creating new Passport scorers per round vs. existing implementation?**
Right now, when we create a new score (new weights) the old 'scorer' is not updated which means you'll be out of sync with the stamps and weights. I think this is a difficult issue for many integrators (including Allo) so i'd like to find a way where you don't have to update every time we make a change. I'm guessing that Allo would like to use our default weight (and threshold) automagically whenever we create a new score, which we'd like to happen monthly going forward. 

**What is the core use case for having new Passport scorers per round? Is there a benefit to Program Managers?
What is the risk of not implementing this change ahead of upcoming rounds?**
See above for these, but you'd have out-dated scores that wouldn't take into account our new stamps.

**Comment by gravityblast** [comment]
@michellema1208 do we still want to do it?

**Comment by michellema1208** [comment]
@gravityblast let's close this for now!
