### ISSUE TITLE
implement ipfs CDN

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1395]
**Overview**
What's the goal

**Details**
Say more

**Comment by vacekj** [comment]
First off, we need to implement this: https://github.com/gitcoinco/grants-stack/discussions/1129
after that, reassess if we still need a CDN. Personally, I think this will obviate the need for any sort of middleware.

**Comment by boudra** [comment]
@vacekj why not both? we definitely need to resize images to optimize loading and bandwidth but having a CDN will reduce our request and bandwidth costs considerably, since an image will have to be loaded only once from IPFS and served from our CDN. Even a small image when loaded a few hundred times will consume more Pinata bandwidth than just loading a big image once.

**Comment by vacekj** [comment]
> @vacekj why not both? we definitely need to resize images to optimize loading and bandwidth but having a CDN will reduce our request and bandwidth costs considerably, since an image will have to be loaded only once from IPFS and served from our CDN. Even a small image when loaded a few hundred times will consume more Pinata bandwidth than just loading a big image once. We also have to consider that we're storing other data apart from images.

Additional complexity, devops, fly.io costs, maintenance etc. If we can bring down our Pinata costs 10x by changing a few img srcs in, it might be better than to integrate and maintain a whole new custom piece of our stack.

**Comment by vacekj** [comment]
@boudra where can i find code for this new cdn service?

**Comment by boudra** [comment]
Sorry I forgot to mention this, it's not really feasible to implement and manage your own CDN if that's what you're thinking, we're using AWS Cloudfront, you can see it in the Production AWS account (aws.admin@gitcoin.co). 

I have done this exact setup in the past to reduce costs of similar services where they would charge crazy amounts for bandwidth and requests like what Pinata is doing, I can assure you the costs of Cloudfront are next to nothing and maintenance is almost non existent once it's created, in the end it's just a distributed reverse proxy with a cache.

In fact it's so cheap that we might just get by with the Free tier: https://aws.amazon.com/cloudfront/pricing/

Again, this CDN and the image optimizations are both solving different issues and they can co-exist, you can think of this as our own IPFS gateway, which now is pointing to Pinata, but it could potentially point somewhere else.

**Comment by gravityblast** [comment]
Thank you all for working on this draft ticket, it's been a while I wanted to solve this problem, and seeing all of you interacting here is amazing, we can finally 
spend less on piñata :)

What's the actual problem though? It's my fault, I didn't write a specific description of what we are trying to solve. 

We are spending 1K/month for piñata, for something that seems strange in web3 but it's a common solved problem in "web2", and using a content delivery service is the common way to solve this problem.

I love there are discussions about all the problems we can solve, in fact having a ticket about "Image Resizing" (#1129) is amazing!

But I would like us to focus more on real data and numbers when we try to solve a problem.

Plans on piñata are clear, for this months we have:

Gateway Bandwidth Used: 72.78 GB/ 7500 GB
Total Requests: 461_757/ 10_000_000

Votes have not even started, and the total requests look much more of a problem compared to the bandwidth. It's 1% vs 5%.

Shall we skip the piñata resizing service? 
Absolutely not, let's use it! We still have a maximum number of image resize there (500_000) so let's keep it in mind.

Are we going to win if we only resize image?
No; the "Fiesta" plan has a maximum of 1,000,000 gateway requests, and we had much more in the past rounds.

If we use a content delivery network as described in the simple title of this issue, I'm confident we can achieve our goal, and if we use the image resize service of piñata we can improve it even more, so I love the proposal of that ticket.

> Additional complexity

Content delivery services have been around for ages, any cloud providers had one after all the amazing work of companies like Akamai in the past. 
I would actually be surprised if a big company serves me a file from NY if I'm in Barcelona.

The lucky part in our case is that we are dealing with **immutable content**, and the URL contains its hash. 
So each URL can be cached by CDNs for ever, it's never going to change, so we will only have requests going to the CDN.

If you look at cloud front,  the first 10_000_000 are free, which is actually the limit of our 1K/month plan, that's crazy!

> devops

Luckily a CDN doesn't need devops, it's just a new URL caching content from an origin.
We can decide to use the CDN URL or the original one, without changing anything in our deployments.

> fly.io costs

Do we have more costs here? In theory we just have a new URL caching the one provided by fly.io.

> maintenance

It can be done by a non technical person, and tech people can decide to use the CDN URL or the origin one.

--------

Thank you all team for helping with this ticket, I wanted to fix this so much but we never had time for this.
If we implement all these things it's amazing!

**Comment by vacekj** [comment]
Didn't know that we would use CloudFront, in that case it's completely fine and you can disregard my comments about maintenance etc. I was worried we would be developing our own CDN. All good now. Resizing still would help i think, but only needs to be done once for the cache which is great.
