### ISSUE TITLE
Twitter verify doesn't signal success or failure

### ISSUE THREAD

**Issue by vacekj** [gitcoinco/grants-stack#1399]
**Overview**
<img width="337" alt="image" src="https://user-images.githubusercontent.com/10381200/231162714-0a60348c-79b7-4e29-a5ad-4ff92db92fdd.png">

**Steps To Reproduce**
1. Apply to a round
2. Verify your twitter
3. gets redirected back to the page, but no status on whether twitter verification failed or succeeded.

**Observed  behavior**
no feedback upon redirect

**Expected behavior**
some kind of feedback on verification status

**Comment by boudra** [comment]
https://github.com/gitcoinco/grants-stack/issues/1403
