### ISSUE TITLE
Manager - Stuck on indexing

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1402]
Tried to create a new round, and everything went smoothly until the indexing part of the process. I tried this a few times and always got stuck on this part.

<img width="1938" alt="Screenshot 2023-04-11 at 15 31 52" src="https://user-images.githubusercontent.com/87520659/231179566-1b274455-f3ac-432f-86da-e21c3206b94e.png">

**Comment by thelostone-mc** [comment]
Which network was this on @melissa-neira 
Which token 
Txn Id from etherscan

**Comment by melissa-neira** [comment]
@thelostone-mc it seems to be working now so we can close this issue out, but I defer that to you

**Comment by nfrgosselin** [comment]
Cool, let's close it
