### ISSUE TITLE
Lacking UX feedback on social verification

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1403]
**Overview**
Right now the user doesn't get any indication that the verification has gone through. See [Loom](https://www.loom.com/share/e3c2da03b68641f49baa96831580c0b2)

**Comment by codenamejason** [comment]
@nfrgosselin can we confirm if this is still an issue, I have received feedback that it is working.

**Comment by nfrgosselin** [comment]
We can't reproduce, so closing it out.

**Comment by nfrgosselin** [comment]
Re-opening this issue — you can see that you don't see a verified badge when you sign the initial social transaction: https://www.loom.com/share/e1d800e6e8564cabb3118b07e6c40a71

**Comment by boudra** [comment]
from @jesuloluwao :

> @codenamejason @boudra Hey I still have a customer unable to verify github. I asked them to make a video and they sent https://drive.google.com/file/d/1X0O9la1wlt7Tq8MNd-yNjUJlf27h30uq/view?usp=share_link. I was also able to verify that they have a public profile but they get a 403 error with a bad request
> In the video above, I've seen the issue is due to the case sensitivity in the organization name. Can we also include this in the error message in the UI?

this issue was due the case sensitivity I agree that we can make the messaging more prominent
