### ISSUE TITLE
More transparent application error

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1410]
**Overview**
Currently, if you submit an application after the application period closes then you just get a generic error. Let's update the error box to say:

headline: Round Application Period Closed
subhead: The application period for this round has closed. 

![image](https://user-images.githubusercontent.com/15041635/231223390-e2b13a44-8585-4c76-839b-5fb5111bb547.png)

**Comment by codenamejason** [comment]
We should actually disable progress when the user has already applied. This should have been done already: when you select the project from the dropdown to apply with it checks whether the application end time has elapsed.
