### ISSUE TITLE
Builder guide clicks through to wrong URL

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1411]
**Overview**
When going through the application flow in Builder, the "Builder Guide" link clicks through to the wrong direct link in support. It should click to this link: https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-grants-program/project-owners

![image](https://user-images.githubusercontent.com/15041635/231223637-ebfb8585-49fa-47a4-afb2-3af4c2ab4601.png)

**Comment by codenamejason** [comment]
Can we add this to PR #1408 @KurtMerbeth
