### ISSUE TITLE
Manager: Open Passport docs link on a new tab

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/grants-stack#1419]
**Overview**
On Passport question, "Learn more about Gitcoin Passport here" opens the passport docs link in the same tab, which might disrupt the round creation experience.

**Steps To Reproduce**
Create a round
On Funding Settings section, click "here" on Learn more about Gitcoin Passport here" next to the Passport question

**Expected behavior**
Open passport docs link on a new tab

**Screenshots**
![Image](https://user-images.githubusercontent.com/19514207/231245723-1f379ee8-5e2b-4a20-be70-7760c96dd172.png)

**Comment by hmrtn** [comment]
I think this is already included on main. But the link is not highlighted so it is hard to discern it being a link.
