### ISSUE TITLE
Explorer: Gray out donation button once round has ended

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1425]
Let's gray out the donation button so that it is clear to the user that they are not able to submit their donations after the round has ended. 

[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=489-13304&t=DXYH6h5TnTZTO8o4-4)

**Comment by thelostone-mc** [comment]
Shouldn't we block out the entire cart after the round has ended ?

**Comment by melissa-neira** [comment]
@thelostone-mc yeah, let's go with that!

**Comment by nfrgosselin** [comment]
Moving this over to the Solarpunk to-do board
