### ISSUE TITLE
Redundant top padding in the grant page

### ISSUE THREAD

**Issue by geoist1** [gitcoinco/grants-stack#1434]
**Overview**

Looks like there's a redundant top padding (pt-6) between the pre-defined heading (Description) and the user input. Makes descriptions look sloppy.

**Steps To Reproduce**
1. Go to the Grant Builder.
2. Start editing an existing grant and preview edits.

**Screenshots**
![image](https://user-images.githubusercontent.com/92825012/231449729-6f535681-4459-4eef-9b60-e47073236283.png)

![image](https://user-images.githubusercontent.com/92825012/231449566-7fdf0e3c-224b-4d16-9084-2a40a50c775f.png)

**Comment by geoist1** [comment]
Also, the text in this box is unnecessarily truncated.
![image](https://user-images.githubusercontent.com/92825012/232606649-4f0db85d-806b-4d57-b893-1495935bf4c5.png)

**Comment by michellema1208** [comment]
this was resolved - closing this out!
