### ISSUE TITLE
Builder - Banner to apply to a round showing up even though round has ended

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1435]
**Overview**
I'm able to see a banner telling me to apply to a round even though the application period has ended. [Loom](https://www.loom.com/share/64058cc041dd4845b969e5aca4d1ef18)

**Comment by michellema1208** [comment]
@melissa-neira do you know if this issue is still open?

**Comment by melissa-neira** [comment]
@michellema1208 I'm not 100% sure, but I do think this has been resolved in another ticket. feel free to close
