### ISSUE TITLE
View on Explorer button has wrong URL

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1438]
**Overview**
The "View on Explorer" button in Manager sends users to the grant-explorer.gitcoin.co URL. This should use the core "explorer.gitcoin.co" URL. See [Loom](https://www.loom.com/share/f5b791d3816c4174903c35a08a76de39)

**Comment by codenamejason** [comment]
Fixed this in the deploy setting and updated the `.env` for the link. Will take affect next build and deploy.

**Comment by nfrgosselin** [comment]
Sweet, thank you!
