### ISSUE TITLE
Clean up Explorer pre-round design

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1439]
**Overview**
The pre-round page on the Explorer isn't showing its [proper layout](https://explorer.gitcoin.co/#/round/1/0x421510312c40486965767be5ea603aa8a5707983). We want to clean up the design to match this [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=483-10998&t=wMy7pAZ3lbml5Ctb-4)

**Acceptance Criteria**
- [ ] Update background gradient
- [ ] Update spacing / fonts / overall design
- [ ] Add in new button states
- [ ] Add Matching Cap percentage stat
- [ ] Add thousands comma separator to Matching pool number

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=483-10998&t=wMy7pAZ3lbml5Ctb-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Would recommend moving this to team board and not on-call
