### ISSUE TITLE
Old URLs should redirect to new URLs

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1440]
**Overview**
Right now the old app URLs load the apps. They're supposed to redirect to the new URLs. 

**Details**
- [ ] grants-hub —> redirects to builder.gitcoin.co
- [ ] grants-explorer —> redirects to explorer.gitcoin.co
- [ ] round-manager —> redirects to manager.gitcoin.co

**Comment by KurtMerbeth** [comment]
@nfrgosselin Does it makes sense to keep the old domains and redirect them? we also could just delete the olds ones, since nobody should use them anymore.

**Comment by nfrgosselin** [comment]
@KurtMerbeth I think some people probably still have those URLs saved, so let's redirect them just to be safe

**Comment by michellema1208** [comment]
@gravityblast should we keep this open?

**Comment by vacekj** [comment]
these urls have been disabled by the vercel migration
