### ISSUE TITLE
Add Program Title to Explorer pre-round screen

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1448]
**Overview**
[This round](https://grant-explorer.gitcoin.co/#/round/1/0x905efbabe2d52cd648fadfafcec8d6c8c60f7423)'s title isn't showing up on Explorer (see screenshot)

**Screenshots**
<img width="973" alt="image" src="https://user-images.githubusercontent.com/15041635/231580749-49101214-ae40-44c9-ae3b-f11155c79a3a.png">

**Comment by thelostone-mc** [comment]
The phantom menace is the round title 
https://gitcoin.mypinata.cloud/ipfs/bafkreigbq56ux7llxrr6gjrr5xqdtkmlug637qa7xhkvnu7rzljitaviei

**Comment by KurtMerbeth** [comment]
I think he is maybe missing the programs name?

**Comment by nfrgosselin** [comment]
Ahh my bad — thanks for the shout. Moving this to closed.
