### ISSUE TITLE
Add Round Settings page > Round Details tab

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1452]
**User Story:**
As a program manager
I want to be able to edit my round details
So that I can make necessary changes before the round starts

**Acceptance Criteria**
GIVEN that I am on my round's details page
WHEN I click on the Round Settings tab 
THEN I see the round settings page
AND the three subtabs (Round Details, Round & Application Period, Funding Settings)
AND the Round Details subtab is selected

GIVEN that I am on my round's Round Settings tab
WHEN I am on a subtab
THEN I see the current round settings for that subtab

**Product & Design Links:**
[Figma](https://www.figma.com/file/guY5OKIgM18SNa62OysBoe/%5BWIP%5D-Linear-QF-Flow-v2?node-id=143-8834&t=oaaQsqSd6tVU7JGu-4)
[Loom of UX](https://www.loom.com/share/30521a647d074d49a7bc306809fbe450)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Fixed via https://github.com/gitcoinco/grants-stack/pull/1519
