### ISSUE TITLE
Application status not showing up on Builder

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1457]
**Overview**
Users are reporting that they are submitting applications, but then Builder is showing "no data" under the Rounds tab. They should be seeing their round data, as shown here:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/15041635/231594282-6d62e601-2bfe-485f-b610-e51624bc0de5.png">

**Examples**
- [this project applied to Eth Infra](https://manager.gitcoin.co/#/round/0xdf22a2c8f6ba9376ff17ee13e6154b784ee92094/application/0xdf22a2c8f6ba9376ff17ee13e6154b784ee92094-0), but is seeing this on their Builder page:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/15041635/231593967-acd78432-1513-4aaf-a7a0-519464af8127.png">

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by thelostone-mc** [comment]
Yup this is fixed
