### ISSUE TITLE
Add meta landing page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1459]
**User Story:**
As a donor/grantee
I want to see all rounds live on the protocol
So that I can figure out where I can participate

**Acceptance Criteria**
GIVEN that I am on the meta landing page (explorer.gitcoin.co)
WHEN I look at the page
THEN I see the page layout (header image, header text, footer)

GIVEN that I am on the meta landing page
WHEN I look at the page
THEN I see a card for a round

GIVEN that I am on the meta landing page
WHEN I click on a card
THEN the round's Explorer opens in another tab

- this also includes creating all components for the page (including round cards)

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=598-13499&t=wcYMkkoCTx7wODkI-0)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Get Rounds Currently Active

```
{
  rounds(
    where:{
      applicationsStartTime_lt: "current_timestamp" 
      applicationsEndTime_gt: "current_timestamp"
    }
  ){
    id
    applicationsStartTime
    applicationsEndTime
  }
}
```

**Comment by KurtMerbeth** [comment]
just found accidentally:
https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=526-14125&t=pzLnQKPa4tMjeT6K-0

but the ticket links to: https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=520-13401&t=995fK91btjDXWbIL-0

which one is the right one? @nfrgosselin @willsputra @melissa-neira

**Comment by KurtMerbeth** [comment]
@melissa-neira @willsputra can you export the header image in a way that we can actually import and use it?

**Comment by melissa-neira** [comment]
@KurtMerbeth the header image is only for the new Round Discovery page. The image we have right now is a placeholder as we're waiting for a graphic from MMM. If you want, we can use the image for now and swap it out when we have the final image. 
What format do you want the image in, PNG or SVG?

**Comment by willsputra** [comment]
@KurtMerbeth @codenamejason cc @melissa-neira use this for the latest meta landing page! so sorry for the confusion
https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=598-13499&t=RzExeqbVtskDxiS3-0
