### ISSUE TITLE
Populate meta landing page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1460]
**User Story:**
As a donor/grantee
I want to see all rounds live on the protocol
So that I can figure out where I can participate

**Acceptance Criteria**
GIVEN that I am on the meta landing page
WHEN I look at the page
THEN I see the Apply Now section at the top of the page
AND it's populated with the three rounds in their application period who have the least time remaining in that period

GIVEN that I am on the meta landing page
WHEN I look at the page
THEN I see the All Active Rounds section below the Apply Now section
AND I see the first nine active (i.e. in their voting period) projects, sorted by the least amount of time remaining in their voting period

GIVEN that I am on the meta landing page
WHEN I scroll down the page
THEN more active rounds load, with the same sorting logic

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=598-13500&t=QcG03T3I47bla3gP-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
Eng team — DM me whenever you pick this up. The implementation will be slightly different than the current Figma file

**Comment by michellema1208** [comment]
@nfrgosselin is this still relevant? @codenamejason @thelostone-mc are picking this up today if you have any updates to share re: implementation?
