### ISSUE TITLE
Finalize Round Results

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1475]
**User Story:**
As a program manager
I want to view and confirm my round results
So that I can finalize and payout my round

**Acceptance Criteria from #1455**
- [x] the table should have fixed height and scrollbars like in the stats page and figma
- [x] implements CSV downloads

**Acceptance Criteria**
- [x] GIVEN that I am on the Round Results page AND my round has ended
WHEN I click on the Finalize Results button
THEN the current distribution in the preview table is queued for upload
AND I see the Warning modal

- [x] GIVEN that I'm looking at the Warning modal
WHEN I click Cancel
THEN the modal closes
AND I see the latest version of the distribution in the preview table

- [x] GIVEN that I'm looking at the Warning modal
WHEN I click Continue
THEN I am guided through the finalization process and wallet transactions

- [x] GIVEN that I've initiated the finalization process
WHEN the process finishes
THEN I see the completion toast
AND I see the finalized version of the Round Results page
AND the round is marked ready for payout

- [x] GIVEN that I've finalized the round
WHEN I click on the "View on Etherscan" button
THEN a new tab opens with the finalization transaction on the relevant block explorer

**Product & Design Links:**
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=1086-43069&t=N9E3HUHadbyKhS3U-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by hmrtn** [comment]
This PR: https://github.com/gitcoinco/allo-indexer/pull/46
And this PR: https://github.com/gitcoinco/allo-indexer-client/pull/12

Are precursors to CSV downloading.

**Comment by vacekj** [comment]
@hmrtn The CSV download for matching data was already implemented, but I forgot to push my changes 🤦🏻‍♂️ sorry. The thing I was handing off was CSV download for the **vote coefficients**, which is independent of the matching data download, and code for this was already pushed when I posted the update yesterday.
