### ISSUE TITLE
HIGH: Project preview not showing when users are creating new prjoects

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1512]
Hello, I made this loom video https://www.loom.com/share/2105bae89e364d9baa9a856fbb5ac2fe

When users try to create a new project, they don't see the preview so they are unable to submit. I don't see any error logs in the console. Please check. I raised as High importance because users are unable preview therefore will not submit.

 > Hi, I'm creating a new project and I was stuck at the "project description". I try to upload some photos (by posting github URL) to illustrate our project, but it was not shown at the submission page. Then I thought it might be the network issue to download the photos,, and I switched to post with some texts for the project description, but it still didn't appear

**Link:** [Conversation with xiafubiao@padolabs.org](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/16143)

**Customer:** [xiafubiao@padolabs.org](https://app.intercom.com/a/apps/xaafeyri/users/643cef4110e9ec1dcd6a34bf/all-conversations)
**Customer ID:** 8dc28e23-a80f-4536-8dd8-404647e78d19
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/16143) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/mentions/conversation/15937

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464832/conversation/16250

**Comment by hmrtn** [comment]
Hi @jesuloluwao - thanks for reporting this. We are investigating and will report back with findings and a fix. Thank you!

**Comment by boudra** [comment]
Caused by this PR: https://github.com/gitcoinco/grants-stack/pull/1478
I recommend we revert it: https://github.com/gitcoinco/grants-stack/pull/1513

**Comment by hmrtn** [comment]
This should be resolved now!

**Comment by jesuloluwao** [comment]
Hi @hmrtn I noticed it worked for a bit but now the page loading has started again.

**Comment by boudra** [comment]
I am not able to replicate this issue again, did you try a hard refresh or clearing the cache? if it still happens do you mind sharing a loom with the console

**Comment by jesuloluwao** [comment]
It seems to work for me now.. And the other customers didn't return so it's safe to say it's working for them too.
