### ISSUE TITLE
Error when downloading application from Round Manager

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1521]
This is an internal request by Alex. I am unable to reproduce as I don't have access to the round manager account.

They mentioned there is a 502 error when downlaoding the ZKtech applications. Also we need to check the streams are okay as the number of applications so far seems very low. 

> 502 error when downloading ZKTech applications.

**Link:** [Conversation with alex@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/13914)

**Customer:** [alex@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/users/6437ade29d89148ea7f14c69/all-conversations)
**Customer ID:** e9ee46ec-7bf5-417d-ad61-9fa207b8023f
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/13914) when this issue is closed.

**Comment by michellema1208** [comment]
@jesuloluwao can you ask Alex to share a Loom recording of this error when downloading? We can then have whoever is on-call pair with her to resolve this

**Comment by akathm** [comment]
Hey- 

This was already fixed by the time this ticket was created 2 days later. Seems like we may be having some trouble bundling bug tickets, as this is the same error which both Kieran, Boris, and several round owners reported. Please group accordingly for tracking, if necessary.

Additionally the 502 error can be seen in event logs when the CSV button is pushed/called. Using our own event logs is likely a much more reliable method than "reproducing" given the round owner access gateway that Lolu mentions. Plus much lower lift than asking for a loom video when eng already has info available to see trigger of errors in the logs....

**Comment by akathm** [comment]
Question confirming a more thorough deep dive to make sure application ingestion is as-expected still stands, though.  I see now 11 total apps for ZK in particular - perhaps its just low but given all the issues, just want to double check we have a true source of truth.

**Comment by michellema1208** [comment]
@akathm - thanks for the update! 

re: source of truth - 

- To view all applications, you can cross-reference data from the [Allo Protocol Indexer](https://github.com/gitcoinco/allo-indexer) for the zkTech round: https://grants-stack-indexer.fly.dev/data/1/rounds/0x274554EB289004e15A7679123901B7F070dDa0fa/applications.json. 

- - If not already, you can install this JSON viewer extension so the output above is more human-readable: https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh 

- If you'd like to see data for other rounds on Mainnet, you can check out: https://grants-stack-indexer.fly.dev/data/1/rounds/

**Comment by akathm** [comment]
ooh amazing- thank you for sharing!!!

I can reliably alter this based on the variable of the round_id only, I'd
guess?


Cheers,
A

**Comment by michellema1208** [comment]
@akathm yes that'll work for any rounds deployed on Mainnet! I believe if you're checking for a round deployed on a network besides Mainnet, the chain id in the URL would also have to update depending on the network (i.e. I believe Optimism is chain ID 10, so the URL would be .../10/rounds/<round contract address>
