### ISSUE TITLE
Builder: Add more copy that the Application Preview page is what the project will look like on Explorer

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1529]
**User story**
As a project owner, 
I want to understand what I'm looking at when I'm on the Application Preview page 
so that I can make any edits accordingly 

**Acceptance Criteria**
GIVEN that I am on the Application Preview page
WHEN I look at the page
THEN I see a message explaining to me that this is a preview of what my project will look like on Explorer 

**Product & Design links**
* [Figma](https://www.figma.com/file/U4uRlyJJn92QiNUuyRxSvX/%5BWIP%5D-Grants-Application-%2F-Edit-Flow?type=design&node-id=647-5313&t=Mblf4FQ6fXkAhDM0-0)

**Comment by michellema1208** [comment]
@melissa-neira @willsputra this is non-urgent, but when I was testing I realized that on the new Application Preview page, we don't really tell the user that what they're looking at is a preview of what their project will look like on Explorer. 

If one of you has bandwidth, do you mind iterating on a quick enhancement design for that page? 

Thinking copy would be along the lines of: "Check out a preview of your project's public page on Explorer. This is what your project will look like to donors during a round, if you are accepted into the round."

**Comment by melissa-neira** [comment]
@michellema1208 sure thing!

**Comment by codenamejason** [comment]
![Image](https://github.com/gitcoinco/grants-stack/assets/9419140/acf77361-9739-46e7-9871-1f91f9d75259)
