### ISSUE TITLE
Manager: all applications are missing the "Created On" date

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1532]
**Overview**
On Round Manager, all applications are missing the "Created On" date

Example from test round: 
<img width="1424" alt="Screen Shot 2023-04-20 at 2 55 55 PM" src="https://user-images.githubusercontent.com/26017180/233461574-f5b41b41-28ee-4f49-af95-4e07bb736e08.png">

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by KurtMerbeth** [comment]
@michellema1208 
i think it is alrady fixed.
example:
https://manager.gitcoin.co/#/round/0x87306d9cc4fd16b702470e0ebee3c05162ff238b/application/0x87306d9cc4fd16b702470e0ebee3c05162ff238b-0

**Comment by michellema1208** [comment]
@KurtMerbeth yep you're totally right! I'll close out this issue.
