### ISSUE TITLE
Update hard-coded minimum donation warning

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1536]
**User Story:**
Right now the text under the donation button is hard-coded to say that $1 is the minimum donation. We want this to be dynamic and show the amount set for the round.

**Acceptance Criteria**
GIVEN that a round doesn't have a minimum donation
WHEN I look under the donation button on the checkout page
THEN I do not see a minimum donation message

GIVEN that a round has a minimum donation
WHEN I look under the donation button on the checkout page
THEN I see the minimum donation message
AND it shows the round's minimum donation setting

**Product & Design Links:**
![image](https://user-images.githubusercontent.com/15041635/233482912-8b626b8b-1e42-4288-b831-54115b202591.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
@nfrgosselin FYI moving this to Solarpunk board to be reviewed during Monday's IPM. Feels important to resolve before Tues if we can.
