### ISSUE TITLE
Manager: duplicate rows in application CSV download

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1542]
**Overview**
From Boris: there are weird mostly-empty duplicate rows that are included in the csv. not for every project though (see screenshot)

<img width="295" alt="csv" src="https://user-images.githubusercontent.com/26017180/233489636-55c4e3a9-6051-450b-a777-075c68823bb0.png">

This is the application CSV in manager

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by meg-fsc** [comment]
Closing as not able to reproduce -- likely user error
