### ISSUE TITLE
Manager: Matching funds table needs border

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1546]
**Overview**
Right now, there's no border around the Current Matching Stats table, making it a bit confusing.
![screencapture-bafybeige7hp4khzzxoagavgr3dfr77q5np4lx4k4btdzr7qggyx6u5ugbq-on-fleek-co-2023-04-21-11_14_05](https://user-images.githubusercontent.com/87520659/233597866-81ea5024-79dc-47fe-9fb9-6d34bd9f6c1d.png)

**Details**
See [Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=208-21959&t=OQbFbxGsR4EZ8x5g-4)

**Comment by hmrtn** [comment]
I believe this is already done!
