### ISSUE TITLE
Manager: round results tab error

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1561]
**Overview**
I'm getting an error when I go to the round results tab. The page gets stuck in a never ending loading loop. [Round](https://manager.gitcoin.co/#/round/0xda909fff4f9e119db5f2e4d042458eb13befea37)

<img width="2054" alt="Screenshot 2023-04-24 at 18 14 22" src="https://user-images.githubusercontent.com/87520659/234057750-2ec35970-6f3a-48b4-a5fe-e033a87ca075.png">

**Comment by thelostone-mc** [comment]
This is an expected error ! Lunarpunk is working on updating this to use the indexer while currently on staging this is pointed to the old API

**Comment by thelostone-mc** [comment]
This should be fixed now
