### ISSUE TITLE
Manager: round stats not loading correctly

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1562]
**Overview**
The stats are off on the round stats page. The matching funds table is empty as well. [Round](https://manager.gitcoin.co/#/round/0xda909fff4f9e119db5f2e4d042458eb13befea37)

<img width="2017" alt="Screenshot 2023-04-24 at 18 27 05" src="https://user-images.githubusercontent.com/87520659/234058819-1b9f45b2-5ed1-4ac0-b3e5-9abc01d26b08.png">

**Comment by thelostone-mc** [comment]
This should be fixed now
