### ISSUE TITLE
Manager: processing modal hangs on "Updating step"

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1570]
**Overview**
When making any transactions on Manager, it seems to hang on the "Updating" step and requires you to manually refresh the page to see that the transaction is successful

Context: https://discord.com/channels/562828676480237578/1098894869029732402/1100245629852205096 

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by thelostone-mc** [comment]
This was an issue which was fixed later on ! Approving / Rejecting applications works
