### ISSUE TITLE
Product Feedback

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1571]
> Hey - it's disruption joe - product feedback 

It would be nice to have a page where all of the grants showed up so i could make adjustments to all grants in bulk. 

Context can be found here https://share.getcloudapp.com/7KuzZk7p

**Link:** [Conversation with Violet Feather from Chicago](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/38306)

**Customer:** [Violet Feather from Chicago](https://app.intercom.com/a/apps/xaafeyri/users/6436b4cfdf2d43d5a8da6a60/all-conversations)
**Customer ID:** 5a166359-5a56-4392-abd4-9233c4b00ea5
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/38306) when this issue is closed.

**Comment by michellema1208** [comment]
Thank you @jesuloluwao! I've linked this ticket with an ongoing ticket I have tracking this feedback on the Allo General board: https://github.com/gitcoinco/grants-stack/issues/1567
