### ISSUE TITLE
No application showing in the Current applications section of the Rounds tab

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1572]
> Hi there, sorry to bother you, I have been checking daily on my application and its been "in review", but today when I checked, its in review but the "current applications" section is saying "no data", where it previously had details of this rounds application. With 25th being so close now, I just want to double check and make sure I haven't messed anything up 

I checked this behavior on my project too and I could confirm it. I see it on the main page but it no longer shows under the rounds tab

![image](https://user-images.githubusercontent.com/88308638/234179792-37cd39ac-7960-464a-a34b-840da7a4f73d.png)

**Link:** [Conversation with peter.c@growstudio.io](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/37722)

**Customer:** [peter.c@growstudio.io](https://app.intercom.com/a/apps/xaafeyri/users/643411ce94562d18126f49ad/all-conversations)
**Customer ID:** d346b9a7-9330-49f4-bf0a-cae7552ac8d5
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/37722) when this issue is closed.

**Comment by jesuloluwao** [comment]
@thelostone-mc tagging you as on call. I saw this hasn't been picked yet

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/38355

**Comment by thelostone-mc** [comment]
Could you share the project link @jesuloluwao  ?

**Comment by jesuloluwao** [comment]
@thelostone-mc it was this https://builder.gitcoin.co/#/chains/1/registry/0x03506eD3f57892C85DB20C36846e9c808aFe9ef4/projects/383

also my test project https://builder.gitcoin.co/#/chains/1/registry/0x03506eD3f57892C85DB20C36846e9c808aFe9ef4/projects/363

but it looks like it now shows since the round has started. But I could see at that point it was reported as seen in the screenshot

**Comment by thelostone-mc** [comment]
Ah nice closing this out then :D
