### ISSUE TITLE
Application preview not showing any details

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-stack#1577]
**Overview**
When I am on Builder and select a project then select "View Application" the page does not load any details.

**Screenshots**
![Screenshot 2023-04-25 at 8 54 00 AM](https://user-images.githubusercontent.com/9419140/234295900-47f05b1b-561d-4815-ada0-aa67091c187e.png)

**Additional context**
Link to project that showed this bug:
https://builder.gitcoin.co/#/chains/1/rounds/0xaa40e2e5c8df03d792a52b5458959c320f86ca18/view/bafkreibdukwvyhzva6dolfkdl7uasbrhhzq42w2gvfvooq4jcxtr7joxui

**Comment by michellema1208** [comment]
tracking this bug here: https://github.com/gitcoinco/grants-stack/issues/1650 

closing this issue out!
