### ISSUE TITLE
Builder: Image Resizing

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1581]
### Discussed in https://github.com/gitcoinco/grants-stack/discussions/1129

<div type='discussions-op-text'>

<sup>Originally posted by **giliomeejg** February 10, 2023</sup>
The previous Alpha Round saw some pages loading with 100Mb of un-resized images.  
This is detrimental to under served communities that fork out a fair bit of cash for bandwidth.

It appears that Pinata, which is already used, has an image resizing service that should be fairly easy to implement by simply adding '?img-width=200&img-height=100' to the end of the URLs being requested:
https://medium.com/pinata/resizing-ipfs-images-with-pinatas-image-optimization-tools-fb381bee58aa

As an example, here's an image that was loaded during the round, and resized on the client side to 296x120:
[https://gitcoin.mypinata.cloud/ipfs/bafy...vchr2maura](https://gitcoin.mypinata.cloud/ipfs/bafybeihnzpm7yykjwl66ko44wmmortqe45radvjzuil7g2fwvchr2maura) (3.9Mb)

Here's the same image, resized appropriately:
[https://gitcoin.mypinata.cloud/ipfs/bafy...vchr2maura?img-width=296&img-height=120](https://gitcoin.mypinata.cloud/ipfs/bafybeihnzpm7yykjwl66ko44wmmortqe45radvjzuil7g2fwvchr2maura?img-width=296&img-height=120) (21Kb)

This is a 99.4% reduction in bandwidth and a relatively simple implementation.
</div>

**Comment by vacekj** [comment]
Total image size is now under 5MB for the whole OSS round :) will be brought down even more with WebP and under-the-fold optimization in the future, but def. good enough for now.
