### ISSUE TITLE
Builder: hide past rounds on My Applications section

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/grants-stack#1583]
**Overview**
On my Project Details page, I can still see past rounds (rounds that are already over) in the My Applications section

**Steps To Reproduce**

1. Go to https://builder.gitcoin.co/#/chains/10/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/0
2. Notice that many of the rounds under "My Applications" have already ended 

**Expected behavior**
I should only see rounds in the "My Applications" section that are upcoming or active rounds (rounds that have not reached its end date). 

**Screenshots**
![Image](https://user-images.githubusercontent.com/19514207/234331291-7e26275f-2dc3-4a06-949d-6b12fc4ab521.png)

**Comment by ArslanYM** [comment]
@michellema1208 While trying to reproduce the bug locally, I'm facing an issue at this step : 

![test](https://github.com/gitcoinco/grants-stack/assets/104521101/cc4014e5-fe9c-47f7-9ed1-e2881dae097b)


***
Basically, to save and publish the app connect to your wallet and asks for a payment. How can I skip through this step such that I can view the applications and try to fix the bug?

**Comment by michellema1208** [comment]
hey @ArslanYM ! Great question - you should definitely use our staging environments to test on testnets! 

Staging environments: 
    - Builder: https://grants-stack-builder-staging.vercel.app/
    - Manager: https://grants-stack-manager-staging.vercel.app/
    - Explorer: https://grants-stack-explorer-staging.vercel.app/

You should be able to see the list of supported networks (production and testnet networks) available on each app, and you can create projects on testnets to test without real money.
