### ISSUE TITLE
Explorer: Project card spacing looks off

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1588]
**Overview**
The way the project cards are spaced in Explorer looks a bit off. It should be at least 4 cards per row, aligned with the margins on both the left and right. We can have more project cards on wider screens, but let's make sure the cards are aligned with the margins.
The cards themselves are looking weird too. There's a lot of space between the project name and the project banner.

Here's what it looks like currently:
<img width="1734" alt="Screenshot 2023-04-25 at 18 23 54" src="https://user-images.githubusercontent.com/87520659/234353046-2321df29-1825-42e3-a788-20ba40d792f5.png">

Here's what it should look like:
<img width="895" alt="Screenshot 2023-04-25 at 19 21 14" src="https://user-images.githubusercontent.com/87520659/234354165-b88ea9c1-f3ef-45ec-81f8-7f3010c9c814.png">

[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=526-14126&t=Y6Dxj6VtIU7jfyz1-4) for reference

**Comment by thelostone-mc** [comment]
This is not an on-call issue !
