### ISSUE TITLE
Explorer page returning failed transaction but transaction was successful

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1616]
> I just successfully paid the donation with my account, but the page shows that it failed<br>what should i do<br>Transaction Hash:<br>0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034

I think we had this issue in previous rounds too. I checked Datadog and I get this error

`console error: Error while bulk submitting donations:  Error: transaction was replaced [ See: https://links.ethers.org/v5-errors-TRANSACTION_REPLACED ] (cancelled=false, reason="repriced", replacement={"hash":"0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034","type":2,"accessList":[],"blockHash":"0x17a22b2d82c68a00a1fff97a9ceb728b0f67b09b85c43d039a9dcf92a9d4a5b9","blockNumber":17130300,"transactionIndex":118,"confirmations":2,"from":"0xe927FfB61EFB366AdCAf074Ff4f66514240f4730","gasPrice":{"type":"BigNumber","hex":"0x08659cbbe9"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x05f5e100"},"maxFeePerGas":{"type":"BigNumber","hex":"0x0b19cb4323"},"gasLimit":{"type":"BigNumber","hex":"0x021ec5"},"to":"0x12BB5bBbFE596dbc489d209299B8302c3300fa40","value":{"type":"BigNumber","hex":"0x1aa535d3d0c000"},"nonce":146,"data":"0x7aa54b680000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000002e000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c000000000000000000000000000e126b3e5d052f1f575828f61feba4f4f2603652af05829c76e3da92a8942378240ab4dc70c8c509f558eca9b0621c61054e9342c000000000000000000000000000000000000000000000000000000000000000d00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c00000000000000000000000000018aa467e40e1defb1956708830a343c1d01d3d7c60c037f9dfa5daee0f07bc26fb73393ef924e36c73c41ea6bd58029e1724de36000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c0000000000000000000000000003a5bd1e37b099ae3386d13947b6a90d97675e5e3be519f8c8f7ff2acb359dd757c5d2bf25b05d9fd29b8684885aa27f1fa487fcf000000000000000000000000000000000000000000000000000000000000000900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c0000000000000000000000000005afc7720b161788f9d833555b7ebc3274fd98da1cc6d33fe291d0fafb19cf8b833dc27d2f469fac52e3cc1f050ca4a0d83d66c74000000000000000000000000000000000000000000000000000000000000002b00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c00000000000000000000000000001d79bceaeaadfb8fd2f2f53005289cfcf4834640f1d31d427400106f3d2958225dd235ae60b6a7572fb5155201b723e1ae79632000000000000000000000000000000000000000000000000000000000000000a","r":"0xb254f04c2499fdf5214ae9731b98f25417e172efd9f75909fc24527f0adeaa43","s":"0x413d6de52009fc136e2b6648407208731e2ed5f2e1ac7e9965c156d3c369adc9","v":1,"creates":null,"chainId":1}, hash="0x22ca6dae84c345c646429a6ec1ad1a9495cfb753b7790ce069ab6879b5b9a991", receipt={"to":"0x12BB5bBbFE596dbc489d209299B8302c3300fa40","from":"0xe927FfB61EFB366AdCAf074Ff4f66514240f4730","contractAddress":null,"transactionIndex":118,"gasUsed":{"type":"BigNumber","hex":"0x01fb93"},"logsBloom":"0x00000000000000000000000000002400000000020000000010100000000000000000000000000000000000004000000000000000000000000000000000000000000000080000400000800000000000000000080000000200040000000100000000000000000008000000000000001010000000000400000000000000000040000000000000000000000000000000000000000000000800000000000000000000000000000000100000000000000800000000000000000000000000000000000002000000000000000000000000000000000000000000000000200000000000002000000000000000800000000000000000008000000008000000000000000000","blockHash":"0x17a22b2d82c68a00a1fff97a9ceb728b0f67b09b85c43d039a9dcf92a9d4a5b9","transactionHash":"0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034","logs":[{"transactionIndex":118,"blockNumber":17130300,"transactionHash":"0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034","address":"0x0F8e03A2175184228A429A118653D068F3a0Bb35","topics":["0x0064caa73f1d59b69adbeb65654b0f0953597994e4241ee2460b560b8d65aaa2","0x000000000000000000000000e927ffb61efb366adcaf074ff4f66514240f4730","0xf05829c76e3da92a8942378240ab4dc70c8c509f558eca9b0621c61054e9342c","0x00000000000000000000000012bb5bbbfe596dbc489d209299b8302c3300fa40"],"data":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c000000000000000000000000000e126b3e5d052f1f575828f61feba4f4f2603652a000000000000000000000000000000000000000000000000000000000000000d","logIndex":109,"blockHash":"0x17a22b2d82c68a00a1fff97a9ceb728b0f67b09b85c43d039a9dcf92a9d4a5b9"},{"transactionIndex":118,"blockNumber":17130300,"transactionHash":"0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034","address":"0x0F8e03A2175184228A429A118653D068F3a0Bb35","topics":["0x0064caa73f1d59b69adbeb65654b0f0953597994e4241ee2460b560b8d65aaa2","0x000000000000000000000000e927ffb61efb366adcaf074ff4f66514240f4730","0x60c037f9dfa5daee0f07bc26fb73393ef924e36c73c41ea6bd58029e1724de36","0x00000000000000000000000012bb5bbbfe596dbc489d209299b8302c3300fa40"],"data":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c00000000000000000000000000018aa467e40e1defb1956708830a343c1d01d3d7c0000000000000000000000000000000000000000000000000000000000000012","logIndex":110,"blockHash":"0x17a22b2d82c68a00a1fff97a9ceb728b0f67b09b85c43d039a9dcf92a9d4a5b9"},{"transactionIndex":118,"blockNumber":17130300,"transactionHash":"0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034","address":"0x0F8e03A2175184228A429A118653D068F3a0Bb35","topics":["0x0064caa73f1d59b69adbeb65654b0f0953597994e4241ee2460b560b8d65aaa2","0x000000000000000000000000e927ffb61efb366adcaf074ff4f66514240f4730","0xbe519f8c8f7ff2acb359dd757c5d2bf25b05d9fd29b8684885aa27f1fa487fcf","0x00000000000000000000000012bb5bbbfe596dbc489d209299b8302c3300fa40"],"data":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c0000000000000000000000000003a5bd1e37b099ae3386d13947b6a90d97675e5e30000000000000000000000000000000000000000000000000000000000000009","logIndex":111,"blockHash":"0x17a22b2d82c68a00a1fff97a9ceb728b0f67b09b85c43d039a9dcf92a9d4a5b9"},{"transactionIndex":118,"blockNumber":17130300,"transactionHash":"0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034","address":"0x0F8e03A2175184228A429A118653D068F3a0Bb35","topics":["0x0064caa73f1d59b69adbeb65654b0f0953597994e4241ee2460b560b8d65aaa2","0x000000000000000000000000e927ffb61efb366adcaf074ff4f66514240f4730","0xcc6d33fe291d0fafb19cf8b833dc27d2f469fac52e3cc1f050ca4a0d83d66c74","0x00000000000000000000000012bb5bbbfe596dbc489d209299b8302c3300fa40"],"data":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c0000000000000000000000000005afc7720b161788f9d833555b7ebc3274fd98da1000000000000000000000000000000000000000000000000000000000000002b","logIndex":112,"blockHash":"0x17a22b2d82c68a00a1fff97a9ceb728b0f67b09b85c43d039a9dcf92a9d4a5b9"},{"transactionIndex":118,"blockNumber":17130300,"transactionHash":"0x321dd1fdd718d87dec48a0a870d90698e1b18c8c7c998fd9b8183244574e4034","address":"0x0F8e03A2175184228A429A118653D068F3a0Bb35","topics":["0x0064caa73f1d59b69adbeb65654b0f0953597994e4241ee2460b560b8d65aaa2","0x000000000000000000000000e927ffb61efb366adcaf074ff4f66514240f4730","0x0f1d31d427400106f3d2958225dd235ae60b6a7572fb5155201b723e1ae79632","0x00000000000000000000000012bb5bbbfe596dbc489d209299b8302c3300fa40"],"data":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005543df729c00000000000000000000000000001d79bceaeaadfb8fd2f2f53005289cfcf483464000000000000000000000000000000000000000000000000000000000000000a","logIndex":113,"blockHash":"0x17a22b2d82c68a00a1fff97a9ceb728b0f67b09b85c43d039a9dcf92a9d4a5b9"}],"blockNumber":17130300,"confirmations":2,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x64c600"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x08659cbbe9"},"status":1,"type":2,"byzantium":true}, code=TRANSACTION_REPLACED, version=providers/5.6.5)`

Talking about transaction replaced. We need to handle this exception on the frontend I think.

**Link:** [Conversation with 1944279846@qq.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/41113)

**Customer:** [1944279846@qq.com](https://app.intercom.com/a/apps/xaafeyri/users/6440e30ff83bc617fcbfe3af/all-conversations)
**Customer ID:** cef09930-d65e-4177-b6eb-f9710a9cc46f
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/41113) when this issue is closed.

**Comment by thelostone-mc** [comment]
Will have figure out a solution for this. @michellema1208 Could we move this into the general board ?
This happens when you replace the txn by paying more gas after submitting the transaction. While everything is recorded on chain, our UI fails cause the original txn isn't the valid one (as it's been replaced)

**Comment by michellema1208** [comment]
@thelostone-mc done - will mark it as high priority for now
