### ISSUE TITLE
Builder: average contribution should not display $NaN if it's 0 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1623]
**Overview**
See screenshot in this tweet: https://twitter.com/AtlantisDAO1/status/1651174511956623361?s=20

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by boudra** [comment]
is there a PR for this?

**Comment by gravityblast** [comment]
https://github.com/gitcoinco/grants-stack/pull/1624

**Comment by gravityblast** [comment]
it wasn't linked because I fixed it from a discussion on discord, I didn't even know about this ticket
