### ISSUE TITLE
Explorer: homepage displays inaccurate number for "days left in round" 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1628]
**Overview**
Currently, the days left in the round is hard-coded to "20 days left in the round". 

<img width="1439" alt="Screen Shot 2023-04-26 at 5 33 52 PM" src="https://user-images.githubusercontent.com/26017180/234707993-104ff116-9c93-4e00-a14a-3c5edbb00145.png">

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by thelostone-mc** [comment]
Fixed via 02a8e1b7 in https://github.com/gitcoinco/grants-stack/pull/1634
