### ISSUE TITLE
Builder: Rounds tab does not have a valid "View on Grant Explorer" URL

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1630]
**Overview**
**Problem: ** When a project is in an active round, they should be able to find their Grant Explorer link via their Builder project profile, under the Rounds tab. However today, there is a button that says "View on Explorer" but when you click on that button, it takes you to a broken Explorer link. 

**Steps To Reproduce**
1. Go to Builder 
2. Find a project that is currently in an active round 
3. Go to Project Details page > Rounds tab 
4. For the currently active round, click on "View on Explorer" CTA
5. See that it takes you to a broken Explorer link 

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by KurtMerbeth** [comment]
https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=4777-37223&t=3CbHh54nCAmHLgDB-4
