### ISSUE TITLE
Builder: Rounds tab has rejected applications in "Active Rounds" section

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1631]
**Overview**
Try: Try: https://builder.gitcoin.co/#/chains/10/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/165 

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by meg-fsc** [comment]
@michellema1208 can you provide AC and more clarification on this ticket?

**Comment by michellema1208** [comment]
hey @meg-fsc - this ticket is outdated, and can be archived for now! 

Will and I had a chat about how we want to restructure the Rounds tab, and I'm tracking our proposed changes in this ticket on the Allo General board currently: https://github.com/gitcoinco/grants-stack/issues/1855
