### ISSUE TITLE
remove matchAmount from round metadata

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1636]
we already have the amount in the contract and calling directly the contract wouldn't update the metadata

**Comment by ArslanYM** [comment]
@gravityblast Can you provide some context to this issue?

**Comment by gravityblast** [comment]
@ArslanYM When a Round is created, we call the contract passing a round metadata pointer, which is the CID of the IPFS file we save with all the info about the round. 

It currently contains the `matchAmount` field, which is a field already present in the contract. 
The matchAmount field can be updated directly calling the contract. In this case the contract will have the new value, but the metadata will still have the old one. 
Since the source of truth is the contract, I would remove this field from the metadata to be sure it's never used and we never show outdated data.

The first thing would be to search in the codebase, especially manager, and see if we use it. 
In case we use it we need to change the code to fetch the value from the contract. 
Once we are sure we never use it, we can completely remove the field from the metadata we save on IPFS.

@boudra @bard I remember we don't use this field in the indexer but we only fetch the field directly from the contract, is it correct? 

@bhargavaparoksham @vacekj do you see any problem if we remove this field?

**Comment by vacekj** [comment]
@gravityblast @ArslanYM Great instructions above, I see no issue with following those.

**Comment by boudra** [comment]
@gravityblast yes, this field is not used in the indexer
