### ISSUE TITLE
Explorer: Project details text width too narrow

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1639]
**Overview**
The project description width is too narrow on the project details page, leaving a lot of white space that doesn't look great (especially on wider screens).

This is what it looks like:
1440px width
<img width="1103" alt="Screenshot 2023-04-27 at 13 16 49" src="https://user-images.githubusercontent.com/87520659/234860124-e4bcca0c-da1c-4a8c-ba2e-d39acb081e75.png">

much wider width
<img width="2072" alt="Screenshot 2023-04-27 at 13 17 03" src="https://user-images.githubusercontent.com/87520659/234860247-a1afe1c6-1224-40dc-bd54-26fe86f8dcc4.png">

**Details**
The text should always be the width of the gray dividing lines above it (there should be a breakpoint to this though so the width doesn't get out of hand.) The more responsive we can make this page, the better. See [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=526-15098&t=hoZer7opXuWcAiiF-4) for reference.

**Comment by meg-fsc** [comment]
@melissa-neira or @vacekj  can you add breakpoints to this ticket
