### ISSUE TITLE
Explorer: when loading explorer, the error screen flashes before loading 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1645]
**Overview**
Details, details, details

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by vacekj** [comment]
Resolved in main as part of the bundle size improvements.
