### ISSUE TITLE
Explorer: The cart is not updating across multiple tabs

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1649]
When you open mutiple projects on different tabs and then add them to the cart, the cart doesn't update on all the tabs and it sometimes overwrites the initial selection. The customer shared this reproduction video

https://user-images.githubusercontent.com/88308638/234976118-aa7fa762-3801-4cb6-ad85-f879e18c86d3.mp4

I was able to verify some of the error but only for one selection in the cart. Here's my reproduction https://www.loom.com/share/0f817639e46f437cbfbb2308f9fb8199

> Hi. I have an issue. Can't add more than 2 project to my cart, Next 2 I trying to add are getting added to my next cart/basket and so on. Tried to clean browser's cash but no luck still. Using Firefox + Metamask

**Link:** [Conversation with Mint Shark from Severobaykal'sk](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/41905)

**Customer:** [Mint Shark from Severobaykal'sk](https://app.intercom.com/a/apps/xaafeyri/users/644a73d785950169ae99271c/all-conversations)
**Customer ID:** 09ec902e-d434-47f3-985f-13ae56e9444a
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/41905) when this issue is closed.

**Comment by thelostone-mc** [comment]
Hmm @michellema1208 we should discuss this in standup ! I don't think we looked into syncing across tabs (not sure how tricky it could be)

**Comment by michellema1208** [comment]
ohh interesting @thelostone-mc - this is a great catch. I don't think this is a "blocking" bug per se as users can still donate. Shall we move this into Solarpunk?

**Comment by michellema1208** [comment]
Hi @jesuloluwao - is the user able to add all of the projects that they want to donate to, but in the same tab? 

If so, I would communicate to them that this is still a Beta product, so we haven't built out tab syncing features, and to please use the same tab to add projects and checkout.

**Comment by jesuloluwao** [comment]
@michellema1208 the user is able to. But imagine a use case where they need to open and go through multiple projects to read them and decide which ones to donate to. It won't be good experience to then have to go back to the home page to click through the projects in order to add them to cart.

**Comment by michellema1208** [comment]
@jesuloluwao Got it, thank you for sharing more details here! I'm going to move this to our Allo General board for now, but will mark as high priority for us to tackle.
