### ISSUE TITLE
Builder: "view application" feature is broken and stuck on the choose network page

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1650]
**Overview**
When I click on "View Application" from my Project Details page, I only see the "select networks" page and not my actual application. 

Link: https://builder.gitcoin.co/#/chains/10/rounds/0xda909fff4f9e119db5f2e4d042458eb13befea37/view/bafkreiae4jqeysgs5rgsxq7svssa7vj6unygbvueerujkdmmlkd24fppm4 

<img width="1428" alt="Screen Shot 2023-05-22 at 1 03 51 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/8bfbb761-b889-4a36-acf6-2193dc01c932">

**Steps To Reproduce**
1. Go to Builder 
2. Find a project that has at least one application to an active round 
3. Go to the Project Details page 
4. For that round, click on "View Application" 
5. See that it takes you to a page that is stuck on the network selection step, not the actual application

**Comment by meg-fsc** [comment]
@michellema1208 can you provide more details or criteria to reproduce?

**Comment by michellema1208** [comment]
@meg-fsc - Solarpunk team has some bandwidth to pick this up. Will move this over since I also have context!

**Comment by michellema1208** [comment]
this was resolved with merging DG
