### ISSUE TITLE
Out of Gas error while donating

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1652]
A couple of users have reported that they are getting out of gas errors when approving their donations with DAI. Here's a loom recording of such cases https://www.loom.com/share/e491b5d96e07451bbd875103ac33fbdf, also a couple transactions.

https://etherscan.io/tx/0x1b7ebc1fe14d80b8da6ebeb548ce0bad44e143f6f0618d215e817413a599d47b
https://etherscan.io/tx/0x397d21834d3f96daadffb0d444bd3cd7ec8e2f39a8d23a9fad245580db5191ce
https://etherscan.io/tx/0x640032feb7468221e99b390df6a027504188a4c60e33c3ce6e5e30f68746f1f8
https://etherscan.io/tx/0xe6215e8f8485acbaa18ab87e48fdda933e5c75c45f082984a160f94ae631449d

It seems to be happening frequently so can we check?

> I just tried to do a donation. The transaction didnt go through. My donations  arent done. And my gas fees is gone. Around 3$. WHats happening here? Can you check please? 0x53390320005d1f77b0be0b53b9d0ed4226e27def8227d6687ffa5acb0a979094

**Link:** [Conversation with Charcoal Crown from Great Malvern](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/42055)

**Customer:** [Charcoal Crown from Great Malvern](https://app.intercom.com/a/apps/xaafeyri/users/644aa7bd6d956e0d2908efa9/all-conversations)
**Customer ID:** 26d43e2e-99c9-4f4a-aa30-8c0cbda1fa67
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/42055) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/41742

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464832/conversation/41632

**Comment by thelostone-mc** [comment]
@DanieleSalatti do you think https://github.com/gitcoinco/grants-stack/issues/871 solves this issue ?

**Comment by KurtMerbeth** [comment]
@thelostone-mc 

seems like the transaction data itself is okay. I was confused by the amounts of the transactions, but it was the users input.
The problem itself seems to be gas related.

**Comment by jesuloluwao** [comment]
Hello guys @thelostone-mc @KurtMerbeth I think maybe we need to revisit this. We are now getting some errors when donating with ETH (I noticed the previous issue might have been limited to DAI). In this case, the UI displays an error at the approval stage but no connection to the wallet. See video here https://www.loom.com/share/5b53c65aad1348f3a2da3f36a39dc211.

I also get this error in the console

`TypeError: l.estimateGas.approve is not a function`

![image](https://user-images.githubusercontent.com/88308638/235264145-af299ca3-dc65-4337-a330-1bc0f55eda1d.png)

**Comment by jesuloluwao** [comment]
@michellema1208 @thelostone-mc 
We're still having reports of this issue 
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/46285

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/1da92543-227f-4640-8d14-a700318a9553)

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/46865

Wallet address 0xfD2D3F0DEddD68AEC3669c86Cb3369378Fa21544

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/330e06a5-4bcb-41ae-b4c2-068b86e160b4)

**Comment by jesuloluwao** [comment]
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/23eaec38-712a-4c1b-bddd-d9d065546fcb)

https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/47070

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/47199

**Comment by vacekj** [comment]
These are most likely incorrect tx submissions, rather than out of gas errors. The confusing ethers unpredictable gas limit error means that ethers couldnt simulate the tx and calculate the gas. Feel free to reopen if it occurs again.
