### ISSUE TITLE
Update random round images

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-stack#1669]
**Overview**
When you load the Explorer home page the round images are generated randomly based on the round address and this is causing some to be the same. 

**Details**
We currently have 24 stock images and if we ever have more than 24 rounds the images will start to duplicate. The effort on this issue should depend on when we plan to incorporate the round operator's ability to add a image to represent the round.

cc: @nfrgosselin @michellema1208 @willsputra

**Comment by michellema1208** [comment]
hey @codenamejason - I'm tracking the "adding a round image" feature request here: https://github.com/gitcoinco/grants-stack/issues/1621. We haven't met and validated this as a product team yet though FYI. 

I think having 24 stock images and ensuring that if there are <24 rounds the images don't duplicate, that's enough for now!
