### ISSUE TITLE
Explorer: center the cart on mobile

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1688]
**Overview**

Current state: 
<img src="https://user-images.githubusercontent.com/87520659/234338080-6b3c524d-34b0-4532-bfb1-28e38b4d1145.PNG" width=40% height=40%> 

This was moved out off: https://github.com/gitcoinco/grants-stack/issues/1587 

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Archives**
There should be no cart modal interaction in mobile because it just doesn't work. Let's use this [toast](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=534-19698&t=Y6Dxj6VtIU7jfyz1-4) instead and just let users click on the cart icon to directly go to their carts. The toast should be center aligned to the bottom of the viewport.

**Comment by michellema1208** [comment]
@melissa-neira - during standup, Jason mentioned that we could potentially center the cart on mobile instead. Would you recommend that or the Toast you initially linked? 

If we should still keep Toast, would you want the Toast modal aligned to the bottom or the top?

**Comment by melissa-neira** [comment]
@michellema1208 mobile designs never included the cart modal interaction because of lack of real estate, so we went with the toast instead. Ideally, the toast would be center aligned to the bottom of the viewport. 

Def not a priority and happy to have at least the cart modal centered for now 😎

**Comment by michellema1208** [comment]
This is super helpful, @melissa-neira thank you!! Let's stick with Toast. FYI I've extracted this task out of the original ticket for the team to pick up at a later point!
