### ISSUE TITLE
System Error during Payout

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1696]
Looks like we're getting this again. This user is unable to donate. I've attached a screen recording of the error.

https://user-images.githubusercontent.com/88308638/236159441-890858d5-fbf6-4821-a39a-01dc7c74d40c.mov

 Also, here are some screenshots of the console
![image](https://user-images.githubusercontent.com/88308638/236159672-f702342c-9fe6-48fb-8ffd-236a2e50d167.png)
![image](https://user-images.githubusercontent.com/88308638/236159762-e7c63679-e1bf-4ab1-9945-21ae47c02066.png)

There was no transaction carried out on chain so I'm not sure if this is the metamask issue

> Hello it keeps returning system error when I submit my donation, how do I resolve this?

**Link:** [Conversation with ericla1014@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/44755)

**Customer:** [ericla1014@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/6452b1e92c4e5ee5dc9cff11/all-conversations)
**Customer ID:** e9294b28-ddd7-4ae3-972d-c1a8554ef1df
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/44755) when this issue is closed.

**Comment by boudra** [comment]
@jesuloluwao are they using Metamask? if so can you ask them what version they're on? it's inside Settings => About

**Comment by vacekj** [comment]
Check again after #1699 is merged and deployed
