### ISSUE TITLE
All: standardize alerts

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1712]
**Overview**
Follow-up: https://github.com/gitcoinco/grants-stack/pull/1691

**Details**
Say more

**Comment by michellema1208** [comment]
@willsputra - would you be able to help audit/group the type of alerts that we're using throughout Grants Stack so Eng can build out reusable components? Per the convo in the linked ticket above, it sounds like it would be super helpful to start standardizing the alerts we're using across the board

**Comment by willsputra** [comment]
@michellema1208 audited the form alerts and the correct ones here!
https://www.figma.com/file/EiTjjZzsXGlBBFHpa41ArL/GS-UX-Audit?type=design&node-id=8%3A600&t=taFsQrqzwvQUU3Fq-1

**Comment by michellema1208** [comment]
thank you so much @willsputra!! Left one comment for you in the Figma
