### ISSUE TITLE
API Endpoint for Verifying Grant Contributions and Distinguishing Grantee/Funder Roles in Gitcoin Allo Programs

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/grants-stack#1715]
**Is your feature request related to a problem? Please describe.**
The problem we face is the need to verify whether a Passport holder was a grantee or funder in a Gitcoin Allo grants program. We require an endpoint to distinguish between matching eligible and non-eligible contributions, as well as to identify the associated funders and grantees.

**Describe the solution you'd like**
We propose the creation of an endpoint that takes an Ethereum address as input and returns information about its associated grant contributions, including whether they were matching eligible or non-eligible. The endpoint should also indicate if the address was a grantee or funder. This would allow the Passport team to verify and distinguish the different types of contributions and grantee/funder roles in the Gitcoin Allo grants program.

**Describe alternatives you've considered**
An alternative solution would be to access the Gitcoin Allo database directly to gather the necessary information. However, this method would potentially compromise the security and integrity of the data. An API endpoint would provide a more secure, controlled, and maintainable solution.

**Additional context**
This feature request is crucial for the Passport team to issue stamps that verify a holder's grantee or funder status in Gitcoin Allo grants programs. The ability to distinguish between matching eligible and non-eligible contributions will help enhance the credibility and utility of these stamps.

**Comment by michellema1208** [comment]
@erichfi I'm closing this issue for now - please let us know if this is something the Passport still needs, and we can reopen!
