### ISSUE TITLE
Use multicall to query contract data

### ISSUE THREAD

**Issue by 0xKurt** [gitcoinco/grants-stack#1739]
Currently we call a contract multiple times in sequence to query it's data.
Example in: [client/src/actions/rounds.ts#L82:loadRound()](https://github.com/gitcoinco/grant-hub/blob/7e3da81815920972df2347f0407e8866061eb03e/client/src/actions/rounds.ts#L82)

To have less RPC calls and thereby improve the performance, we should use multicall to query the whole data in one call.

**Comment by michellema1208** [comment]
@gravityblast is this still open?
