### ISSUE TITLE
Upgrade/Replace custom lit-js-sdk (deprecated soon)

### ISSUE THREAD

**Issue by 0xKurt** [gitcoinco/grants-stack#1741]
Currently we're using [lit-js-sdk-w-custom-provider](https://www.npmjs.com/package/lit-js-sdk-w-custom-provider) which seems to be a customized version of [lit-js-sdk](https://www.npmjs.com/package/lit-js-sdk). It will be deprecated soon.

> Very soon, this SDK will be deprecated and will only receive security updates. Find the latest SDK V2 here https://github.com/LIT-Protocol/js-sdk

We should upgrade to a newer version.

**Comment by michellema1208** [comment]
@gravityblast is this still open?

**Comment by gravityblast** [comment]
closing in favour of #2274
