### ISSUE TITLE
Donation confirmation

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#1751]
As a donor, I want to receive real-time confirmation that my donation was processed successfully.

Desired solution:
- Provide a toast message with the transaction confirmation message and a link to etherscan to view it
- This solution should be compatible across chains (eg -- include link to optimism scan if checking out on OP)

Open question:
- How to handle error states (I'm not sure what we do now / whether those are handled in metamask)

**Comment by michellema1208** [comment]
resolved with Donation History page - closing this out!
