### ISSUE TITLE
Builder: update Application Landing page for when applications have not opened yet

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1761]
**User Stories**
As a project owner 
I want to know if the application period for a round has started yet 
So that I know when I can start applying 

**Acceptance Criteria**
GIVEN that applications have not started
WHEN I look at the page 
THEN I see information about applications starting on X date
AND a disabled Apply CTA

**Product & Design links**
* [Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=4891-39873&t=AXp18ripODoi3NBL-4) 
* Try: https://staging.grantshub.gitcoin.co/#/chains/5/rounds/0xd8b77930ff589a27a7c15d825eb04860669da56b

**Comment by willsputra** [comment]
@michellema1208 let's disable the Apply button and add the start date below it! wdyt?

![Image](https://github.com/gitcoinco/grants-stack/assets/19514207/45894533-d37a-43cb-99bd-be324d2eac1a)

Figma: https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=4891-39873&t=AXp18ripODoi3NBL-4

**Comment by michellema1208** [comment]
this is perfect @willsputra ! I'm going to recategorize this as ready for Eng work :)
