### ISSUE TITLE
Incorrect Round Application Status Shown on Round Application Page

### ISSUE THREAD

**Issue by 0xKurt** [gitcoinco/grants-stack#1770]
When attempting to apply for a round before it has started, the round application page incorrectly displays that the application period has ended. The page should indicate that the application period has not yet started to avoid confusion for users.

![image](https://github.com/gitcoinco/grants-stack/assets/22886639/c1ceba41-c548-4ce7-9ed7-8a65b319b7de)

**Comment by michellema1208** [comment]
this has been resolved!
