### ISSUE TITLE
Explorer / Manager UI not updating match amount

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1793]
**Overview**
If a user deploys a round then later calls `updateMatchAmount` to change the pot size, the Explorer + Manager UIs don't update to show the correct pot amount. 

**Example**
- Match amount on [this contract](https://optimistic.etherscan.io/address/0x35c9d05558da3a3f3cddbf34a8e364e59b857004#readContract) is ~6 ETH
- [Explorer](https://explorer.gitcoin.co/#/round/10/0x35c9d05558da3a3f3cddbf34a8e364e59b857004) shows a match amount of 3 Eth

Discord discussion: https://discord.com/channels/562828676480237578/1106201534968123402

**Comment by DanieleSalatti** [comment]
I think we get that from the metadata? Looking into it rq.

**Comment by DanieleSalatti** [comment]
Forgot to update this, but yes – that comes from the metadata.

Looking at the logic [here](https://github.com/gitcoinco/grants-stack/blob/44c045d5c1d4b8dc1a5760a26f6f2e1a221ff192/packages/api/src/utils.ts#L211), it specifically comes from IPFS which explains why we still show the old value.
