### ISSUE TITLE
upgrade to wagmi v1 + viem, (133 => 27 kB)

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1797]
https://wagmi.sh/react/migration-guide
https://www.rainbowkit.com/docs/migration-guide
https://viem.sh/docs/ethers-migration.html

**Overview**
- [x] Upgrade from wagmi v0 to v1 (this drops ethers for viem in the meantime)
- [x] Remove ethers dependency
- [x] Replace all BigNumber usage with bigint
- [x] bump es version to bigint literals
- [x] upgrade rainbowkit to v1
- [x] get typescript to pass
- [x] get build to pass
- [x] get app working
- [x] get tests to pass
- [x] verify everything that is put on-chain
- [x] verify calculations
- [x] Replace all old ABIs with new ones, delete unused

**Projects**
- [x] Round Manager

**Comment by vacekj** [comment]
Doing Manager first as it's a non-end-user-facing codebase that I'm most familiar with.

**Comment by boudra** [comment]
@vacekj are you working on this? if so do you mind assigning yourself

**Comment by vacekj** [comment]
@gitcoinco/grantsround-product @gitcoinco/grantsround requesting review here for Round Manager according to the points written above. Also a code review would be awesome, most of the changes follow the same patterns, there should be very little to no actual logic changes.

**Comment by meg-fsc** [comment]
Testing notes:
- test all on-chain interactions
- creating a round, creating a project, donation, etc
