### ISSUE TITLE
Take a pass at all the packages included in the bundle and see if they are used or not, and if they are tree shaken

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1798]
**Overview**
What's the goal

**Details**
Say more

**Comment by vacekj** [comment]
Conclusions
- [ ] biggest weight we can shed remains ethers.js
- [ ] Another big optimization is converting the svgs of the landing banner and the 404 page to webp.

Created a new ticket to convert the svgs to webp. but we will leave the original svg in git, for posterity.
