### ISSUE TITLE
Manager: allow applications and round period to overlap

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1840]
**User Story:**
As a Program Manager
I want to accept applications even after my round has started 
So that I don't exclude qualified projects based on application timeline

**Acceptance Criteria**
GIVEN that I am creating a round
WHEN I am configuring application and round dates 
THEN I see a checkbox to accept applications throughout the round 

GIVEN that I want to accept applications throughout the round 
WHEN I check the box 
THEN I see the application end date field is read-only 
AND it populates based on the round end date selection 

**Product & Design Links:**
- [Loom walkthrough](https://www.loom.com/share/0088cad637a14e86bbbda735a32da47b)
- [Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?type=design&node-id=2058%3A44553&t=72M3DAIH6udXhBQJ-1)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Fix is at https://github.com/gitcoinco/grants-stack/pull/1790
