### ISSUE TITLE
Manager: errors with matching cap calculation when editing a round 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1841]
**Overview**
Two minor errors on the Funding Settings tab: 

- [ ] If I edit the "matching funds available" amount, the matching cap banner says "0% (0 DAI)"  -> it only updates after I edit the matching cap value 
<img width="1118" alt="Screen Shot 2023-05-19 at 10 47 48 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/78e55ad3-eb6a-4fe9-a3f0-e060c70a5b75">

- [ ] Round up the matching cap amount to the hundredths decimal place 
<img width="1436" alt="Screen Shot 2023-05-19 at 10 49 41 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/39f54670-afd0-46f0-8061-28136d31a80d">

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by DanieleSalatti** [comment]
Also I assume the banners should disappear if "no" is selected?

![Image](https://github.com/gitcoinco/grants-stack/assets/129965/c5480d6a-9b6f-460b-b9d5-d8d87ada4d13)
