### ISSUE TITLE
Show vote coefficient as "0" if donation is below threshold

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#1844]
Observed behavior: If the donation does not meet the minimum $1 USD threshold to qualify for matching funds, BUT does meet all other criteria (eg - Passport score), then the donation is shown with a vote coefficient of 1

Expected behavior: All donations that do not meet the minimum threshold to qualify for matching funds should show a vote coefficient of 0

**Comment by michellema1208** [comment]
@gravityblast do you know if this is still an open issue?
