### ISSUE TITLE
Create AIP for multi-round checkout

### ISSUE THREAD

**Issue by meg-fsc** [gitcoinco/grants-stack#1846]
**User Story:**
As a follow up to #1796 , we want to implement multi-round checkout functionality in Grants Stack. In order to do so we will need to make changes to the Allo protocol. This ticket covers discussing and agreeing on the format and timing of those changes with the Allo team. It does not include actually making any changes/commits.

**Acceptance Criteria**
AIP has been discussed with Allo team and posted to Github

**Product & Design Links:** None

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by meg-fsc** [comment]
@gravityblast we were talking about you picking this up if you're able

**Comment by gravityblast** [comment]
The implementation of AIP-13 has been merged  https://github.com/allo-protocol/allo-contracts/pull/69
