### ISSUE TITLE
chore: clean up the Explorer homepage

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1869]
**Overview**

- [x] Add Greenpill Q2 2023 round (confirmed real round): https://explorer.gitcoin.co/#/round/10/0x4195cd3cd76cc13faeb94fdad66911b4e0996f38 
- [x] Hide Meg's test round: https://explorer.gitcoin.co/#/round/10/0xde272b1a1efaefab2fd168c02b8cf0e3b10680ef 

**Details**
Say more

**Comment by DanieleSalatti** [comment]
#1870
