### ISSUE TITLE
Manager: remove error page popping up every time I take an action in Manager

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1890]
**Overview**
Problem: Every time after I take an action within Manager (i.e. approve/reject a project, edit a round, etc.), I briefly see the Manager app error page flash up on my screen, and then after a second it refreshes. Let's remove that error page from popping up, which is confusing. 

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/ 
2. Try to Approve or Reject a project, Edit a round, etc. 
3. When the transaction is successful, the page refreshes and briefly flashes the error page, before returning to the correct page

**Comment by vacekj** [comment]
due to dependencies, fixed in #1848

**Comment by vacekj** [comment]
Will be extracted out of #1848 to its own branch as #1848 will be broken up into multiple PRs.
