### ISSUE TITLE
[placeholder] Builder: add padding between end of application and footer 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1894]
**Overview**
Details, details, details

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by gravityblast** [comment]
@michellema1208 @melissa-neira can we add a screenshot just to be sure we work on the right thing please?

**Comment by melissa-neira** [comment]
@gravityblast I don't think this is an issue anymore but I'll defer to @michellema1208

**Comment by michellema1208** [comment]
closing this!
