### ISSUE TITLE
How many users have bridged to OP?

### ISSUE THREAD

**Issue by meg-fsc** [gitcoinco/grants-stack#1908]
We are considering launching a Optimism chain, Public Goods Network. We also will certainly run future rounds on a L2 such as optimism. As we prep to support users through this experience, we want to gather data about our users' familiarity with bridges.

For donor wallets in previous alpha/beta rounds...
- How many of them have used any (easily identifiable) bridge before?
- How many of them have bridged funds to optimism?
- For those wallets that have bridged funds to optimism... what are the most common tokens they hold? What are the average total holdings on optimism? How does this compare to their total holdings on eth?

Also curious for other things you think would be interesting to include!

**Comment by baokiddy** [comment]
@meg-fsc 

From initial review, I've run some scripts on Dune to get a few starting answers. Quick caveat, I ran into some difficulties filtering the full list of donor addresses on Dune and so worked with a subset of 8000. Additionally, I discovered an Optimism specific table in the Dune Abstraction schema and decided to use that as a base to guide analysis -  my goal is this guide will help us hone in on future steps outside this first dive into the data.

1. As clarified, I am still working on a full list of any/all bridge transactions, but review of the 8000 addresses [967](https://dune.com/queries/2602409) 

2. I located an Optimism created bridge table detailing bridge transactions from Ethereum. By focusing on this as a base table I filtered forAlpha/Beta Round donors [here](https://dune.com/queries/2601736/4313446). Even from the subset donor list

3. From analysis, it looks like there is a large focus on ETH transactions. Other tokens of interest seemed to be USDC, USDT and DAI. I'm still working on answering the questions regarding average token holding and the comparison between Ethereum and Optimism 

I've created charts illustrating these findings within the following dashboard -> https://dune.com/baokidi/alpha-and-beta-round-bridge-analysis

Please let me know if you have any questions, concerns or suggestions. I'll take that into account as I finish up/ideate on the remaining analytics.

**Comment by baokiddy** [comment]
Quick note, I am working on a more general script to check for bridges to Arbitrum, zkSync and StarkNet to better answer your question on general bridges rather than just Optimism.

**Comment by meg-fsc** [comment]
Thanks @baokiddy ! I just asked about the "large address list" question in the Flipside discord, too -- will see if there's any clues there.

This is super helpful data. My only question is around the average transaction amount -- this feels really high (26k average for eth?) Is there any way this query could be summing total transaction amount, or something?

**Comment by baokiddy** [comment]
Hey @meg-fsc Added in the requested analysis. Any word on the large address list for filtering?
