### ISSUE TITLE
Crypto newbies

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#1909]
We're starting to investigate fiat onramping support on our product roadmap. We think that this could potentially unlock a large new user base, both for donors and for projects. One thing that would be helpful in this investigation is to understand how many of our current users are "crypto newbies."

Can you help craft a definition of a crypto newbie?

Based on that definition, can we look back at both the beta round and recent-ish cGrants rounds to determine what percentage of projects and donors could be considered crypto newbies, and how the size of that population is trending over time?

**Comment by michellema1208** [comment]
closing this out!
