### ISSUE TITLE
Project description doesn't show up in the preview when creating a project in builder

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1910]
Here's a loom video https://www.loom.com/share/2ece8187a06340399450bcd9cfbd4d26

 > I am creating a grant in Builder and the preview does not seem to be working. It is not showing the grant description.<br>

**Link:** [Conversation with jon@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/52852)

**Customer:** [jon@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/users/64408252984bbaf990c82f0d/all-conversations)
**Customer ID:** dd87997b-2032-473a-9e31-a98d5aca5bb2
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/52852) when this issue is closed.

**Comment by michellema1208** [comment]
This has been fixed - live in production!
