### ISSUE TITLE
Manager: UX changes for Round Edit flow

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1915]
### 6/20/23 Update: Backlogged from Round Edit Flow milestone

**Overview**

Some remaining UX work to do on the Round Settings page (when in edit mode): 

**All**
- [x] When a field is disabled or in readonly mode, the text should be light gray not black 

**Round & Application Period tab**

- [x] When a field is disabled, the border has a gap in the bottom left corner 
- [x] When disabled, the text in the Application Start Date box should be light gray, like the Application End Date & Round Start date boxes 

<img width="1098" alt="Screen Shot 2023-06-02 at 11 16 56 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/3f9e627a-26b2-457a-9ab1-9a88e2e125e2">

**Funding Settings tab**

- [x] The header for payout token is cutoff if the selection is ETH 
<img width="1157" alt="Screen Shot 2023-06-02 at 11 25 43 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/bab887b0-3a58-4af5-9e92-02f3a1d42de3">

- [x] The "USD" header text should be light gray not black (make is the same as the ETH/DAI and % text color of the above headers) 
<img width="942" alt="Screen Shot 2023-06-02 at 11 26 52 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/e9015e08-9b9f-494b-a445-c11b50d59e60">

- [x] (TBD) Remove redundant "required" labels for YES/NO questions 

**Details**
Say more

**Comment by michellema1208** [comment]
@willsputra - when I was testing this feature, I noticed that for the Matching Cap & Minimum Donation threshold questions, we are adding the "required" label twice, one for the YES/NO question and one for the value (and this is consistent with your designs). However, if I select "NO" to these questions, I feel it's a bit confusing to still display "required" on the value fields, despite them being empty. 

Thoughts on adding some logic here, so if you select no, the "required" label disappears on the value fields? Or if you have a better idea UX-wise? 

<img width="1109" alt="Screen Shot 2023-06-02 at 11 29 46 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/3c2010c0-d24a-4bab-a6d4-f82f7cf28f41">

**Comment by hmrtn** [comment]
I suggest we implement and use common base components - as much of these fields are duplicated in the create round flow and follow much of the same logic. 

This work already exists in this PR: https://github.com/gitcoinco/grants-stack/pull/1873, which is no longer being merged..

**Comment by michellema1208** [comment]
hey @hmrtn - that's a great point, thank you for the callout here! I'm going to move this ticket to Design stage instead - may be worth for me / @willsputra / @melissa-neira to callout all of the unique components across Create + Edit flow and have this ticket cover both flows while also updating to use common base components
