### ISSUE TITLE
Identify Needs to Support PGN

### ISSUE THREAD

**Issue by meg-fsc** [gitcoinco/grants-stack#1933]
**User Story:**
As a public goods maxi
I want to make Grants Stack available on PGN
So that public goods can grow and thrive!

**Acceptance Criteria**
This purpose of this ticket is to:
`1` Outline the work that Grants Stack team will need to do to deploy the app on PGN. That information should be documented in a comment here, and we will ticket it out for future work.
`2` Outline any work that Grants Stack will need the Allo team to do to support this deployment. That information should be documented in a comment here and communicated to the Allo team.
`3` Outline any requirements or dependencies that the Grants Stack team has on PGN. That information should be documented in a comment here and communicated to Kyle.

No code should be deployed with this work.

**Comment by meg-fsc** [comment]
More info on PGN: https://docs.google.com/document/d/1ab97sRsPbQCL_q00I2E_kEE87df11mJXPrmk7yTThnk/edit#heading=h.cp5qs3wcao4n

**Comment by gravityblast** [comment]
created "PGN support requirement" doc https://docs.google.com/document/d/16If95eWJyyfr3RglmKM4vE-S15tzKjRBZenZKGYQ7JI/edit#heading=h.3sz9ikkc8ds
