### ISSUE TITLE
Explorer: typo in "approve token" modal during donation flow

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1941]
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/95af583d-938a-4004-9bcf-ba0417d4fb26)
 
Feedback from Kris. There's a space missing here after 'if'. Hope we can fix these little things, it looks very unprofessional.

> <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/762861273/42631fe69a586ce577c9a885/image.png"></div>

**Link:** [Conversation with kris](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/59952)

**Customer:** [kris](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/59952) when this issue is closed.

**Comment by vacekj** [comment]
No longer relevant as the component doesn't exist anymore.
