### ISSUE TITLE
Application closed message before the application date on the platform

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1948]
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/b41d138b-c5c8-4b2a-ac43-985a7b469beb)

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/f6bd550c-13cf-40f9-88f5-4701ed3dcac0)

 > <div dir="auto"><div dir="auto">Our partners from Ethereum Foundation seem to be having an issue with the round they are running. Seems they are getting the applications closed message before the close date. See the message from them below as well as attached screenshots.</div><div dir="auto"><br></div>Are there any quirks with the timing of application period and round period by chance? Got this error when trying to apply to a test round, but it shouldn’t be closed yet. <a href="https://explorer.gitcoin.co/#/round/10/0x21c8d23efa0fe20216ede8a92fc19bee3ab4cf70" target="_blank" rel="nofollow">https://explorer.gitcoin.co/#/round/10/0x21c8d23efa0fe20216ede8a92fc19bee3ab4cf70</a></div>

**Link:** [Conversation with ben](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/60371)

**Customer:** [ben](https://app.intercom.com/a/apps/xaafeyri/users/6423d9a531ebbc089cb7c9c2/all-conversations)
**Customer ID:** 0fd90e05-1964-4f34-a7bf-916de398448b
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/60371) when this issue is closed.

**Comment by michellema1208** [comment]
@jesuloluwao - this has been addressed in this PR: https://github.com/gitcoinco/grants-stack/pull/1920 

Feel free to double check on your end, and then close this ticket if it's working for you as well
