### ISSUE TITLE
[PGN Testnet] Manager: add PGN testnet network

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1962]
**User Story**
As a user of Manager 
I want to be able to switch onto PGN testnet 
so that I can create a round on PGN testnet 

**Acceptance Criteria** 
GIVEN that I am on Manager 
WHEN I click on the Network selection toggle 
THEN I see an option to switch to PGN testnet 

GIVEN that I want to switch onto PGN testnet
WHEN I click on PGN testnet 
THEN I am prompted to switch my network 

GIVEN that I successfully switch my network to PGN testnet
WHEN I look at the Network selection toggle
THEN I see the network that I am currently on is PGN testnet 

**Tech Details**

**Comment by meg-fsc** [comment]
Figma link for PGN logo: https://www.figma.com/file/PTVMnKfcH4br9yqYHU7ApR/Public-Goods-Network-Identity?type=design&node-id=27-2&t=vlN5DFwr9ccOZiWl-0
