### ISSUE TITLE
Issue downloading CSV

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1969]
> <div dir="ltr">Hey folks, I just tried to download a couple different CSV's from the platform and got this error message: <br><br><pre>Cannot GET //api/v1/chains/1/rounds/0x32c49d2dA5f6866a057e4aA2058c62A2974a5623/exports/vote_coefficients</pre>
<div><div dir="ltr"><div dir="ltr">
<div><br></div>
<div>Any idea what is happening and when this will be resolved?</div>
<div><br></div>
<div><br></div>
<div>
<img src="https://ci3.googleusercontent.com/mail-sig/AIorK4woXNz0vkIaQP45aZs1pWnObHi8U6uZi2sELJrFmY9zjphmmvd0_jiO6QEtfqGHtxK5lrIYsbI" width="80" height="80" style="color:rgb(34,34,34);margin-right:0px" alt=""><br>
</div>
</div></div></div>
</div>

**Link:** [Conversation with ben](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61086)

**Customer:** [ben](https://app.intercom.com/a/apps/xaafeyri/users/6423d9a531ebbc089cb7c9c2/all-conversations)
**Customer ID:** 0fd90e05-1964-4f34-a7bf-916de398448b
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61086) when this issue is closed.

**Comment by jesuloluwao** [comment]
Additional details 

 > I was trying to download the results and other details from the Advocacy Round. I also then tried the same on the climate and web3 community rounds and Connor tested as well. I believe on the OSS round.

**Comment by boudra** [comment]
@jesuloluwao can we close this task?
