### ISSUE TITLE
 Implement an automated test of the indexer using a local node

### ISSUE THREAD

**Issue by boudra** [gitcoinco/grants-stack#1971]
### 6/21/23 Update: Moved from Indexer Improvements milestone -> Product Backlog

Implement a test of the indexer with a local node, it could work like this:

- Launch local node
- Deploy contracts and seed with rounds and votes
- Index it and assert data is what we expect

**Comment by bard** [comment]
Closing this as the snapshot testing procedure covers the same ground and other kinds of verification can be done faster and more accurately with unit test, see https://github.com/gitcoinco/allo-indexer/issues/114.
