### ISSUE TITLE
Explorer: make URLs case insensitive

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#1975]
**Overview**
URLs should be case insensitive. If we have an ethereum addresses in the URL, the page should always work with:

* lowercase address 
* uppercase address 
* ERC-55 mixed-case address
* random not check-summed mixed case

**Steps To Reproduce**
In the current system this URL doesn't work:

https://gegitcoin.on.fleek.co/#/round/1/0xdf22a2C8F6BA9376fF17EE13E6154B784ee92094

but this works

https://gegitcoin.on.fleek.co/#/round/1/0xdf22a2c8f6ba9376ff17ee13e6154b784ee92094

**Additional context**

All our routes/components should take the address from params and lowecase it.
After that we can use the lowercase address directly where we can, or generate the check-summed mixed-case version in other cases like when we request data from the indexer.

**Comment by vacekj** [comment]
Additional ticket - always checksum all inputs in indexer client
