### ISSUE TITLE
bug: unable to edit round even though round has not started

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1982]
**Overview**
**From Michelle**: It looks like at the contract level, we might be requiring the application start time to also be in the future, so Connor and team are not able to edit a round even though the round start date is in the future, because the application start date is already past. I would expect to be able to make any edits to my round so long as the round has not started. 

**From Connor:** 

This instance we'd want to move the Zuzalu round (https://manager.gitcoin.co/#/round/0x74911b66c1d50cdaf24ba58cada60316a41f5c69 )
but we've tried this in the past and learned it won't work 

Zuzalu application period has started, not ended, and round hasn't started. We'd want to push the round start date back. But it's not possible. Just tried it via the UI, you just get this error and then it refreshes

<img width="732" alt="Screenshot_2023-06-26_at_8 27 40_AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/8134258a-07f0-4627-ab00-9a8f044412dc">

This is what it looks like trying to edit via etherscan, which we tried in the past. You have to put in values for all 4 fields. So the 
Only updates if new time is in the future and current set time is also in the future
 clause means you can't update any of them if the first thing (applications opening) has begun

Also related to: https://github.com/gitcoinco/grants-stack/issues/2094

<img width="533" alt="Screenshot_2023-06-26_at_8 28 36_AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/4f1df1d6-352a-4cae-a603-ba8149fb8d1d">

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by vacekj** [comment]
Same problem as https://github.com/gitcoinco/grants-stack/issues/2113#issuecomment-1780883799
