### ISSUE TITLE
User donations not showing on the Donations history page

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#1995]
The user made donations in optimsm but they aren't showing up in the donations page.

Here's a link to the user's donations page: https://explorer.gitcoin.co/#/contributors/0x06bc5be9ad18a47987c169c9947b9f72ae88b2d8

User's wallet: [0x06bc5be9ad18a47987c169c9947b9f72ae88b2d8](https://optimistic.etherscan.io/address/0x06bc5be9ad18a47987c169c9947b9f72ae88b2d8)

Their donations not showing up on the page:
0xf263324ded0f19cbfa3f2bee1a5b52db279f3e9c2dda26013123d70989b6348a 0.93USD
0x523318d9b91c305ea868b2d472edf186dd08f84e30c4c83a35f2c5fd5afdbf06 1.86USD
0x62688897b0e3054bcfaade7b695be28cd4a69f59ea9a95c2fb1aa0df1a9ab8a7 1.86USD
0xbbd483b4dc55cf01b4d0ae87c82a5e5c9a2278de5a1e4dda7c64d9ea0d9470ca 1.86USD
0x155bae935843770d879e5fbfa7c23b25538ebee7f0e63585ebd1542f40b1a7df 1.86USD
0x3e505b85549defccf6ce79e5d58788c4a3c95db68692507d177156b83c1cce88 9.32USD
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/9e7af717-3f9c-416f-8ba2-b2979c8435bb)

 > <div dir="ltr"><div><span style="color:rgb(36,39,42);font-family:&quot;Segoe UI&quot;,Tahoma,sans-serif;font-size:16px;white-space:pre">cleared the cache, didn't help.... send transaction ID</span><br></div><div><span style="color:rgb(36,39,42);font-family:&quot;Segoe UI&quot;,Tahoma,sans-serif;font-size:16px;white-space:pre"><br></span></div><span style="color:rgb(36,39,42);font-family:&quot;Segoe UI&quot;,Tahoma,sans-serif;font-size:16px;white-space:pre">0xf263324ded0f19cbfa3f2bee1a5b52db279f3e9c2dda26013123d70989b6348a 0.93USD</span><div><span style="color:rgb(36,39,42);font-family:&quot;Segoe UI&quot;,Tahoma,sans-serif;font-size:16px;white-space:pre">0x523318d9b91c305ea868b2d472edf186dd08f84e30c4c83a35f2c5fd5afdbf06</span> <span style="color:rgb(36,39,42);font-family:&quot;Segoe UI&quot;,Tahoma,sans-serif;font-size:16px;white-space:pre">1.86USD</span><span style="color:rgb(36,39,42);font-family:&quot;Segoe UI&quot;,Tahoma,sans-serif;font-size:16px;white-space:pre"><br></span></div><

**Link:** [Conversation with Ivan Lyskanych](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61678)

**Customer:** [Ivan Lyskanych](https://app.intercom.com/a/apps/xaafeyri/users/649bd7e0fb8e890eb2c04edb/all-conversations)
**Customer ID:** d41ef9ae-a030-41c1-8d59-44b66023a21c
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61678) when this issue is closed.

**Comment by bhargavaparoksham** [comment]
This has been resolved.
