### ISSUE TITLE
Feedback: Project website not required in Manager

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2002]
In creating a round (round manager) the project website is required. Can this be changed to a toggle? This made no sense for the citizens round (most people don't have a website for what they did)
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/a812c642-e579-446e-97d8-bbaa2b9f801c)

 > 

**Link:** [Conversation with kris](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61720)

**Customer:** [kris](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61720) when this issue is closed.

**Comment by michellema1208** [comment]
moving this to Productboard, closing this out!
