### ISSUE TITLE
Manager: typo with "Support input" label when creating a round (on both DG and QF)

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2005]
Note: This is happening on both DG and QF flows.

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/2ba181ec-96c6-4e0c-9666-38016a7d6b47)

 > Typo, when creating a round on manager, 3 p's here 

**Link:** [Conversation with kris](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61712)

**Customer:** [kris](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61712) when this issue is closed.

**Comment by michellema1208** [comment]
this bug was re-introducing with Direct Grants integration - reopening
