### ISSUE TITLE
FEATURE REQUEST: Link to Grantee Discord/Telegram

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2010]
> Request: The ability for a grantee to link to their discord and/or telegram group and have it live right at the top with the links to their twitter and github. 

I've had a grantee ask me if they could do this. 

They want to invite donors to join their community to collaborate 

From my perspective, I love that it creates an opt-in communication channel so grantees can let donors know when it's time to donate again. We're currently missing this and this could cause a giant increase in donor retention on the platform. They come for the grantees not for gitcoin.

Thanks for considering this! Please let me know any decisions made on this request 

**Link:** [Conversation with umar](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61774)

**Customer:** [umar](https://app.intercom.com/a/apps/xaafeyri/users/644fecfdcac7f116b83df189/all-conversations)
**Customer ID:** d8d4e4a0-e481-4e70-afe0-3eb459ad0b81
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61774) when this issue is closed.

**Comment by michellema1208** [comment]
moving to Productboard - closing this out!
