### ISSUE TITLE
Twitter account optional during grant creation but required during round application

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2017]
When creating a Grant in our round people saw that the project Twitter account was optional. That is how we indicated it in the Citizens Round. (no github needed, no twitter account)

Citizens Round: https://explorer.gitcoin.co/#/round/10/0x984e29dcb4286c2d9cbaa2c238afdd8a191eefbc 

However, when applying to the round they got the info it was required, which is entirely contradictory. This needs to be fixed. You can see this in the two screenshots below.

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/0acd3e95-f594-452c-91c7-a5c7d3fd22c9)
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/73f22567-34e3-4798-8003-567c17b8ac75)

**Link:** [Conversation with kris](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61716)

**Customer:** [kris](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61716) when this issue is closed.

**Comment by michellema1208** [comment]
@jesuloluwao - FYI, Twitter is always optional when creating a project, but a user can always go back and edit their project to add Twitter. What happened here is that the Citizens Round probably required Twitter as a part of the application when setting up the round, so this is working as expected. 

Closing this issue for now - please reopen if we have a round that did _not_ require Twitter, and this message occurs.
