### ISSUE TITLE
Manager: Error while deploying a round

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2021]
The user is getting errors while deploying a round in optimism

Here's a video reproducing the error
https://github.com/gitcoinco/grants-stack/assets/88308638/c3a286ab-3b26-4fa5-8838-ca64fb393a1a

Screenshots
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/66c255b2-e36b-4f5f-b5af-15f4e67912a0)

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/4936a74f-b270-446f-81b9-f4f0df9a7aa5)

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/3d205ddd-8c1e-4dc2-a110-c964f38aa8cf)

 > Followed your steps. Here's console screenshot + recording. Failing consistently. Another colleague has the same issue (testing from another country). My guess is many other users face the same issue. Please help. Frustrating. 

In addition, if you could pls connect me with your partnerships/marketing folks that would be great. Would like to explore how a non web3 nonprofit funder like my organisation, could leverage web3 tech. Beyond the self-help platform, but also sharing with the community + better apply web3 ways of working to "traditional" public goods

**Link:** [Conversation with support@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61998)

**Customer:** [support@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/users/64a311a86d6bb3b84d5017e3/all-conversations)
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61998) when this issue is closed.

**Comment by michellema1208** [comment]
@jesuloluwao is this issue still open? If not, can we go ahead and close this ticket?
