### ISSUE TITLE
[placeholder] WalletConnect support on Manager is not working

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2038]
**Overview**

From GR-OG Telegram: 
![Screenshot_2023-07-11_at_3 14 42_PM](https://github.com/gitcoinco/grants-stack/assets/26017180/66698e3c-a634-426c-8342-b50fc1727d62)

**Steps To Reproduce**
1. go to manager.gitcoin.co and click connect
2. select walletconnect
3. copy the QR code
4. paste it into the safe.global app
5. see a bunch of errors.

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
We are unsure if this is an error on Gitcoin's end or Safe's end. Multiple users are reporting issues signing into manager with wallet connect. However, Owocki tried using this same workflow to sign into a different app and hit the same issue, which suggests it may be on safe's end.

**Comment by meg-fsc** [comment]
Video from another customer with the same issue: https://drive.google.com/file/d/1hQ-3KY5uH-egm--3APGhEwY9Sqio1Kxh/view?usp=sharing

I was able to personally reproduce across Manager, Builder, and Explorer, but it's unclear to me if this is a Gitcoin or Safe issue
