### ISSUE TITLE
Explorer: after donating to a round, I am linked to the transaction instead of the Donation History page

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2065]
**Overview**

**Problem:** After I donate, the confirmation screen has a CTA to "See my transaction", but it should instead be a CTA to "View donation history" and take me to my donation history page. 

From Explorer: 
<img width="1438" alt="Screen Shot 2023-07-18 at 11 26 04 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/97a9c85d-327a-47f6-8f5a-78cb009c8c0b">

Figma: 
<img width="517" alt="Screen Shot 2023-07-18 at 4 36 57 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/86890aa2-75fc-4cf5-acf6-12d3b51fd070"> 

Figma: https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?type=design&node-id=2100-36501&mode=design&t=lXDaOQ2S8NgdVzYL-0 

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by bhargavaparoksham** [comment]
This has been resolved as part of MRC.
