### ISSUE TITLE
Manager: funding amount not showing up in UI even though contract has been funded 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2084]
**Overview**

**Problem**: We're getting reports from partners that after they funded their round contracts, the funding amount is not showing up on the Fund Contracts tab in Manager UI. See links below: 

Mantle Grants: 
* https://etherscan.io/address/0xf1c021df6dc6b2dc2e5a837cdfddc2f42503233b#tokentxns 
* Screenshot: https://share.getcloudapp.com/d5uDy5Oj 

Citizens Round: 
* https://optimistic.etherscan.io/tx/0xc0d110fa576ca891aaeec3a5879c03455397296f369ae4b677d12d26c0990e71 
* Screenshot: 
<img width="568" alt="Screen Shot 2023-07-24 at 4 23 10 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/b0d6cf0b-c769-43e7-a405-e5fc8230e61a">

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by meg-fsc** [comment]
Note: follow ups in GGOG telegram channel, this is blocking round managers from finalizing rounds. Need to pick up on Monday cc @michellema1208 @gravityblast

**Comment by meg-fsc** [comment]
Noting that this seems to be preventing managers from distributing funds, not just a UI bug.

To reproduce go to: https://rmgitcoin.on.fleek.co/#/round/0x859FaeAa266BA13bd1E72eB6dd7A223902d1adFE?debug=true

Notice that contract is fully funded
Notice that round results are finalized
Notice that grantees are unable to be paid (SS attached

![Image](https://github.com/gitcoinco/grants-stack/assets/72808678/c0ad3e73-2fd6-4c79-b87e-79d94e3ce3fb)

)
