### ISSUE TITLE
Donations not appearing on the donation history page

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2085]
It seems that recent donations are not appearing on the donations history page. I also tried myself and made a donation but it doesn't show on my donations history:

txid: https://optimistic.etherscan.io/tx/0x688e896e54e3891035ae110bdefcbfc952b655c012758fc4971e1f4c0c27b848
Dontated to: https://explorer.gitcoin.co/#/round/10/0x3e92c56dac4a262efcafce7a78381622092754fd

 <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/792613088/9c53bc6eac79124e00c68d12/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA+%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0+2023-07-25+%D0%B2+13.35.13.png"></div>

**Link:** [Conversation with topalinuipyh@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62835)

**Customer:** [topalinuipyh@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64aa97f9aea479bcc6ac628f/all-conversations)
**Customer ID:** ac9533de-3d90-44a9-b77f-5fe8e796c298
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62835) when this issue is closed.

**Comment by jesuloluwao** [comment]
Adding this user who cannot see their donations from Alpha round https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/62798

Donations: https://etherscan.io/tx/0x23bd25cddc958925036d30e4d054f985da745fd09cf5fbbc48dd7422d06ad7ef
History page https://explorer.gitcoin.co/#/contributors/0x765a16ca391A6b9249cfA65bf2D14C38722198e3

**Comment by melissa-neira** [comment]
Unable to reproduce - tested this on optimism, the txn did not immediately show up on the donation history page but it did show up after a few seconds. See [here](https://explorer.gitcoin.co/#/contributors/0x4614291bb169905074Da4aFaA39784D175162f79)

**Comment by jesuloluwao** [comment]
Hey @melissa-neira can you see the above user I linked? 
Donations: https://etherscan.io/tx/0x23bd25cddc958925036d30e4d054f985da745fd09cf5fbbc48dd7422d06ad7ef
History page https://explorer.gitcoin.co/#/contributors/0x765a16ca391A6b9249cfA65bf2D14C38722198e3

Their alpha round donation isn't showing in the history.. I added the link to the donations history so you can see and also the link to the alpha round transaction

**Comment by melissa-neira** [comment]
@jesuloluwao I think alpha round donations will not show because of contract updates that have been made. Please correct me if I'm wrong @gravityblast @michellema1208
