### ISSUE TITLE
Round needs to be fully funded before it's finalized

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2090]
**Overview**
We received feedback from round managers that they were unaware that a contract needs to be fully funded before a round is finalized. When a round manager attempts to finalize a contract that is not fully funded, it silently fails (does not finalize round, but user still pays gas and there is no error messaging.)

**Steps To Reproduce**
1. Go to round results
2. Attempt to finalize a round without a fully funded contract
3. Observe that the round is not finalized
Sample tx from round that was attempted to be finalized and failed: https://etherscan.io/tx/0xda91ef1e15a353c580c579c41b4532213eac1d0798428d1bb6bca9c05f9e0cad 

**Expected behavior**
@melissa-neira @michellema1208 can you work on this?

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by meg-fsc** [comment]
Here is a loom recording of the issue: https://www.loom.com/share/504d60295475450e8bce9190cc206a70

@melissa-neira when you're back would be great to mock up a modal that will pop up to tell people to fund the contract instead of queuing the tx!

**Comment by melissa-neira** [comment]
@meg-fsc here's a first pass at this - [Figma](https://www.figma.com/file/s5i7Nl2jPGnT3Pvwh5A9Pa/Manager-GG18?type=design&node-id=135-15553&mode=design&t=AzDqBCmWJXYpQwWn-4)
