### ISSUE TITLE
Feedback on round application

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2095]
Now that the application period can overlap with the round start date, the explorer link takes you to the live round once the start date/time is hit, and there is no link to apply to the round. I could see how this would be confusing for grantees who are trying to apply to a live round via explorer link - is there a way we could add an application button to the live round page? Thanks :) 

**Link:** [Conversation with kieran@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62882)

**Customer:** [kieran@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/users/6459e23a6e14be109b67c3ad/all-conversations)
**Customer ID:** 6bc82584-82f0-4cbe-96d6-d473f2212fe8
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62882) when this issue is closed.

**Comment by michellema1208** [comment]
porting this feedback to Productboard - closing this now!
