### ISSUE TITLE
Explorer: Passport banner is still showing up despite not selecting Passport during round setup

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2097]
The explorer still says "Your Gitcoin Passport is not currently eligible for donation matching" even though we selected "no" for passport defense when setting up the round
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/332e63ef-63e8-4708-8cf4-6ebd7a94e4f5)
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/509043b3-e652-4610-88b5-5f0a517b6efc)

**Link:** [Conversation with connor](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62935)

**Customer:** [connor](https://app.intercom.com/a/apps/xaafeyri/users/64346c0981755c3c9c27c8aa/all-conversations)
**Customer ID:** be25a915-f041-40fb-bba6-99990a2077db
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62935) when this issue is closed.

**Comment by bhargavaparoksham** [comment]
@michellema1208 This issue has been fixed with passport cleanup & passport widget PR.
