### ISSUE TITLE
Manager: Round Results tab should change state/copy after results are finalized

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2109]
**Overview**
When a round manager finalizes round results, the "finalize results" button disappears from the bottom of the page, but the rest of the page remains the same. The copy at the top is confusing re the state of results. We should change the copy or perhaps add some noticeable messaging that results have been finalized.

New designs [here](https://www.figma.com/file/s5i7Nl2jPGnT3Pvwh5A9Pa/Manager-GG18?type=design&node-id=2-4035&mode=design&t=UbKKsC7T9sGQxzAH-4) 

**Steps To Reproduce**
1. Go to a finalized round, eg https://rmgitcoin.on.fleek.co/#/round/0x859FaeAa266BA13bd1E72eB6dd7A223902d1adFE?debug=true
2. Notice that Finalize Results button is missing
3. Notice that copy still reflects non-finalized state

**Screenshots**
Attached
<img width="1575" alt="Screenshot 2023-08-03 at 8 26 40 AM" src="https://github.com/gitcoinco/grants-stack/assets/72808678/70f4ee39-3ef1-4cab-abf2-092546e415b1">

**Comment by melissa-neira** [comment]
Designs [here](https://www.figma.com/file/s5i7Nl2jPGnT3Pvwh5A9Pa/Manager-GG18?type=design&node-id=2-4035&mode=design&t=UbKKsC7T9sGQxzAH-4)
