### ISSUE TITLE
Prevent user from paying round before results are finalized

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2111]
**Background:**
The China Community Round is not able to distribute results because they had tried to distribute results before finalizing the round, and the contract got into a bad state. We have a fix coming on the contract level, but in the meantime, we want to prevent anyone from hitting this state in the front end. 

More info in Discord here: https://discord.com/channels/562828676480237578/1136408839705600040/1136556220359131136

**Designs**
[Figma](https://www.figma.com/file/s5i7Nl2jPGnT3Pvwh5A9Pa/Manager-GG18?type=design&node-id=2-4035&mode=design&t=UbKKsC7T9sGQxzAH-4)

**Acceptance Criteria**
GIVEN that I have not yet finalized results
WHEN I attempt to fund a round
THEN I should not be able to fund a round

This ticket needs designs that disable the finalize round buttons on the front end and present copy/warnings to the user to make sure they don't get into this state.

**Comment by melissa-neira** [comment]
Designs [here](https://www.figma.com/file/s5i7Nl2jPGnT3Pvwh5A9Pa/Manager-GG18?type=design&node-id=2-4035&mode=design&t=UbKKsC7T9sGQxzAH-4)
