### ISSUE TITLE
Manager: Unable to edit round application end date

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2112]
**Overview**
I went to edit my round end date so that I could finalize results. However, I'm unable to edit my round end date because my application end date must be before my round end date, and the application end date is not editable.

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/#/round/0xbd84a5c0affbcd4bf285ab20ebecae20f0a31f36?debug=true
2. Click on round settings -> dates
3. Try to edit the round end date to an EARLIER date

**Observed  behavior**
Loom: https://www.loom.com/share/b635255cc84a437cb1640fbfc02c649a

**To fix**
When "Enable rolling applications is enabled," and the round end date is changed, the application end date should automagically do the same thing

**Comment by vacekj** [comment]
@meglister loom is gone - just need the chain that this round is on - I can't find it on any of our chains.
