### ISSUE TITLE
Indexer returning inconsistent matching results

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2118]
**Overview**
Geo Web has twice reported that they're getting inconsistent results when finalizing their round. This step calls our indexer to calculate the quadratic funding equation.

I am having a hard time reproducing it, but they have sent me their results which I have summarized here: https://docs.google.com/spreadsheets/d/1LWIcz90db6S4E2Welot5fX8xVDf_zGuq0y-Glm18j7A/edit#gid=0

CSV exports of results here: https://drive.google.com/drive/folders/1aKBmAV4c-s6G8qutVB5r-W_-pqb97ZEW?usp=sharing

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/#/round/0x3E92c56Dac4a262efcAfCE7a78381622092754fD?debug=true
2. Click Round Results
3. Download CSV of matching distribution
4. Play around with the round saturation options -- switch between keep as is / scale up, refresh the page, etc. There is definitely some caching issues but I'm less worried about those than the actual calculations.

**Comment by meglister** [comment]
PS I asked the user where he is located to see if we could possibly be hitting different servers (my only thought on how this could be happening) -- we are both US based so likely not it. He was using Brave and I am using Chrome

**Comment by bard** [comment]
More context: https://github.com/gitcoinco/passport/issues/1562

**Comment by bard** [comment]
Closed by https://github.com/gitcoinco/passport-scorer/pull/341
