### ISSUE TITLE
Explorer: Whitelist Fantom's valueless token for voting 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2121]
**User Story:**
As a supporter in the Fantom round 
I want to be able to use a valueless token to vote for the projects that I want to support
So that I don't need to use real FTM tokens 

**Acceptance Criteria**

GIVEN that I am supporting projects in a Fantom round 
WHEN I checkout my cart 
THEN I see an option to "checkout" using the valueless token 

**Product & Design Links:**
* [Product proposal](https://www.notion.so/gitcoin/Proposal-Valueless-token-for-Fantom-QF-76f985a2f2b04fadac4a5829704a6736?pvs=4)
* Confirmed with Fantom team with only GcV for voting / confirmed FTM will be used for matching pool 

**Tech Details:**
* Fantom's valueless token - GitcoinVote (GcV) contract address: 0x83791638da5EB2fAa432aff1c65fbA47c5D29510 
* Fantom will be doing the following 
> * Creating the valueless token and sharing the contract address with GS team 
> * Setting up a way to distribute the valueless token (i.e. faucet for the valueless token) 

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by meglister** [comment]
Token:
GitcoinVote (GcV) 0x83791638da5EB2fAa432aff1c65fbA47c5D29510

**Comment by gravityblast** [comment]
@michellema1208 @meglister do we have the logo/icon?

**Comment by meglister** [comment]
![GcV_adobe_express](https://github.com/gitcoinco/grants-stack/assets/72808678/bf501fdd-6ec7-499b-8bbc-480352146684)

**Comment by meglister** [comment]
@gravityblast I attached the SVG above and am also linking to the file here: https://drive.google.com/file/d/1nvOldrR0CRD2JPNMUJ76vj3Fj1uA88OQ/view?usp=sharing

**Comment by michellema1208** [comment]
![new](https://github.com/gitcoinco/grants-stack/assets/26017180/c326942c-46ff-4ef3-a9c0-302d3bbf352e)
