### ISSUE TITLE
[Polygon] [GS] All: Add Polygon Mainnet and testnet as a network on Grants Stack 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2130]
**User Story:**
As a Grants Stack user  
I want to be able to use Grants Stack on Polygon 
So that I can run a round on Polygon 

**Acceptance Criteria**
GIVEN that I am on Grants Stack (Builder / Manager / Explorer) 
WHEN I click on the network selection toggle 
THEN I see that Polygon is a supported network 

GIVEN that I am on Manager
WHEN I am setting up a round
THEN I see payout token options include MATIC, ETH, USDC

GIVEN that I am on Explorer
WHEN I am checking out projects in a round on Polygon 
THEN I can set my donations on Polygon to be in MATIC, ETH, USDC

**Product & Design Links:**

**Tech Details:**
* Chain Deploy checklist: https://www.notion.so/gitcoin/Chain-Deploy-Checklist-d4ed8c6664f14ac3b2da0f0d9c9a6219?pvs=4
* Supported chains on LIT: https://developer.litprotocol.com/v2/resources/supportedchains/ 
* Contracts: https://github.com/allo-protocol/allo-contracts/blob/main/docs/CHAINS.md 
* Tokens to be supported: MATIC, ETH, USDC
* Add support for Polygon Mainnet & testnet 

**Tasks**
- [ ] Check that LIT supports Polygon Mainnet and testnet 
- [ ] Check that the tokens we want to support on Polygon support the `permit` function

**Open Questions:**
* 

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by gravityblast** [comment]
@gitcoinco/grantsstack-engineering check erc20 compatibility with the permit function

**Comment by gravityblast** [comment]
https://www.notion.so/gitcoin/Chain-Deploy-Checklist-d4ed8c6664f14ac3b2da0f0d9c9a6219

**Comment by gravityblast** [comment]
check/update LIT js custom packages

**Comment by michellema1208** [comment]
MATIC does not support permit - need to confirm with Polygon team if we can skip support for MATIC on checkout

**Comment by vacekj** [comment]
@gitcoinco/grantsstack-product changed the point of this to 2 (tentatively 3) to account for builder using very outdated packages and the chain, token, and asset handling being scattered accross the 3 apps.

**Comment by vacekj** [comment]
blocked on the subgraphs not being deployed @gitcoinco/grantsstack-product @thelostone-mc

**Comment by gravityblast** [comment]
> MATIC does not support permit - need to confirm with Polygon team if we can skip support for MATIC on checkout

@michellema1208 @vacekj MATIC is the actual native token in Polygon, same way we have ETH on mainnet, so it's not an ERC20

**Comment by michellema1208** [comment]
@gravityblast @vacekj We got an update from Polygon team that the tokens they'd like to have supported are: MATIC, ETH, USDC 

I've updated the ticket above as well! // cc: @meglister

**Comment by vacekj** [comment]
Matic And usdc support is fine, but eth (in the form of wrapped eth) I'm pretty sure we can't support with our current system (@gravityblast for confirmation) because it lacks permit.

**Comment by gravityblast** [comment]
yes your are right @vacekj , polygon WETH doesn't support the permit function
