### ISSUE TITLE
Manager: consolidate the Applicant Criteria step of the round creation flow 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2142]
**User Story:**
As a Program Manager 
I want to create a round 
So that I can run a round on Grants Stack 

**Acceptance Criteria**
GIVEN that I am on the Applicant Criteria step of the round creation flow 
WHEN I look at the page 
THEN I see a section for eligibility criteria, requiring project socials, and application questions 

**Product & Design Links:**

**Tech Details:**

**Open Questions:**
* How might we organize this page such that it is not overwhelming, but also enables the Program Manager to get the information they need from applicants? 

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by gravityblast** [comment]
can we close this issue @michellema1208 ?

**Comment by michellema1208** [comment]
@gravityblast this is part of a future roadmap item to improve the onboarding process onto Manager! Is it ok if we keep it open?
