### ISSUE TITLE
[Direct Grants] [Allo] Deploy Direct Grants contract and subgraph to all supported chains 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2149]
**User Story:**
As a Program Manager
I want to be able to set up a Direct Grants round 
so that I can run a Direct Grants round on Grants Stack

[TBD] **Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**
* [Direct Grants Deployment Plan](https://www.notion.so/gitcoin/Direct-Grants-Deployment-Plan-fbba62460dc84e9c88d3ab24ab82b076?pvs=4)

**Tech Details:**

**Open Questions:**
* Which chains are in scope for this deployment? 

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by meglister** [comment]
moving to Live -- was done by allo team
