### ISSUE TITLE
[MRC] Explorer: stuck switching from mainnet to OP

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2172]
**Overview**
Summary: To reproduce, add projects from mainnet to cart and 1 from op. Connect MM wallet to ethereum. Start checkout. Submit 1 tx successfully (0x941cbf40ceff4a722989a19e888cdf45b87b309f988f3588c944777835de88a6). Notice that UI does not proceed to check out on Optimism.

![megbug](https://github.com/gitcoinco/grants-stack/assets/26017180/cfb89e18-6911-45bb-a00d-7f49490e81d0)

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by vacekj** [comment]
Env vars were missing in prod on fleek, added them, please recheck in about 5 minutes with a hard refresh @michellema1208
