### ISSUE TITLE
Bug: Explorer Apply Now page is crashing

### ISSUE THREAD

**Issue by bhargavaparoksham** [gitcoinco/grants-stack#2178]
**Overview**
Apply now page on Explorer is crashing. Link: https://explorer.gitcoin.co/#/apply-now

**Screenshots**
<img width="1430" alt="Screenshot 2023-08-14 at 6 29 22 PM" src="https://github.com/gitcoinco/grants-stack/assets/22616592/d286698f-49c2-4b1c-aa7c-b3263c69792e">

**Comment by vacekj** [comment]
This was fixed in bugfixes yesterday.
