### ISSUE TITLE
[Epic] Josef's Explorer Voyage Ideas 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2186]
### Overview (updated 8/28/23) 

**Top 3 Priorities**
1. Matching Estimates ([milestone w/ tickets](https://github.com/gitcoinco/grants-stack/milestone/76)) 
2. Improve performance, both actual and perceived -> https://github.com/gitcoinco/grants-stack/issues/2193 
3. Explorer cleanup + branding update/refresh: 
> a. Only funded rounds appear on Explorer Homepage -> https://github.com/gitcoinco/grants-stack/issues/2194
> b. Branding update and overall refresh -> https://github.com/gitcoinco/grants-stack/issues/2195

**Bonus** 
5. Adding round banner images in Manager setup experience -> Explorer homepage
6. Sorting options to sort projects on the round page: https://github.com/gitcoinco/grants-stack/issues/2206
7. Share our data with the user, display existing data better https://github.com/gitcoinco/grants-stack/issues/2197
8. Bringing back Collections / social sharing on Explorer? 

--------------
### Archive

Possible quests, sorted by user impact:
- Improve performance, both actual and perceived. https://github.com/gitcoinco/grants-stack/issues/2193
- Landing page overhaul https://github.com/gitcoinco/grants-stack/issues/2194
- Matching Estimates ([milestone w/ tickets](https://github.com/gitcoinco/grants-stack/milestone/76)) 
- Branding update and overall refresh https://github.com/gitcoinco/grants-stack/issues/2195
- Share our data with the user, display existing data better https://github.com/gitcoinco/grants-stack/issues/2197
- Sorting options to sort projects on the round page: https://github.com/gitcoinco/grants-stack/issues/2206

**Comment by vacekj** [comment]
@michellema1208 agree fully with the priorities

**Comment by bard** [comment]
@vacekj would be interesting to list also the technical changes that support the above. I know that `useSWR` is on the table. You also mentioned adopting Vite, is this a good opportunity? Anything else?

**Comment by michellema1208** [comment]
closing this for now - has been moved to roadmap!
