### ISSUE TITLE
Donation flow: Error Checking out with DAI

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2199]
Smart contract says it was not able to calculate gas. I hit proceed anyway. The window said congrats, but tx failed.: [0xa11e6d161ffc49532affc9750ae082dcb04b30c15f8a333924d493a3d2eed533](https://optimistic.etherscan.io/tx/0x29b2785b5c4b1fc630a96fda26a839923ba9144076ab03bebf42ecf69f9a872d)

![image](https://github.com/gitcoinco/grants-stack/assets/88308638/561286c3-c443-4579-8b48-f40f8640425c)

I tried a second time and it wasn't successful in the UI this time. And the transaction also failed. Loom vide here https://www.loom.com/share/930918399201404daa7c9ed491966327?sid=718164c8-323a-476b-989f-5c8bca149b63

**Link:** [Conversation with humberto.besso@protonmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64237)

**Customer:** [humberto.besso@protonmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64ca3edad911b26f22d66e3d/all-conversations)
**Customer ID:** 4ca1e8c1-eac2-474f-a386-663d2a5490fe
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64237) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64245?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64188?view=List

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64174?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64114?view=List

**Comment by vacekj** [comment]
https://dashboard.tenderly.co/tx/optimistic/0xfbe35be7ef353dd33d65c0e9c2d5e38ab6a2875a5da7d8b090c097019b57c79e @gravityblast

**Comment by jesuloluwao** [comment]
Reopening because issue still occurs

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64292?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64240?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64183?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64235?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64241?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64219?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/64247?view=List

**Comment by gravityblast** [comment]
fixed with https://github.com/gitcoinco/grants-stack/pull/2211
