### ISSUE TITLE
sentry: don't throw/send to sentry errors like form validations

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2204]
**Overview**
Review errors sent to sentry, and change code to send to sentry only what we need

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by bard** [comment]
This can be used to filter out uncaught exceptions: https://docs.sentry.io/platforms/javascript/configuration/filtering/
