### ISSUE TITLE
All: Grantee applications are not showing up on Builder/Manager 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2213]
**Overview**
Problem: We're getting some reports that grantees who applied to rounds like OSS and ReFi don't have their applications showing up on Builder, Manager, etc. The round application window ends in 24h so this is high priority 

Affected grantees: 

**The TOR Project**
Builder link: https://builder.gitcoin.co/#/chains/1/registry/0x03506eD3f57892C85DB20C36846e9c808aFe9ef4/projects/684
Transaction link: https://etherscan.io/tx/0x40d650ce0c08bca2aa41603c4d6116960e9dbdf6109c741b6c5d286408c4a9d2 

**ReFi Cape Town**
Builder link: https://builder.gitcoin.co/#/chains/10/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/906
Transaction link: https://optimistic.etherscan.io/tx/0x5949e1ee1fc7066aa89be3986b56da672456674802c2ac9078251bed5224530d  

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by gravityblast** [comment]
@michellema1208 I see they applied to 2 different rounds:

<img width="470" alt="Screenshot 2023-08-17 at 13 31 05" src="https://github.com/gitcoinco/grants-stack/assets/1059/8a384cee-121b-4dbd-87b6-3a01780a082c">
<img width="467" alt="Screenshot 2023-08-17 at 13 31 14" src="https://github.com/gitcoinco/grants-stack/assets/1059/86353c2a-483d-4932-b0a1-47d3879b9a7b">

**Comment by gravityblast** [comment]
> The TOR Project
Builder link: https://builder.gitcoin.co/#/chains/1/registry/0x03506eD3f57892C85DB20C36846e9c808aFe9ef4/projects/684
Transaction link: https://etherscan.io/tx/0x40d650ce0c08bca2aa41603c4d6116960e9dbdf6109c741b6c5d286408c4a9d2

that tx is on mainnet, but the round is on optimism

**Comment by gravityblast** [comment]
https://github.com/gitcoinco/grants-stack/issues/2220

**Comment by gravityblast** [comment]
@michellema1208 

> ReFi Cape Town
Builder link: https://builder.gitcoin.co/#/chains/10/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/906
Transaction link: https://optimistic.etherscan.io/tx/0x5949e1ee1fc7066aa89be3986b56da672456674802c2ac9078251bed5224530d


This transaction is a transaction sent to the ProjectRegistry to update the project, not to apply to a round

**Comment by michellema1208** [comment]
Jon (PGF) confirmed this is no longer an issue
