### ISSUE TITLE
4 applyToRound txs were sent to mainnet while the actual round is on optimism

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2220]
txs on mainnet 

https://etherscan.io/address/0x8de918f0163b2021839a8d84954dd7e8e151326d

<img width="1379" alt="Screenshot 2023-08-17 at 13 42 56" src="https://github.com/gitcoinco/grants-stack/assets/1059/988b5ab8-e34c-49c6-b93c-482d3f6be8cf">

actual round on optimism with the same address

https://optimistic.etherscan.io/address/0x8de918f0163b2021839a8d84954dd7e8e151326d

related issue: https://github.com/gitcoinco/grants-stack/issues/2213

**Comment by meglister** [comment]
Getting more info about these projects to try to replicate their issue

**Comment by meglister** [comment]
`1` 0x56edf679b0c80d528e17c5ffe514dc9a1b254b9c is the payout address for Hildr (grapebaba.eth)
link: https://explorer.gitcoin.co/#/round/10/0x8de918f0163b2021839a8d84954dd7e8e151326d/0x8de918f0163b2021839a8d84954dd7e8e151326d-115 

`2` 0xe3d34dac159f88fd2cd38b1380b998000a9c0880 is the payout address for the Tor Project (🤨 )
link: https://explorer.gitcoin.co/#/round/10/0x8de918f0163b2021839a8d84954dd7e8e151326d/0x8de918f0163b2021839a8d84954dd7e8e151326d-162

**Comment by michellema1208** [comment]
@gravityblast is this something you would still recommend we prioritize investigating?
