### ISSUE TITLE
Explorer: checkout on optimism allows checking out with DAI even if the users's balance is zero

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2222]
**Overview**
Details, details, details

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by meglister** [comment]
@melissa-neira moving to blocked / tagging you for a proposed solution & designs! cc @michellema1208
