### ISSUE TITLE
Explorer: Incorrect error message when user tries to donate without enough DAI

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2226]
On metamask, the error shows as unable to estimate gas whereas the user does not have enough DAI.

Loom video below
https://www.loom.com/share/1990917cd13247c58ec59f9b868b2577?sid=94b14458-7d4d-4f42-83cc-03dfc81f4d78

 > <div dir="ltr">I'm seeing this error in Metamask when donating without sufficient DAI.<div><br></div>
<div>This wallet has no DAI on optimism</div>
<div><br></div>
<div>
<img src="https://gitcoin-1cc7f5744bc1.intercom-attachments-3.com/i/o/809663042/2d514c784d8bf09bdf2d72e5/Screenshot+2023-08-17+at+14.49.06.png?expires=1723812631&amp;signature=e6cb53b44215e0ede4656080fae70ff2960e9cae835f8b93d51cb410f37bb60b" alt="Screenshot 2023-08-17 at 14.49.06.png" width="542" height="237" intercom-upload-id="809663042_2d514c784d8bf09bdf2d72e5"><img src="https://gitcoin-1cc7f5744bc1.intercom-attachments-3.com/i/o/809663050/0b96342dbfb07aed111dd73f/Screenshot+2023-08-17+at+14.48.49.png?expires=1723812631&amp;signature=43cc97f131efc258561dfcb446b1b6811f3d7bf98595a81be08a80e01e12c592" alt="Screenshot 2023-08-17 at 14.48.49.png" width="335" height="542" intercom-upload-id="809663050_0b96342dbfb07aed111dd73f"><br>
</div>
</div>

**Link:** [Conversation with Kevin Olsen](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64340)

**Customer:** [Kevin Olsen](https://app.intercom.com/a/apps/xaafeyri/users/641d85ae51e27a95315eb3b5/all-conversations)
**Customer ID:** a055536f-cfe8-4c2f-93d2-2cae1b8b7a16
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64340) when this issue is closed.

**Comment by michellema1208** [comment]
@gravityblast @meglister is this issue something Grants Stack can fix? I don't think we can change what the error message in Metamask is, right?

**Comment by vacekj** [comment]
fixed by #2662
