### ISSUE TITLE
User's contribution not showing on history page

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2227]
**Overview:** There's a couple instances of user contributions not showing up on their Donation History page, detailed below. 

### User 1 
Moved to: https://github.com/gitcoinco/grants-stack/issues/2257 

### User 2
**Summary:** A user in Intercom is unable to see their tx history for recent donations

**Transaction link:** https://optimistic.etherscan.io/tx/0x4579b734a3bdf3b24f445a923b6d02f11c1776341b78bc482afcf1170be3c0bd

**Donation History page**: https://explorer.gitcoin.co/#/contributors/0x35cd01e0dacc4895a3ace555fb3704d8d053c50f

**Console logs:** 

<img width="1435" alt="Screen Shot 2023-08-23 at 1 31 01 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/e100c99f-07b8-426d-9fbc-1350653678a8">

### User 3
**Summary:** Another user is reporting not seeing their OP transactions. 

**Transaction link:** https://optimistic.etherscan.io/tx/0x8fecff1b4f949f32628a4bdb753f0cc923149c64abaa825f0cab2f28a0016738

**Donation History page**: https://explorer.gitcoin.co/#/contributors/0xdfBecC0b4aEF80b96Da27aB483feb0892472eaC2

**Console logs:** 
<img width="1438" alt="Screen Shot 2023-08-23 at 1 43 14 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/4a6e5e18-34cd-4e99-a0d2-e137fb41c04f">

___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64283) when this issue is closed.

**Comment by meglister** [comment]
Another example reported:

Donation link: https://optimistic.etherscan.io/tx/0x8fecff1b4f949f32628a4bdb753f0cc923149c64abaa825f0cab2f28a0016738

Donation history: https://explorer.gitcoin.co/#/contributors/0xdfBecC0b4aEF80b96Da27aB483feb0892472eaC2

**Comment by jesuloluwao** [comment]
Error from my console 
<img width="638" alt="image" src="https://github.com/gitcoinco/grants-stack/assets/88308638/4ad6f12f-97ce-4bde-9085-04d734464feb">

**Comment by bard** [comment]
The 404 comes from the data not being found for chain 1 and chain 250, wherease it is found for chain 10 and 424.

However, for chain 10, the projects appear to be "Lenster", "JediSwap", and "Via | Cross-chain router": https://indexer-grants-stack.gitcoin.co/data/10/contributors/0xB4C3/a8Ca8f/E617a9/90df8a/d7D830/764216/1cd074.json
