### ISSUE TITLE
Can’t understand 

### ISSUE THREAD

**Issue by niloy9** [gitcoinco/grants-stack#2235]
**Overview**
Details, details, details

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by gravityblast** [comment]
closing this issue since it doesn't seem to describe a problem
