### ISSUE TITLE
Manager: Round csv skips some lines

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2246]
> <div dir="ltr">Hello,<div><br></div><div>There appears to be an issue with the csv download in at least the climate and community rounds and possibly others.&nbsp;</div><div><br></div><div>In Climate the csv skips over ID's 98-116.&nbsp;</div><div><br></div><div>97	0x6c192324d26cb3164cff28903b71314cf1bf8dd0ff10d7e0fa3e5e8568d87cfe<br>117	0x30c554f355fc9af4e0d86f58429e713bcef00d30f59dc73dc3fb44e7fef8d888<br></div><div><br></div><div>In Community the csv skips over ID's 236-287</div><div><br></div><div>235	0x873c64f5c8869a654b52d8307791ce0e48655fa098aeea6da5381278858db5d7<br>288	0xfe59b646759b6cd905908e95f8df2974c9523aa3b7501dfda135eebcaf56e73f<br></div><div><br></div><div>Wrapping up reviews and approvals and this is causing some issues.</div><div><br></div><div>Thank you,</div><div>Jon</div></div>

**Link:** [Conversation with Jon Ruth](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64375)

**Customer:** [Jon Ruth](https://app.intercom.com/a/apps/xaafeyri/users/64c7d99b69cf6c8dd0ed3270/all-conversations)
**Customer ID:** 762cafe3-0b47-4a55-a7a6-d79e0c90894b
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64375) when this issue is closed.

**Comment by jesuloluwao** [comment]
> Adding to this, the csv's I pulled the evening of the 16th at ~7pm est includes these missing entries. Not sure if an update was punished between then and the following morning. It seems like the lists I pulled after the round closed have the error in case it is related to the round closin

**Comment by michellema1208** [comment]
@gravityblast @boudra - do we think that these sorts of errors (Round CSV skipping lines) is due to Indexer reliability? Or is this a UI bug?
