### ISSUE TITLE
[Arbitrum] [GS] Add support for donations and matching pool funds in ETH, DAI, & ARB 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2249]
**User Story:**
As a Program Manager 
I want to use ETH/DAI/ARB for my grant round (both payout of matching pool funds and actual donations in the round) 
So that I can distribute funds and/or give my users different options for tokens 

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
merged into #2255
