### ISSUE TITLE
Error loading grants on Optimism in Builder

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2250]
grantees are complaining that they don't see their projects when they log into builder. I confirmed that is happening 

https://www.loom.com/share/cb518cee3ded4d65806a3794ac100765?sid=c88b8c82-ee24-46aa-a657-35eec032ef20

**Link:** [Conversation with carlos@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64540)

**Customer:** [carlos@gitcoin.co](https://app.intercom.com/a/apps/xaafeyri/users/643847a93df291439c1c701d/all-conversations)
**Customer ID:** a7b91110-3d4b-4307-8f31-14cb37ef7ecf
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64540) when this issue is closed.

**Comment by michellema1208** [comment]
this has been resolved!
