### ISSUE TITLE
chore: Document technical details in Chain Deploy Checklist 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2251]
**Overview**
After the Arbitrum deployment process, document technical details in this Chain Deploy checklist: https://www.notion.so/gitcoin/Chain-Deploy-Checklist-d4ed8c6664f14ac3b2da0f0d9c9a6219?pvs=4 

**Details**
Say more

**Comment by bard** [comment]
Indexer part done at https://www.notion.so/gitcoin/Chain-Deploy-Checklist-d4ed8c6664f14ac3b2da0f0d9c9a6219?pvs=4#f2e6b16da1744971b0fd1a64ad48068e

**Comment by vacekj** [comment]
GS part done
