### ISSUE TITLE
Manager: remove colon from copy on left-hand side starting with "Note: ..." 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2265]
**Overview**
See: 
<img width="1440" alt="Screen Shot 2023-08-25 at 5 32 30 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/512b3ce8-f207-425a-9e47-f0d10ef1f195">

This is on the Application page, part of the Round Creation flow

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by ArslanYM** [comment]
Can i give this a try to understand the codebase?

**Comment by ArslanYM** [comment]
This issue was fixed in #2326

**Comment by vacekj** [comment]
closing as fixed in #2326
