### ISSUE TITLE
Explorer: "go to passport" link in checkout modal returns 404

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2268]
Steps to reproduce:

1. Add project to cart
2. Start to check out with a wallet that does not have a valid passport
3. Notice that this popup appears 
![image](https://github.com/gitcoinco/allo-indexer/assets/72808678/a19fdb6d-9dc1-4e19-a740-e1fcf9445d8a)
4. Click "go to passport"
5. Notice that this page returns a 404: https://explorer.gitcoin.co/#/round/passport/connect

Desired behavior: clicking go to passport brings user to this link: passport.gitcoin.co

**Comment by ArslanYM** [comment]
@meglister Should we just use `<Link/>` instead of `useNavigate()` hook for solving this or we need to do this via the hook.
### Current Code: 
![dd](https://github.com/gitcoinco/grants-stack/assets/104521101/d541f5aa-f2b0-4407-9b76-4fd4b8d9a175)

**Comment by vacekj** [comment]
No reason not to do this via Link.

**Comment by ArslanYM** [comment]
If the desired behavior is just navigating to passport.gitcoin.co , then this should do trick. 
![this](https://github.com/gitcoinco/grants-stack/assets/104521101/1c74c820-fb3e-4393-a7c3-616a654ea92f)


I'll raise a PR if this is okay.
