### ISSUE TITLE
Explorer: update round dropdown menu to showcase upcoming rounds 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2275]
### Overview
We have some upcoming rounds on Grants Stack across new chains (Fantom, Arbitrum, Avalanche, zkSync, Polygon) that we should showcase on Explorer via the dropdown menu we currently have for GG18. Details below! This is a temporary manual solution while we are redesigning the Explorer Homepage. 

i.e. would look something like this: 
![IMG_3155](https://github.com/gitcoinco/grants-stack/assets/26017180/a96f71a6-db95-4945-b18e-588aa5afc6fb)

designs here - [figma](https://www.figma.com/file/4J1WWx7cOd0uUNbI2uA4z0/Explorer-GG18?type=design&node-id=817-26547&mode=design&t=lIzhW2tM3OoEnymj-4)

### Tasks

- [x] Replace round links in the GG18 menu with links to upcoming rounds (use same font / layout), separated by chain (see below for live Fantom and Arbitrum rounds) 
- [x] Update GG18 brand asset to "Active Rounds" asset (coming soon) 

### Links

**Arbitrum** 
- The Gaming Round: https://explorer.gitcoin.co/#/round/42161/0xd0a086c37fbd20c44f3ba2cff69208d1b62f54e3 

- New Protocol Ideas Round: https://explorer.gitcoin.co/#/round/42161/0x8b70206844630d8c0a2a545e92d3c8d46a3ceaad

- Developer Tooling on Nova Round:https://explorer.gitcoin.co/#/round/42161/0x1d16f0eedf8ced25f288056ddcbb653d0f0451ad

- Education, Community Growth & Events Round: https://explorer.gitcoin.co/#/round/42161/0x59d79b22595b17af659ce9b03907615f53742c57

**Fantom**
- Vault Round 1: https://explorer.gitcoin.co/#/round/250/0x8dce7a66e0c310f9f89e847dba83b2344d589161 
 
**Details**
Say more

**Comment by meglister** [comment]
@michellema1208 let's keep the redirect up for now, actually -- I'm wondering if we should wait for the new explorer homepage since we haven't solved for spam yet

**Comment by michellema1208** [comment]
@meglister got it, removed!

**Comment by vacekj** [comment]
@meglister @michellema1208 idea - could we implement some very basic spam filters (round is funded and above 1 eth should suffice) and disable the redirect?
