### ISSUE TITLE
run checks in pre-push hook

### ISSUE THREAD

**Issue by bard** [gitcoinco/grants-stack#2283]
To avoid pushing work to a PR branch and not noticing that PR checks fail, set up lefthook to automatically run before push the same checks that would run in CI: lint, typecheck, tests.

supersedes #2201

**Comment by vacekj** [comment]
@bard do you mind if I take over this ticket to free you up for indexer work?

**Comment by bard** [comment]
@vacekj please do. :pray: Mind the notes in the checklist in the linked PR, especially the bit about doing linting in pre-commit instead of pre-push.
