### ISSUE TITLE
Remove matching funds direct grants round page

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2300]
**Overview**
Details, details, details

**Steps To Reproduce**
1. Go to https://gs-direct-grants-grant-explorer.vercel.app/#/round/10/0x84de8abdd4534812ed3b2ac1f861577075cac8e0
2. Observe "Matching funds available..." under the title of the round

**Expected behavior**
Remove matching funds line. Do not replace with anything else.

**Screenshots**
<img width="1182" alt="Screenshot 2023-09-06 at 5 42 34 PM" src="https://github.com/gitcoinco/grants-stack/assets/72808678/7f44058c-191c-4169-8a35-2e8131726a6d">

**Comment by vacekj** [comment]
completed.
