### ISSUE TITLE
Remove donation option from direct grants in explorer

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2301]
**Overview**
Currently direct grants project pages display funding stats and the opportunity to add to cart. These are not applicable to direct grants.

**Steps To Reproduce**
1. Go to https://gs-direct-grants-grant-explorer.vercel.app/#/round/10/0x84de8abdd4534812ed3b2ac1f861577075cac8e0/0x84de8abdd4534812ed3b2ac1f861577075cac8e0-0
2. Observe funding stats + add to cart

**Expected behavior**
Remove both of those components (funding stats + add to cart button.) Do not replace with anything else. 

**Screenshots**
<img width="1669" alt="Screenshot 2023-09-06 at 5 43 30 PM" src="https://github.com/gitcoinco/grants-stack/assets/72808678/cd65e5f0-436a-449a-9576-91f30dc7eb7c">

**Comment by vacekj** [comment]
fixed.
