### ISSUE TITLE
Manager: make donations from users with Passport scores 10 or higher eligible for matching 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2304]
**User Story:**
As a Round Manager of the Fantom round 
I want to count donations with Passport scores 17 or higher towards matching 
So that I reduce Passport friction for my supporters 

**Acceptance Criteria**
GIVEN that a user has a Passport score of 17 or higher 
WHEN the user makes a donation 
THEN it is recorded that that donation is eligible for matching 

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by meglister** [comment]
I wonder if this is easier to do manually (eg - pull all passport scores and manipulate the CSV upload) vs in the indexer?

**Comment by michellema1208** [comment]
@meglister ooh that's a good point since it's just this round! Can you share more how you were thinking about doing this? 

Would it just be downloading the Fantom's round CSV file, and manually updating the `success` column boolean to be `TRUE` for any donation that had a `rawScore` value >= 17? And then reupload revised results? 

I haven't done this before, so just want to validate the manual path! Very down to help drive this if so

**Comment by meglister** [comment]
@michellema1208 , yes that's exactly it! Believe we should be able to query the Passport API to pull the individual scores and then use that data to change coefficients where necessary.

Would love to get a gut check from @gravityblast if this sounds feasible!

**Comment by gravityblast** [comment]
@michellema1208 @meglister 
yes the easiest way to do it without updates from engineering would be:

* download the CSV
* update the coefficient column to 1 even where the score is lower than 20 but the amount is higher than the minimum amount
* upload the file and finale the round

**Comment by michellema1208** [comment]
@meglister closing this ticket as it looks like Fantom team has already finalized results - let me know if we need to reopen this!
