### ISSUE TITLE
[Avalanche] [GS] All: Add Avalanche Mainnet and testnet as a network on Grants Stack 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2308]
**User Story:**
As a Grants Stack user  
I want to be able to use Grants Stack on Avalanche  
So that I can run a round on Avalanche  

**Acceptance Criteria**
GIVEN that I am on Grants Stack (Builder / Manager / Explorer) 
WHEN I click on the network selection toggle 
THEN I see that Avalanche is a supported network 

GIVEN that I am on Manager
WHEN I am setting up a round 
THEN I see payout token options include ETH / DAI / AVAX

GIVEN that I am on Explorer 
WHEN I am checking out projects in a round on Avalanche 
THEN I can set my donations on Avalanche to be in ETH / DAI / AVAX

**Product & Design Links:**

**Tech Details:**
* Allo v1 contracts: https://github.com/allo-protocol/allo-contracts/blob/main/docs/CHAINS.md 
* Tokens to be supported: AVAX, DAI, wETH
* Add support for Avalanche Mainnet & testnet

**Open Questions:**
* 

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
@gitcoinco/grantsstack-product AVAX can be supported as a payout token, but not as a donation token (not even Wrapped AVAX) since it lacks permit support.

**Comment by gravityblast** [comment]
@vacekj @michellema1208 I guess instead of ETH we meant the native token right?

**Comment by michellema1208** [comment]
@gravityblast are we able to support wETH on AVAX?

**Comment by gravityblast** [comment]
@michellema1208 it looks like weth on avalanche doesn't support permit so we can't right now https://snowtrace.io/address/0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab#code /cc @vacekj

**Comment by vacekj** [comment]
@michellema1208 @gravityblast that's correct. In the future, we might want investigate moving to Permit2 by uniswap to alleviate some of those issues.
