### ISSUE TITLE
[zkSync] Indexer: Add support for zkSync Mainnet and testnet 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2311]
**User Story:**
As a Grants Stack user  
I want to be able to use Grants Stack on zkSync 
So that I can run a round on zkSync  

**Acceptance Criteria**
GIVEN that I have made a donation in tokens supported on zkSync
WHEN I check pages that pull data from the Indexer* 
THEN I see accurate data being displayed relative to token prices

*Pages that read data from the Indexer include: 
- Builder: stats tab
- Manager: stats dashboard, matching calculations 
- Explorer: project page, donation history page 

**Product & Design Links:**

**Tech Details:**
* Chain Deploy Checklist: https://www.notion.so/gitcoin/Chain-Deploy-Checklist-d4ed8c6664f14ac3b2da0f0d9c9a6219
* Allo v1 contracts: https://github.com/allo-protocol/allo-contracts/blob/main/docs/CHAINS.md 
* Allo graph deployments: https://github.com/allo-protocol/graph/tree/main/round
* Donation Voting Tokens on zkSync:
ETH - 0x000000000000000000000000000000000000800A
USDT - 0x493257fD37EDB34451f62EDf8D2a0C418852bA4C
USDC - 0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4
LUSD - 0x503234F203fC7Eb888EEC8513210612a43Cf6115
DAI - 0x4B9eb6c0b6ea15176BBF62841C6B2A8a398cb656
MUTE - 0x0e97C7a0F8B2C9885C8ac9fC6136e829CbC21d42

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by bhargavaparoksham** [comment]
This is done as part of this pr, https://github.com/gitcoinco/grants-stack-indexer/pull/367
