### ISSUE TITLE
review/merge collection feature

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2336]
**Overview**
https://github.com/gitcoinco/grants-stack/pull/1786

**Details**
Say more

**Comment by michellema1208** [comment]
@gravityblast updates from Grooming: 

- For MVP, we want to support multi-round collections -- users should be able to add projects across different rounds to the same collection 
- [Figma for Collections MVP](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=493-4626&mode=design&t=tQUpC2byBCZwzpUf-0)
- When you open up a collection, it opens up a new page with a unique URL

**Comment by michellema1208** [comment]
Closing as archived/outdated
