### ISSUE TITLE
Manager: update round description & requirements to multi-line

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2338]
It's hard to read the Round Description when I enter it in this field because I'm limited to one line
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/ecc0dd51-9eaf-4f42-8aa1-b78e9b76502b)
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/9b7396ef-cbd1-47a0-8a79-74b51c8a2615)

**Link:** [Conversation with umar](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64186)

**Customer:** [umar](https://app.intercom.com/a/apps/xaafeyri/users/64ac0017471c413a5277da76/all-conversations)
**Customer ID:** 94e7cfc1-07b0-47fc-87ec-ddb285053cc8
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64186) when this issue is closed.

**Comment by ArslanYM** [comment]
Can I work on  this?

**Comment by ArslanYM** [comment]
### For the roundInput, the `<Input/>` has been used which itself is a tailwind-styled-component. (package)

![1](https://github.com/gitcoinco/grants-stack/assets/104521101/e5d15124-a5b6-41ff-9aa9-89fef476d75d)

### It looks something like this.

![2](https://github.com/gitcoinco/grants-stack/assets/104521101/a215c027-0fa9-4b7d-8d1e-7e4fef67ad8e)


### To get a multiline input we can change it with a text area  ,  just need confirmation/suggestion on how I should proceed with this.

**Comment by ArslanYM** [comment]
@michellema1208 I have fixed the issue in #2462. Please review
