### ISSUE TITLE
[Question] : Do we need to fill all the env constants for local development.

### ISSUE THREAD

**Issue by ArslanYM** [gitcoinco/grants-stack#2347]
**Overview**
while trying to develop the round-manager package locally , do we have to fill all all the environment variables for it to run. 
I've been trying to setup the project locally (following the [Readme](https://github.com/gitcoinco/grants-stack/blob/main/packages/round-manager/docs/DEV.md) ) ,  and it complies successfully but the webapp breaks. Can't seem to figure this one out.

**Observed  behavior**
 The webapp breaks.
![break](https://github.com/gitcoinco/grants-stack/assets/104521101/b748f205-0527-4b42-ba2a-a8310db0433b)

**Additional context**
Im not sure if its the problem with envs , ive followed the Readme but doesnt seem to work.

**Comment by gravityblast** [comment]
hey @ArslanYM thank you for contributing! I know @vacekj worked on validating the required env vars so maybe he can help, we might just need to wait for those changes, wdyt @vacekj ?

**Comment by ArslanYM** [comment]
@gravityblast Thanks, Sure thing.

**Comment by vacekj** [comment]
Env var validation is already part of main. If you rebase on latest main tip, it should tell you which env vars are missing during build. In this case, it's the projectId for wallet connect that's missing, in wagmi.ts

**Comment by ArslanYM** [comment]
> Env var validation is already part of main. If you rebase on latest main tip, it should tell you which env vars are missing during build. In this case, it's the projectId for wallet connect that's missing, in wagmi.ts

Do we need to fill up all env vars to get started with it locally ?

**Comment by vacekj** [comment]
@ArslanYM Yes, you need to fill in all of them to run the program. Some are optional, such as datadog, but the build system still requires that you fill them in, so just put in something random.

**Comment by ArslanYM** [comment]
> @ArslanYM Yes, you need to fill in all of them to run the program. Some are optional, such as datadog, but the build system still requires that you fill them in, so just put in something random.

Should we add a note in the [DEV.md](https://github.com/gitcoinco/grants-stack/blob/main/packages/round-manager/docs/DEV.md) file about the setting up the env variables? It's pretty confusing when you follow the steps in the guide and still cant run the app locally.

**Comment by vacekj** [comment]
Yes, plan on updating all the READMEs to reflect the current situation.

**Comment by ArslanYM** [comment]
> Yes, plan on updating all the READMEs to reflect the current situation.

Okay,  I can start working on it after I get some confirmation from the team about the env vars.
