### ISSUE TITLE
Grant Explorer Cleanup

### ISSUE THREAD

**Issue by vacekj** [gitcoinco/grants-stack#2348]
This is a ticket to clear out remaining superfluous complexity and debt in Explorer, to prepare the codebase for further enhancements and new features.

- [ ] #2353
- [ ] #2354
- [ ] #2355
- [ ] #2356
- [ ] #2357
- [ ] #2358
- [ ] #2359
- [x] https://github.com/gitcoinco/grants-stack/issues/2202

**Comment by michellema1208** [comment]
thank you so much for putting this together, Josef! + @gravityblast to take a look as well!

**Comment by gravityblast** [comment]
we should split each point to a different ticket. each one needs different types of review and test, some of those are super quick to do and the more we can ship the better.

**Comment by michellema1208** [comment]
I can help with that this afternoon, thanks Andrea!

**Comment by vacekj** [comment]
@michellema1208 I've grouped the items into tickets, I'll create them tomorrow.
