### ISSUE TITLE
[Arbitrum] Explorer: donation data not showing up on Donation History page for Arbitrum donations

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2361]
From @YukiPL on 9/30/23: 

### Use Case 1: Missing donations on Donation History page for Arbitrum donations 
I have another user who has donated but not showing. Below are the details:
https://explorer.gitcoin.co/#/contributors/0xda89f7c5e41d4d8899afcb2af94cd29ee89eaca9

<img width="1437" alt="Screen Shot 2023-10-02 at 8 27 21 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/308b48db-97bb-4121-b4a9-e015c6214bc7">

Tx:
https://arbiscan.io/tx/0x70e0853f5f4f958ca69f57e789e90ac43f31242dc3c0e407a8d3f2bbba3bff94
Can someone have a look?
Thanks

### Use Case 2: Missing USDC donations on Arbitrum 
I have a grantee stated that he has received 52 donations, but it only shows 37 in his grant's page. I have a quick look and realise USDC donations are not showing in the History page of the contributors. 

Here are some of the details: 
grant: https://explorer.gitcoin.co/#/round/42161/0x1d16f0eedf8ced25f288056ddcbb653d0f0451ad/0x1d16f0eedf8ced25f288056ddcbb653d0f0451ad-23

<img width="1438" alt="Screen Shot 2023-10-02 at 8 27 08 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/7e311e12-ca4c-46ff-afa0-18876dd5f216">

grant's wallet: 
0xE5F426fE1536b04Bd4aF8C7c405564C5B80F723C

One of the missing donations:
https://arbiscan.io/tx/0x2f5285d4b612d3096d4c534b3c3b2541a7b6389fe6569cc0be2a2512010ed998

https://explorer.gitcoin.co/#/contributors/0x6f625ca653fcb4cfa2424cbe958aef8c6690c717
<img width="1440" alt="Screen Shot 2023-10-02 at 8 26 43 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/b7a3c948-1ef3-4159-84ae-3b38eb314730">

Thanks

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/65345?view=List

**Comment by michellema1208** [comment]
this has now been fixed!

**Comment by michellema1208** [comment]
### Archives
**Overview**
Summary: Donation data for rounds on Arbitrum is not showing up throughout Explorer - it's missing on project pages and Donation History pages. 

Successful transaction: https://arbiscan.io/tx/0x81491068445fa04db1a0402a6eaef3eb749a913dd389216c27b292ec7aa7ead4 
Donation History page which is not showing recent Arbitrum donations: https://explorer.gitcoin.co/#/contributors/0x37e5e6eb36467F98392ebBb35F110FbB8238e6D3 

<img width="1439" alt="Screen Shot 2023-09-19 at 4 29 13 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/ca4a3be2-39d1-49ba-9eb3-3d2f59812cc8">

Data is also missing from all rounds on Arbitrum currently. See: 

<img width="1416" alt="Screen Shot 2023-09-19 at 4 35 27 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/092aa2a2-f8bb-44d6-bb53-e0929e9b6e77">

- Gaming Round: https://explorer.gitcoin.co/#/round/42161/0xd0a086c37fbd20c44f3ba2cff69208d1b62f54e3 
- The New Protocol Ideas Round: https://explorer.gitcoin.co/#/round/42161/0x8b70206844630d8c0a2a545e92d3c8d46a3ceaad 
- Developer Tooling on Nova: https://explorer.gitcoin.co/#/round/42161/0x1d16f0eedf8ced25f288056ddcbb653d0f0451ad 
- The Education, Community Growth, and Events Round: https://explorer.gitcoin.co/#/round/42161/0x59d79b22595b17af659ce9b03907615f53742c57 

**Steps To Reproduce**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by michellema1208** [comment]
confirming this is fixed - closing again
