### ISSUE TITLE
Manager: restrict user from finalizing round results if contract is not funded 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2371]
**User Story:**
As a Round Manager 
I want to know that I must fully fund my contract before finalizing my results
So that I don't finalize my results and receive an error in the process 

**Acceptance Criteria**
GIVEN that I am on the Round Results tab 
WHEN I look at the top of page 
THEN I see copy that says "Finalize your round results here. Doing so will allow you to fund your grantees. Please make sure to fully fund the round contract on the Fund Contract tab before finalizing results. 

GIVEN that I have not fully funded my contract yet 
WHEN I look at the bottom of the Round Results tab 
THEN I see the Finalize Results button is disabled 

GIVEN that I **_have_** fully funded my contract 
WHEN I look at the bottom of the Round Results tab 
THEN I see the Finalize Results button is enabled 

**Product & Design Links:**
Related to: https://github.com/gitcoinco/grants-stack/issues/2037

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
hey @boudra ! Are you still working on this ticket by chance? Asking mostly bc some partners finalizing their rounds have started to run into this issue, so could be a huge help to get this added to UI :) 

No stress if you're not anymore though - I can just take you off / move this back to TODO!

**Comment by boudra** [comment]
I am going to take myself off this ticket since i won't be able to get to it this week as i have a lot of work to do on the indexer, I submitted a draft PR that someone can continue working on, I had started a small refactor that ended up being touching too many parts of the code so I would suggest just implemented the check and revert any refactoring.
