### ISSUE TITLE
[Explorer Homepage] Explorer: Add sort/filtering functionality to Rounds tab 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2378]
**User Story:**
As a donor 
I want to easily find rounds on Grants Stack 
So that I can easily find projects to support 

**Acceptance Criteria** 
GIVEN that I am on the "Rounds" tab 
WHEN I click on "Sort by" 
THEN I see sorting options that include the following: 

- Newest to Oldest (based on round creation date) 
- Oldest to Newest (based on round creation date) 
- Round End Date - Earliest to Latest (based on round end date) 
- Round End Date - Latest to Earliest (based on round end date) 
- Matching funds available - High to Low (based on matching funds available) 
- Matching funds available - Low to High (based on matching funds available) 

GIVEN that I am on the "Rounds" tab 
WHEN I click on "Filter" 
THEN I see filtering options that include the following: 

- Filter by chain (all supported chains) 
- Filter by grant round type (QF or Direct Grants) 
- Filter by status (taking applications, active, finished) 

GIVEN that I select two or more filters in the same category 
WHEN I look at the page 
THEN I see the toggle and section name says "Multiple" 
AND the results are a union of both filters 

GIVEN that I select two or more filters in different categories 
WHEN I look at the page 
THEN I see the toggle and section name says "Multiple" 
AND the results are an intersection of filters in different categories 

GIVEN that I want to remove a filter 
WHEN I click on the applied filter 
THEN it removes the filter 

**Product & Design Links:**
- [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-11219&mode=design&t=DVqmgnYkbAHatvGR-0)

**Tech Details:**

**Open Questions:**
* Are the sort by contributor and project options high impact? If not, should we scope out for now? 
* > A (h/t @melissa-neira): In early donation browsing research, users mentioned wanting a starting point in their browsing journey. a lot of users mentioned wanting to see which projects had the most contributors and which had the most funding in order to vet a project's legitimacy

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
@melissa-neira curious for your thoughts on the above open question!

**Comment by melissa-neira** [comment]
@michellema1208 I would say they are high-impact for these reasons: in early donation browsing research, users mentioned wanting a starting point in their browsing journey. a lot of users mentioned wanting to see which projects had the most contributors and which had the most funding in order to vet a project's legitimacy. I think the same logic could apply to rounds, but I defer that decision to you!

**Comment by carlbarrdahl** [comment]
> * Contributor count - High to Low (# of donors in the round)
> * Contributor count - Low to High (# of donors in the round)
> * Project count - High to Low (# of projects in the round)
> * Project count - Low to High (# of projects in the round)

These are currently not possible. I've created to issues in the graph repo:
- https://github.com/allo-protocol/graph/issues/31
- https://github.com/allo-protocol/graph/issues/32

**Comment by michellema1208** [comment]
@carlbarrdahl - thank you for flagging! Shared on Discord, but will reshare here - let's go ahead and scope these sorts out for MVP. I'll update the ticket Acceptance Criteria - thank you so much!
