### ISSUE TITLE
Explorer: add a stats section to the Explorer Homepage

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2381]
**User Story:**
As a donor 
I want to have a delightful experience browsing Explorer 
So that I stay and fund more projects and rounds 

**Acceptance Criteria**
GIVEN that I'm on the Explorer Homepage 
WHEN I look at the top of the page 
THEN I see stats about Explorer that includes: 

- Total # of Donations 
- Total # of Projects that have received $$ 
- Total amount of funding distributed (both direct donations and matching funds) 

**Product & Design Links:**

**Tech Details:**
* This data is NOT live (pull data manually) - but could be animated, like impact.gitcoin.co 

**Open Questions:**
* @gravityblast - two questions for you 
> 1. What is your recommendation would be for often we update the above stats? 
> 2. Is all of the data above feasible to pull? 

A: We will need to hard code this data, but we could animate to increment upwards like impact.gitcoin.co 

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
@gravityblast have a few open questions for you in the ticket above!

**Comment by bard** [comment]
To animate the value: https://www.npmjs.com/search?q=hook%20animate%20value

**Comment by michellema1208** [comment]
@gravityblast I would actually recommend us only show Grants Stack data, not cGrants data, because it should be the $$ that have gone through Grants Stack. wdyt @gravityblast @meglister ?
