### ISSUE TITLE
Explorer: update branding and page layout 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2382]
**User Story:**
As a donor 
I want to have a delightful experience browsing Explorer 
So that I stay and fund more projects and rounds 

**Acceptance Criteria**
GIVEN that I am on the Explorer Homepage 
WHEN I look at the page 
THEN I see updated branding on the page 
AND I see a Home tab which displays rounds categorized by groups 
AND an "Explore Rounds" tab which displays all rounds with sort/filter functionality 

**Product & Design Links:**
* [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=300-14464&mode=design&t=os8gMWwBouzyFg6y-0)
* [Sample staging environment to see existing homepage](https://explorer-staging-git-bug-2394-grants-stack.vercel.app/#/)

**Tech Details:**
* From @gravityblast: for the round groupings with different card sizes, we can build those basic components as a part of this ticket

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by carlbarrdahl** [comment]
As mentioned in the call, it would make sense to create a layout component that contains all the shared parts between the different routes.

Right now there are some duplications in these routes, for example, this code to render the navbar and the footer is in each of these files.
```tsx
<Navbar />
...
 <div className="relative top-16 lg:mx-20 h-screen px-4 py-7"> <-- This is different in some of the pages
    <main>

...
<div className="my-11">
  <Footer />
</div>
```

We can create a shared layout component that renders the Navbar, Footer, padding, max-width, etc. This way we only need to make adjustments in one file and ensure consistency across pages.
