### ISSUE TITLE
[spike] Research matching calculations for a proportional matching system with Passport

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2387]
**Overview:** We are exploring ways to engage with Passport in GG19 that reduce donor friction by introducing the following sliding scale matching system: 

**_Passport score framework:_** 

- 0-15: 0% Match 
- 15-25: 50-100% Match 

**Open Questions** 
* What changes are needed at the matching calculator level to support a proportional matching system? 
* How would we calculate matching estimates (before the round is over/finalized) with the proportional matching system in mind? 
* How might proportional matching affect other factors in a round, like matching cap, round saturation, etc., if at all? 

**Additional Links**

- [Original Discord thread](https://discord.com/channels/562828676480237578/1154140527860658250/1154140527860658250)
- [Product Requirement Doc](https://www.notion.so/gitcoin/PRD-Passport-donation-flow-v2-4082015ba2a64bfa9c341a7be042bc1a?pvs=4 ) 
- [Data Dashboard](https://gg18sybil.streamlit.app/)

**Comment by michellema1208** [comment]
@gravityblast would love for you to take a look at this spike ticket, let me know if it makes sense!

**Comment by gravityblast** [comment]
we need to check if we have all the data from passport including scores lower than 20
