### ISSUE TITLE
Builder: add WalletConnect v2 support 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2392]
**Overview**
**Context**: Wallet connect v2 is now supported thru lit protocol! https://spark.litprotocol.com/walletconnect-v2-with-lit-protocol/ 
A lot of our users have asked about connecting to Builder with WalletConnect, so this would be a big help. 

**Details**
Say more

**Comment by gravityblast** [comment]
one important thing for the engineering part, we need to be sure we can pass the current web3 provider, or send them a PR to support it like we do for Builder
