### ISSUE TITLE
Manager: page layout is not responsive on Fund Grantees tab > Paid Grantees

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2398]
**Overview**
This is what the page looks like when I navigate to "Paid Grantees" on Fund Grantees tab. 

Try with: https://manager.gitcoin.co/#/round/0xfaf72df9d5384bdb0e56901bf770c27d28af084d 

<img width="1439" alt="Screen Shot 2023-09-27 at 3 46 17 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/0e4caf25-9e98-4ac5-aa48-f6dafc6902bb">

**Steps To Reproduce**
1. Go to https://manager.gitcoin.co/#/round/0xfaf72df9d5384bdb0e56901bf770c27d28af084d 
2. Click on Fund Grantees tab 
3. Go to Paid Grantees 
4. See error in page layout 

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by jesuloluwao** [comment]
Hi @vacekj I just wanted to highlight that this layout issue is not limited to the Fund Grantees tab https://www.loom.com/share/a84bab7069614da0891a0cdddd072a9e?sid=3855ac2d-972d-4930-a098-e1737b2e8645

https://app.intercom.com/a/inbox/xaafeyri/inbox/conversation/68885?view=List
