### ISSUE TITLE
[spike] Display live matching estimates in column on Donation History page

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2401]
**Background** 
We are exploring ways to engage with Passport in GG19 that reduce donor friction. One of the ways that we can do this is via a proportional matching system: the match a donor receives is proportional to the Passport score that they have, i.e. if the score threshold is 20, a Passport score of 15/20 yields a 75% match, as opposed to a 0% match in the current system. **The final proportional matching alogrithm is _not_ finalized yet, and subject to change based on conversations with @gravityblast @michellema1208 and the Passport team**. 

One of the ways that we are planning to expose new proportional matching data to the end user is via a Passport widget on the Explorer nav bar, as well as adding matching estimates to the Donation History page -- those matching estimates would fluctuate depending on: 

1. The nature of QF, and how many donations the project donated to receives over the course of the round 
2. Your current matching power based on the updated matching algorithm

For more info on the full user flow, see this [Miro](https://miro.com/app/board/uXjVMoa_C3U=/?share_link_id=125960946256). 

**Open Questions**: 
- What is the most efficient way to calculate live matching estimates throughout the round? **Note**: This would only apply for donations in active rounds, not past rounds. 
- What is the feasibility of being able to pull live matching data on the Donation History page? Is there significant impact on the Indexer that we should plan for? Average views/users on the Donation History page? 
- Will additional changes need to be made to the matching calculator to support this use case? See https://github.com/gitcoinco/grants-stack/issues/2387
- Will additional changes need to be made to matching estimates on the Cart Checkout page to support proportional matching? See https://github.com/gitcoinco/allo-indexer/issues/307

**NOT in scope:** 
* How to display matching estimates on DH page for past rounds that have _not_ been finalized yet 
* How to display matching estimates on DH page for past rounds that _have_ been finalized 

**Additional Links**

- [Original Discord thread](https://discord.com/channels/562828676480237578/1154140527860658250/1154140527860658250)
- [Product Requirement Doc](https://www.notion.so/gitcoin/PRD-Passport-donation-flow-v2-4082015ba2a64bfa9c341a7be042bc1a?pvs=4 )

**Comment by gravityblast** [comment]
during the spike we can explorer what @bard suggested using storybooks
