### ISSUE TITLE
document first-time setup

### ISSUE THREAD

**Issue by bard** [gitcoinco/grants-stack#2410]
**Overview**

It is currently not straightforward for external contributors to clone the repository and launch the application(s). This is mostly due to the applications depending on API keys which, however free, are tied to invididual developers' accounts, and thus cannot be provided as part of the repository and need to be requested by developers from third-party services.

**Details**

There should be a section in the README or a separate document listing these required API keys and, at minimum, linking to pages where the developer can get them from, e.g.:

>   - `REACT_APP_ALCHEMY_ID=` - sign up to the free plan on alchemy.com and request an API key
>   - `REACT_APP_INFURA_ID=` - sign up to the free plan on infura.io and request an API key
> ...

**Challenges and  unknowns**

It is not clear whether certain keys _can_ at all be available to external contributors, e.g. `REACT_APP_SUBGRAPH_ARBITRUM_API`. If not, this might be a blocker for external contributions.

**Comment by ArslanYM** [comment]
> **Overview**
> 
> It is currently not straightforward for external contributors to clone the repository and launch the application(s). This is mostly due to the applications depending on API keys which, however free, are tied to invididual developers' accounts, and thus cannot be provided as part of the repository and need to be requested by developers from third-party services.
> 
> **Details**
> 
> There should be a section in the README or a separate document listing these required API keys and, at minimum, linking to pages where the developer can get them from, e.g.:
> 
> > * `REACT_APP_ALCHEMY_ID=` - sign up to the free plan on alchemy.com and request an API key
> > * `REACT_APP_INFURA_ID=` - sign up to the free plan on infura.io and request an API key
> >   ...
> 
> **Challenges and unknowns**
> 
> It is not clear whether certain keys _can_ at all be available to external contributors, e.g. `REACT_APP_SUBGRAPH_ARBITRUM_API`. If not, this might be a blocker for external contributions.

This issue was solved after (https://github.com/gitcoinco/grants-stack/pull/2443) , If there is still a need for a proper first time setup guide, Can I work on a video tutorial or blog that documents the whole process of running the project locally?

**Comment by bard** [comment]
> This issue was solved after (#2443) , If there is still a need for a proper first time setup guide, Can I work on a video tutorial or blog that documents the whole process of running the project locally?

There is a [DEV.md](https://github.com/gitcoinco/grants-stack/blob/main/docs/DEV.md) document that was also recently updated, could you have a look at it and see if it's missing something, based on your direct experience of getting the project running?

You're welcome to also blog about it of course. :) I'd advise against videos because setup processes can change, and when they do, it's easy to update a written tutorial than a recorded one.

**Comment by ArslanYM** [comment]
> > This issue was solved after (#2443) , If there is still a need for a proper first time setup guide, Can I work on a video tutorial or blog that documents the whole process of running the project locally?
> 
> There is a [DEV.md](https://github.com/gitcoinco/grants-stack/blob/main/docs/DEV.md) document that was also recently updated, could you have a look at it and see if it's missing something, based on your direct experience of getting the project running?
> 
> You're welcome to also blog about it of course. :) I'd advise against videos because setup processes can change, and when they do, it's easy to update a written tutorial than a recorded one.

Cool, I will create a blog for first-time-contributors to setup the project locally. The [DEV.md](https://github.com/gitcoinco/grants-stack/blob/main/docs/DEV.md) is perfectly fine as well.
