### ISSUE TITLE
general: Citizens Round team unable to add round operator to round contract

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2417]
**Overview**
Citizens team is trying to add this wallet address (0xCA72c93172BA6EfF168E59e7F17C3C7A8FeA9B62) to the round contract, but is running into an error. They were able to add the same wallet address to the Program contract successfully, but not to the Round contract. 

**Steps To Reproduce**
1. Go to round contract: https://explorer.publicgoods.network/address/0x7492a8c4ED29B1F1559888Bd832fAe5D33E10370?tab=write_contract
2. On write contract tab, use role =  0xec61da14b5abbac5c5fda6f1d57642a264ebd5d0674f35852829746dfb8174a5 and account = 0xCA72c93172BA6EfF168E59e7F17C3C7A8FeA9B62
3. Click write

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by krrisis** [comment]
Full convo here https://discord.com/channels/562828676480237578/1106593326095933512/1158458203495993394

**Comment by krrisis** [comment]
error message 
![image](https://github.com/gitcoinco/grants-stack/assets/6533925/583f0f22-154c-44fa-97d4-4aa93ab35b42)
