### ISSUE TITLE
Explorer: add Passport widget in nav bar 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2433]
**User Story:**
As a donor 
I want to know what my Passport score and donation impact are 
So that I know the impact of my donation 

**Acceptance Criteria**

_**Empty State**_
GIVEN that I don't have a Passport or have a score of zero 
WHEN I look at the nav bar on Explorer 
THEN I see a Passport widget with "No score detected" copy 

GIVEN that I don't have a Passport or have a score of zero
WHEN I click on the widget 
THEN I see copy about no score detected 
AND a CTA to go to Passport

**_Happy Path_**
GIVEN that I have a nonzero Passport score 
WHEN I look at the nav bar on Explorer 
THEN I see a Passport widget with my score 

GIVEN that I have a nonzero Passport score 
WHEN I click on the widget 
THEN I see more information about my Passport score 
AND my donation impact percentage
AND a CTA to go to Passport

**Product & Design Links:**
* [Figma](here are the updates to the passport widget (https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=719-30288&mode=design&t=HhcD8Go9ILxSVVUZ-4)

* The color of your score and donation impact percentage depends on your score 

Matching framework: 
0-15: 0% Match
15-25: 0-100% Match

Color system: 
> Score of 0-15: Red 
> Score of 15-25: Yellow 
> Score of 25+: Green 

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment]
@bhargavaparoksham I had a chat with @gravityblast  earlier today, and he suggested that we change the sliding scale matching framework to be: 

Scores: 
0-15: 0% Match
15-25: 50-100% Match 

I'll update the ticket above to match this - this should only impact the colors!

**Comment by michellema1208** [comment]
+ @melissa-neira based on the updated sliding scale matching framework in above comment, what do you think the right breakdown for colors should be? I originally had: 

Score of 0-15: Red
Score of 15-18: Yellow
Score of 18-25+: Green

But am wondering if that might be deceptive with users with scores 18-24 that aren't getting 100% match? 

Alternatively, we could show: 
Score of 0-15: Red
Score of 15-25: Yellow
Score of 25+: Green

**Comment by melissa-neira** [comment]
@michellema1208 yep, that sounds right to me!
