### ISSUE TITLE
Explorer: update Explorer logo to Grants Stack logo 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2446]
**User Story:**
As a donor 
I want to know that I am on Grants Stack 
So that I have a coherent donation experience on Grants Stack 

**Acceptance Criteria**
GIVEN that I am on Explorer 
WHEN I look at the nav bar 
THEN I see a Grants Stack logo (not an Explorer logo) 

**Product & Design Links:**
* Logo: https://www.notion.so/gitcoin/Grants-Stack-Logo-Lockup-35c79c34c89a4631993b5b64eddec72d?pvs=4 
* [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=493-1157&mode=design&t=ogwKgqolDeHEQp2n-0) 

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
@melissa-neira can you verify this is still relevant, and if so, what should the final design be? Figma corresponds to what we have right now.

**Comment by melissa-neira** [comment]
@vacekj it doesn't - we want to change the navbar to say grants stack instead of explorer. let's leave this ticket for after gg19 though, so it doesn't change mid round
