### ISSUE TITLE
Manager: Add markdown support in round description for DG

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2452]
**User Story:**
As a Round Manager 
I want to be able to use rich text in my round description 
So that I can represent my round well 

**Acceptance Criteria**
GIVEN that I am writing my round description 
WHEN I use Markdown formatting 
THEN my round description has rich text

**Product & Design Links:**

**Tech Details:**

**Open Questions:**
* Do we want to add this for QF as well? 
* Wondering if just pure Markdown support is enough? Do we need WYSIWIG support? What about a preview of how the round will look like (fwiw, we've gotten request for more previews as well) 

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by marsrobertson** [comment]
I was about to open a new issue but I thought it's a common concern, arrived here from search for "description".

I just want to add new lines. Markdown support even better. I think Markdown support is sufficient, no need to WYSIWIG editor.

<img width="1692" alt="image" src="https://github.com/gitcoinco/grants-stack/assets/44369284/9fb7ef35-b601-4b51-95e7-2bf365eafcff">
