### ISSUE TITLE
Add a markdown file with list of go-to libraries and link it in the PR template

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2468]

**Comment by carlbarrdahl** [comment]
Great initiative!

Here are some of my favorites:
- react query - I prefer it over swr https://tanstack.com/query/latest/docs/react/comparison
- tailwind
- tailwind-variants - https://github.com/nextui-org/tailwind-variants
  - made a utility function https://github.com/nextui-org/tailwind-variants/discussions/112
- clsx - fastr and smaller than classnames https://github.com/lukeed/clsx
  - merge classNames and easy to apply conditional classes

**Comment by vacekj** [comment]
Agree with all the aforementioned ones, adding some favourites of my own:
- Linting and formatting: [BiomeJS (formerly Rome.tools)](https://biomejs.dev/)
