### ISSUE TITLE
Explorer: Add DAI as Donation Token on PGN

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2472]
**Overview**
Add DAI as a Donation token on PGN on Explorer 

Link to DAI contract: https://explorer.publicgoods.network/address/0x6C121674ba6736644A7e73A8741407fE8a5eE5BA

**Tech Details**

- [x] Double check that the DAI token on the [official bridge](https://bridge.publicgoods.network/) is the up-to-date one (see contract above) 
- [ ] Double check DAI support on [Gitcoin PGN Bridge](https://bridge.gitcoin.co/)

**Comment by michellema1208** [comment]
Note from IPM: need to make sure that DAI is supported on PGN bridge in order to test
