### ISSUE TITLE
Explorer: nav bar cleanup 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2476]
**Overview**
Let's cleanup our nav bar on Explorer and make it forward-compatible with the new Explorer Homepage redesign! 

- [ ] Remove PGN Bridge button 
- [ ] Remove sub-nav bar 
- [ ] Remove Active Rounds dropdown 
- [ ] Add "Explore Rounds" button in nav bar -> takes you to Explore Rounds tab on Homepage 

**Product & Design Links**
* [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=4-32469&mode=design&t=c0j1TRMSn9K7vV5T-4)

**Details**
Say more

**Comment by carlbarrdahl** [comment]
Working on this in PR #2474

**Comment by michellema1208** [comment]
closing as done!
