### ISSUE TITLE
Direct Grants rounds not loading on Polygon

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2478]
**Overview**
I am not able to load previously created direct grants rounds on Polygon. Jason investigated here: https://discord.com/channels/562828676480237578/1164618197870334012

Jason's commentary:
found the issue
it's in round.ts in round-manager main

`payoutStrategy {
  id
  strategyName
} `

should be
`payoutStrategy {
  ... on DirectPayout {
    id
    roundId
    strategyName
  }
  ... on MerklePayout {
    id
    roundId
    strategyName
    isReadyForPayout
  }
}`

He also said:
Incorrect:
https://github.com/gitcoinco/grants-stack/blob/1b4245802f7742c4905b3463283536163c952d28/packages/round-manager/src/features/api/round.ts#L309
https://github.com/gitcoinco/grants-stack/blob/1b4245802f7742c4905b3463283536163c952d28/packages/round-manager/src/features/api/round.ts#L202
Correct:
https://github.com/gitcoinco/grants-stack/blob/1b4245802f7742c4905b3463283536163c952d28/packages/round-manager/src/features/api/round.ts#L132 
looks like one got missed
the other ones in the file have been updated

And:
and would also double check the ViewRoundPage.tsx around line 104

**Steps To Reproduce**
1. Go to https://manager.gitcoin.co/#/round/0xb9f3a7d2a67a002127927abb0d982c12f8955d15?debug=true
2. See error

**Comment by gravityblast** [comment]
@bhargavaparoksham this PR should fix it https://github.com/gitcoinco/grants-stack/pull/2477

thank you @codenamejason

**Comment by bhargavaparoksham** [comment]
This has been resolved now. ref: https://discord.com/channels/562828676480237578/1164618197870334012/1168639201131110411
