### ISSUE TITLE
Indexer: add support for USDC on Polygon

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2509]
**User Story:**
As a donor  
I want to see USDC prices accurately reflected on Polygon 
So that I know how much I have or will donated in USDC on Polygon 

**Acceptance Criteria**
GIVEN that I am checking out projects in USDC on Polygon on Explorer 
WHEN I look at the price 
THEN I see that it is the correct price 

GIVEN that I am managing a round on Polygon
WHEN I look at my round 
THEN I see USDC prices accurately reflected wherever it occurs 

**Product & Design Links:**

**Tech Details:**
- USDC Contract on Polygon: https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174?a=0x71c7656ec7ab88b098defb751b7401b5f6d8976f

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by bhargavaparoksham** [comment]
PR: https://github.com/gitcoinco/allo-indexer/pull/334
