### ISSUE TITLE
Review sentry new/old accounts, keys used in prod and staging, and make sure notifications are enabled

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2518]

**Comment by vacekj** [comment]
FIndings: 
- There are two Gitcoin accounts I can see when logging in with my gitcoin gmail: Gitcoin (old) and Gitcoin Protocol
- Gitcoin Protocol contains three projects. GE, RM and Indexer. Builder is missing, also not present in code.

## Alerts config
- Alerts are set up for GE and RM to go off when a new issues is found and it occurs more than 10 times a minute to avoid testing errors and flukes.
- Alerts for indexer are set up for both on-call and andrea-specific

## Keys
- fixed all keys - the values for staging projects on vercel were wrong.

Action items:
- [ ] Set up Sentry for builder - create project on sentry, add code to builder, add env vars to builder and builder-staging on vercel.

**Comment by meglister** [comment]
@gravityblast shoudl we close this?
