### ISSUE TITLE
[spike] Validate feasibility and data availability of the Categories feature

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2534]
**Overview**
We want to validate the feasibility and data availability of the Categories feature, as proposed in [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-11219&mode=design&t=Aryu9KR6zKp3qk8Z-0).

**Details**
Here are the product requirements we're looking to confirm: 
* We can show a preview of 4 projects included in the category 
* When you click on a Category, I can see projects in that category, with up to 50(?) results 

**Open Questions**
* What's the easiest way for us to show a preview of 4 of the projects in the category? Should this be a static image? Or do we know the search results ahead of time and could display 4 random images of projects in the category? 
* How many results should we display per category such that it doesn't affect performance significantly? Up to 50? 
* Will the results of search query for a given category name be deterministic? Or do we expect it to change every time? 

**Designs**
<img width="478" alt="Screen Shot 2023-11-01 at 4 51 43 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/eb8e05cb-a42e-4aed-a6cb-f981a7949325">

<img width="342" alt="Screen Shot 2023-11-01 at 4 52 01 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/7b7ab5b9-6c20-4a93-894a-96107acb1b46">

Link: [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-11219&mode=design&t=Aryu9KR6zKp3qk8Z-0)

**Comment by gravityblast** [comment]
the goal from eng is to have a json configuration for Categories, with a list of categories with something like
```
type Catergory = {
}
```

**Comment by gravityblast** [comment]
> What's the easiest way for us to show a preview of 4 of the projects in the category? Should this be a static image? Or do we know the search results ahead of time and could display 4 random images of projects in the category?

for the MVP of this functionality it would be better to have a static image

**Comment by gravityblast** [comment]
> How many results should we display per category such that it doesn't affect performance significantly? Up to 50?

I think a maximum of 50 is good /cc @bard @boudra

**Comment by bard** [comment]
> the goal from eng is to have a json configuration for Categories, with a list of categories with something like
> 
> ```
> type Catergory = {
>   title: string:
>   applications: Array<{
>     bannerImage: string;
>     ref: string; // unique identifier of an application, with chainId,roundAddress,applicationid /cc @bard 
>   }>
> }
> ```

This looks more like a type for data rather than for configuration. Configuration would rather be:

```
type Category = {
  title: string;
  query: string
}
```

**Comment by bard** [comment]
> > Will the results of search query for a given category name be deterministic? Or do we expect it to change every time?
> 
> it should be deterministic once we have the applications snapshot /cc @bard

Based on what we see on https://gitcoin-search-dev.fly.dev/static/index.html, it is.

**Comment by bard** [comment]
> > How many results should we display per category such that it doesn't affect performance significantly? Up to 50?
> 
> I think a maximum of 50 is good /cc @bard @boudra

I doubt it make a significant difference on performance. More of a product/UI call.
