### ISSUE TITLE
Deploy and Add GIST as voting token for QV experiment

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2555]
Overview: the Gitcoin team is hosting a QV round while in Istanbul to get people exposed to Grants Stack and drive funds for Turkish charities. We are going to allowlist a valueless voting token on Optimism for them to use for this event. 

Chain: OP
Token address: 0x93a5347036f69bc6f37ed2b59cbcdda927719217
Token abbrev: GIST
Logo: unavailable -- can we use a placeholder?

**Comment by vacekj** [comment]
@gitcoinco/grantsstack this token doesn't support permit at all, so it won't be available in MRC. I see there are just 1 transfers and holders, maybe we can help the team redeploy?

**Comment by owocki** [comment]
will tag quaylawn to let him know youd like to redeploy this @vacekj 

in the future, id put ina have a ticket/request for us to be able to add tokens to GS without any code changes.  i have a few diff partners that would like to be able to do QV.

**Comment by vacekj** [comment]
@owocki thank you, I already redeployed this at https://optimistic.etherscan.io/address/0x93a5347036f69bc6f37ed2b59cbcdda927719217, sent Meg the supply and she will coordinate the rest.

We understand that requiring permit functionality is a limiting factor for token support, and we will be investigating supporting Permit2, which would allow to support _any_ ERC-20, no matter its native permit support. 

This would be a major unlock for operator experience, allowing them to add a token by just pasting its address in Manager, and for users too, as I estimate that a lot of them have previously approved the Permit2 contract, which only needs to be done once.

Stay tuned..
