### ISSUE TITLE
Some application links not loading in Explorer

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2556]
**Overview**
I am unable to load application pages in Explorer for previously completed rounds. There is a console error displayed when the page fails to load (attached).

This seems to be impacting particular rounds (where every project in that round fails to load), but it has not been verified for rounds beside this one. I have verified that other rounds on this chain are working as expected.

**Steps To Reproduce**
1. Go to https://explorer.gitcoin.co/#/round/424/0x222EA76664ED77D18d4416d2B2E77937b76f0a35
2. Click on any of the projects listed on that page
3.  Observe that the page fails to load the application data

**Screenshots**
<img width="1699" alt="Screenshot 2023-11-08 at 8 37 25 PM" src="https://github.com/gitcoinco/grants-stack/assets/72808678/51549272-3643-42d1-b3f2-2732bff6ee0f">

**Comment by carlbarrdahl** [comment]
Seems to be working now
![image](https://github.com/gitcoinco/grants-stack/assets/2961337/e4171fa4-f42c-431e-ae27-7dcca768092a)

**Comment by bhargavaparoksham** [comment]
@carlbarrdahl The issue still exists on the project page. The round page is loading fine.
