### ISSUE TITLE
Bug: Cannot verify projects socials via Metamask Mobile 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2561]
**Overview**
Jon (Gitcoin) has been helping ZachXBT, an aspiring GG19 grantee, who is not able to verify project socials via Metamask Mobile. He is trying to apply to a round that requires Twitter, and is unable to apply as a result. See screenshots below: 

![Screenshot_2023-11-09_at_9 28 12_AM](https://github.com/gitcoinco/grants-stack/assets/26017180/4d16f2ca-177e-4161-a60e-633ca460e6b4)

![photo_2023-11-09_09 28 25](https://github.com/gitcoinco/grants-stack/assets/26017180/43384dc3-0d27-45e2-852c-7ca74cb461fe)

![photo_2023-11-09_09 28 22](https://github.com/gitcoinco/grants-stack/assets/26017180/59a475b4-1785-43ae-b7e1-13201142a9b2)

**Steps To Reproduce**
1. Connect to Builder via Metamask mobile
2. Create a project 
3. Attempt to verify project Twitter 

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by vacekj** [comment]
The solution to this is supporting walletconnect v2 in builder.
