### ISSUE TITLE
track events with gtm for homepage, rounds, and projects pages

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2562]
home-collections-card-big
home-collections-card-small
home-category-card
home-donate-now-card-big
home-donate-now-card-small
home-rounds-ending-card

home-rounds-tab
home-projects-tab

TODO:
rounds-page-card
projects-page-card
projects-page-category-card
projects-page-collection-card
projects-page-search-fulltext-card
projects-page-search-semantic-card

**Comment by vacekj** [comment]
Would be great to know what is the purpose of this tracking. Is it for tracking conversions? Are there any use-cases we already have in mind? @gitcoinco/grantsstack
