### ISSUE TITLE
experimental product analytics with posthog

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2563]

**Comment by bard** [comment]
Potential breakdown:

1. sign up to the hosted plan with free tier
2. create a `posthog` branch in `grants-stack`
3. configure Explorer in the `posthog` branch to use posthog
4. play around with the PR deployment
5. evaluate usefulness of data in Posthog
6. if useful enough, pick an option:
    1. keep using hosted plan, or
    2. self-host:
        1. set up an aws ec2 instance
        2. assign a gitcoin.co domain name
        3. ensure docker is set up to start at boot
        4. use posthog-provided docker-compose.yml to bring up the stack
        5. point client to self-hosted instance
7. merge `posthog` branch or discard based on evaluation
