### ISSUE TITLE
Explorer: add partial empty state for project search

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2588]
Follow-up ticket to: https://github.com/gitcoinco/grants-stack/issues/2488 , per conversations with @boudra [here](https://discord.com/channels/562828676480237578/1174027891806322768/1174064873861287946). See past comment [here](https://github.com/gitcoinco/grants-stack/pull/2560#pullrequestreview-1723467800)) for more context as well. 

**User Story:**
As a donor 
I want to know if the project I'm looking for is not there 
So that I don't waste time looking for a non-existent project

**Acceptance Criteria**

GIVEN that I enter keywords that have no fulltext match but some semantic search matches 
WHEN I look at the page 
THEN I see a partial empty state with copy that says "Your search did not match any projects. Try again or feel free to browse through projects similar to your search" 
AND a list of semantic search results 

GIVEN that I enter keywords that have no fulltext or semantic search matches 
WHEN I look at the page 
THEN I see a full empty state with copy that says "Your search did not match any projects. Try again using different keywords." 
AND no results 

**Product & Design Links:**
* [Figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-11219&mode=design&t=X4tN3U0nGAHIKDwt-0)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by carlbarrdahl** [comment]
In case someone starts working on this before the collections PR is merged. Could you base it off of that branch?
