### ISSUE TITLE
Number of projects incorrect on Explore Rounds tab

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2596]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/rounds?orderBy=matchAmount&orderDirection=desc&status=active%2Ctaking_applications

### What happened?

The Open Source Software round has 106 approved applications, but we're displaying a total of 100 applications on the explorer homepage

### What should have happened instead?

It should display 106 projects

### Steps to Reproduce

1. Go to the round page here and observe 106 projects: https://explorer.gitcoin.co/#/round/424/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008
2. Go to round manager and observe 106 approved projects: https://manager.gitcoin.co/#/round/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008?debug=true
3. Observe on the explorer page the total of 100 projects
![Screenshot 2023-11-15 at 9 29 25 AM](https://github.com/gitcoinco/grants-stack/assets/72808678/eed87611-f36f-401b-ac8a-a12e767de66d)
![Screenshot 2023-11-15 at 9 29 18 AM](https://github.com/gitcoinco/grants-stack/assets/72808678/a9fb45a8-5d9b-4965-be24-eca9db975c7a)
![Screenshot 2023-11-15 at 9 29 09 AM](https://github.com/gitcoinco/grants-stack/assets/72808678/aafe0547-ef04-4a6e-b0ec-ed6af8465e31)

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

PGN

**Comment by bhargavaparoksham** [comment]
@meglister This seems to be fixed now. I can see the project the same project count in explorer as in round manager.

**Comment by michellema1208** [comment]
hey @bhargavaparoksham - I'm still seeing the project count on preview card as 100 but then the true project count on the Explorer round page as 107 for OSS, for example, so am going to keep this ticket open / move back to TODO! / cc: @meglister

**Comment by carlbarrdahl** [comment]
Here are the data requests being sent. 

It seems the first one only returns projects with status: 1.

Query from Explore Rounds tab returns 100 projects
```sh
curl 'https://graph-gitcoin-mainnet.hirenodes.io/subgraphs/name/gitcoin/allo' \
-H 'content-type: application/json' \
--data-raw '{"query":"\nquery GetRounds(\n  $first: Int, \n  $orderBy: String,\n  $orderDirection: String,\n  $where: Round_filter,\n  $currentTimestamp: String\n  ) {\n    rounds(first: $first,\n      orderBy: $orderBy,\n      orderDirection: $orderDirection,\n      where: $where\n    ) {\n      id\n      roundMetaPtr {\n        protocol\n        pointer\n      }\n      applicationsStartTime\n      applicationsEndTime\n      roundStartTime\n      roundEndTime\n      matchAmount\n      token\n      payoutStrategy {\n        id\n        strategyName\n      }\n      projects(where:{\n        status: 1\n      }) {\n        id\n      }\n    }\n}\n","variables":{"orderBy":"matchAmount","orderDirection":"desc","where":{"and":[{"or":[{"roundStartTime_lt":"1700225845","roundEndTime_gt":"1700225845","roundEndTime_lt":"1731761845"},{"applicationsStartTime_lte":"1700225845","applicationsEndTime_gte":"1700225845"}]},{}]},"first":100}}' \
| jq ".data.rounds[0].projects" | jq "length"
```

Query from round page returns 124
```sh
curl 'https://graph-gitcoin-mainnet.hirenodes.io/subgraphs/name/gitcoin/allo' \
-H 'content-type: application/json' \
--data-raw '{"query":"\n        query GetRoundById($roundId: String) {\n          rounds(where: {\n            id: $roundId\n          }) {\n            id\n            program {\n              id\n            }\n            roundMetaPtr {\n              protocol\n              pointer\n            }\n            applicationMetaPtr {\n              protocol\n              pointer\n            }\n            applicationsStartTime\n            applicationsEndTime\n            roundStartTime\n            roundEndTime\n            token\n            payoutStrategy {\n              id\n              strategyName\n            }\n            votingStrategy\n            projectsMetaPtr {\n              pointer\n            }\n            projects(\n              first: 1000\n              where:{\n                status: 1\n              }\n            ) {\n              id\n              project\n              status\n              applicationIndex\n              metaPtr {\n                protocol\n                pointer\n              }\n            }\n          }\n        }\n      ","variables":{"roundId":"0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008"}}' \
| jq ".data.rounds[0].projects" | jq "length"
```
