### ISSUE TITLE
Cannot add more than one grant to cart

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2600]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/cart

### What happened?

Adding a grant to cart removes the previously added grant to cart

### What should have happened instead?

Adding a grant to cart keeps all previous grants in the cart

### Steps to Reproduce

1. Go to explorer, add a grant to cart
2. Notice it is added successfully
3. Add another grant to cart
4. Notice it is also added successfully, but the previous grant is removed

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

all

**Comment by michellema1208** [comment]
Closing - fixed with https://github.com/gitcoinco/grants-stack/pull/2601
