### ISSUE TITLE
Unable to edit application end date

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2602]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/round/0x908d56da660654955a3e4bd09e8002372432fb02

### What happened?

On the round settings page, if you try to edit the application end date of a round, you get an error

### What should have happened instead?

You should be allowed to edit the round settings.

### Steps to Reproduce

1. Go to manager
2. Go to round settings
3. Go to round & application settings tab
4. Edit any of the round start/end dates
5. You'll get an error

https://www.loom.com/share/9e638ea9cd7f47fd810a193fbc43e5dd?sid=ef694f5f-b3e9-47fd-b68a-075119414a9d

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Optimism

### Relevant log output

```shell
https://www.loom.com/share/9e638ea9cd7f47fd810a193fbc43e5dd?sid=ef694f5f-b3e9-47fd-b68a-075119414a9d
```

**Comment by jesuloluwao** [comment]
I took a screenshot from the loom here to show the console log 
![Screenshot 2023-11-15 at 4 14 44 PM](https://github.com/gitcoinco/grants-stack/assets/88308638/e639be62-26a0-4012-a9bb-dec1e6b3ba7f)

**Comment by meglister** [comment]
Adding screenshots of the console from another customer who had this error



![Image](https://github.com/gitcoinco/grants-stack/assets/72808678/734c09a3-9680-4ebe-9021-7813ce27ce4a)
![Image](https://github.com/gitcoinco/grants-stack/assets/72808678/8d155312-4ee2-48c4-bdc8-a96a2fefd89f)

**Comment by michellema1208** [comment]
Note from @gravityblast : it was possible to update the round, but it wasn't possible some hours before
