### ISSUE TITLE
Rounds not correctly sorted by matching amount

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2603]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/rounds?orderBy=matchAmount&orderDirection=desc&status=active%2Ctaking_applications

### What happened?

It looks like we are sorting by match amount by currency, but different matching amounts across different currencies are not sorted correctly.

### What should have happened instead?

Matching amounts should be sorted correctly across currencies

### Steps to Reproduce

1. Go to https://explorer.gitcoin.co/#/rounds?orderBy=matchAmount&orderDirection=desc&status=active%2Ctaking_applications
2. Notice that Ethereum Core Infrastructure round has a 200,000 USDC matching pool but is sorted near the bottom of the page

![Screenshot 2023-11-15 at 10 23 02 AM](https://github.com/gitcoinco/grants-stack/assets/72808678/df538d76-df03-40b8-9334-f48915e749c2)

### What browser(s) are you seeing the problem on?

Chrome

**Comment by carlbarrdahl** [comment]
This is because some tokens have different decimals. For example, ETH, DAI, and most tokens have 18 decimals. USDC has 6.

To demonstrate this:
```sh
200000000000 = 200,000 USD
1000000000000000000 = 1 ETH 
```

To be able to display correctly we would need to fetch the token decimals for each of the projects.

@gravityblast does the indexer index the token decimals?

**Comment by michellema1208** [comment]
+ @boudra who may also be able to speak to Carl's indexer question above!

**Comment by boudra** [comment]
we have the match amount in USD in the indexer: https://indexer-production.fly.dev/data/10/rounds.json
but you'd have to load the whole json and filter it in the front end as we haven't built an API to filter yet

**Comment by vacekj** [comment]
temporarily, we can use the `useTokenPrice` hook from `common` that queries redstone finance, and see if we can get this from the indexer using the new graphql api

**Comment by vacekj** [comment]
I'll hold off on this until we have proper support in indexer, so as not to add lots of complexity for a non-critical bug.
