### ISSUE TITLE
Matching Estimates not showing during checkout

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2605]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/cart

### What happened?

Matching Estimates aren't showing up during checkout

### What should have happened instead?

On the checkout page,, we should see the matching estimates

### Steps to Reproduce

1. Add items to your cart
2. Proceed to checkout

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Optimism

**Comment by meglister** [comment]
Screenshot of console errors on cart page -- another CORS error?

![Image](https://github.com/gitcoinco/grants-stack/assets/72808678/544c7047-0185-4f75-afd9-c54f6fbdc66b)

**Comment by vacekj** [comment]
Resolved by updating configuration in CloudFront to allow all headers.
