### ISSUE TITLE
Explorer: add 5 new Collections from Curators

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2620]
**Overview**
Add these 4 Collections that are ready from our selected curators: 

- See this [spreadsheet](https://docs.google.com/spreadsheets/d/16kif9RcFw4YUgZ2g1K1FLm8cSv86Lc-jPuiKk7yG3dk/edit?resourcekey#gid=170267390) for Curator Name, Collection Title, Collection Description, + link out to spreadsheet of projects in their Collection. 

If you have any questions, just ping Michelle! 

- superphiz [figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=1764-26667&mode=design&t=j3xPbvrTYCJPVuUf-4)
- Devansh Mehta [figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=1764-26720&mode=design&t=j3xPbvrTYCJPVuUf-4)
- Ale RaMo [figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=1764-26751&mode=design&t=j3xPbvrTYCJPVuUf-4) 
- CryptoReuMD - [figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=1771-28921&mode=design&t=8pE5n7Wp9qz6Qqde-4)
- Olimpio - [figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=1772-28954&mode=design&t=8pE5n7Wp9qz6Qqde-4)
- Wasabi - [figma](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=1772-28989&mode=design&t=8pE5n7Wp9qz6Qqde-4)

**Details**
Say more

**Comment by michellema1208** [comment]
@bard - @melissa-neira should be able to help with that! Melissa, let me know if you run into any issues, though!

**Comment by melissa-neira** [comment]
@bard the images have been added to the ticket 🤝
