### ISSUE TITLE
Builder: Edited details not included in new application

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/grants-stack#2632]
### What was the URL where the error occurred?

https://builder.gitcoin.co/#/projects

### What happened?

This grant owner made some updates on his project, paid the updates and then applied to the Climate Round, but the changes are not appearing.
This is the only case I have. https://builder.gitcoin.co/#/chains/10/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/817

Updates txid: (Nov-08-2023 03:21:29 PM +UTC) https://optimistic.etherscan.io/tx/0x318199ee8cfcce12506093b3b19c493578b452f16aa5b290e4fd3d1cce005876

Application txid (Nov-08-2023 03:50:03 PM +UTC)
https://optimistic.etherscan.io/tx/0x488fb430818bc4477737f7d6e7b1f52217e4cfa5eb8a61a70f7b00557c6ac7ef

### What should have happened instead?

The new updates should appeared in new application.

### Steps to Reproduce

https://builder.gitcoin.co/#/chains/10/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/817

### What chain(s) did the error occur on?

Optimism

**Comment by michellema1208** [comment]
Closing as addressed
