### ISSUE TITLE
Polygon explorer directed to the wrong site on Donation History page

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/grants-stack#2645]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/contributors/0x80c9ED513350D3a34F0c17aebc4FbE9C05Bbb9D0

### What happened?

When clicking on the 'View Transaction' on the User's history Page, it directs to the wrong URL (https://polygonscan.io/). It should be directing to https://polygonscan.com/.

<img width="1244" alt="Screenshot 2023-11-20 at 08 54 44" src="https://github.com/gitcoinco/grants-stack/assets/92294305/ac84218c-6e55-4dad-ac3b-f7bdb8f09059">

### What should have happened instead?

The click on 'View Transaction' should be directing to https://polygonscan.com/.

### Steps to Reproduce

1. Go to History page
2. Click on 'View Transaction' on any Polygon contribution
3. The click direct to the wrong Polygon explorer

### What browser(s) are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What chain(s) did the error occur on?

Polygon

**Comment by boudra** [comment]
we are pointing to polygonscan.io instead of polygonscan.com

**Comment by YukiPL** [comment]
@boudra but if you click on the View Transaction it return error:


![Image](https://github.com/gitcoinco/grants-stack/assets/92294305/1f864f42-2ceb-4556-84fb-accb0af3decf)
