### ISSUE TITLE
Explorer: Apply badge missing on Round card

### ISSUE THREAD

**Issue by carlbarrdahl** [gitcoinco/grants-stack#2651]
### What was the URL where the error occurred?

https://explorer.gitcoin.co

### What happened?

![image](https://github.com/gitcoinco/grants-stack/assets/2961337/9a27ec28-eb8e-4b33-b9e4-1b8060fe00e8)

### What should have happened instead?

First Round card should show Apply badge

### Steps to Reproduce

.

**Comment by bard** [comment]
Closed in favor of #2751 which contains reproduction.
