### ISSUE TITLE
Evaluate Data Aggregation and Query Efficiency for Explorer Pages

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2664]
## Overview

Right now, our Explorer front-end fetches data from different places:

- Contracts
- IPFS
- Subgraphs
- Indexer
- Search Service

This approach, involving multiple data sources, leads to potential issues in data uniformity and retrieval efficiency.
It also slows down development of new features, especially when integrating new data into the front-end that cannot be readily aggregated from a single source.

## Objective
The primary goal is to shift towards more effective use of our new indexer database,  we can focus on:

1. **Data Completeness Check**: Verify if our new indexer database contains all required data for the following Explorer pages:
   - Project Application Page (https://explorer.gitcoin.co/#/round/424/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008-161)
   - Round Page (https://explorer.gitcoin.co/#/round/424/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008)
   - Rounds Page (https://explorer.gitcoin.co/#/rounds?orderBy=matchAmount&orderDirection=desc&status=active%2Ctaking_applications)

2. **Query Optimization Review**: Evaluate whether the data in our indexer is organized for optimal querying efficiency. This may involve considering additional steps for data denormalization to improve access speed.

## Desired Outcomes

From this analysis, we expect to:
- Understand the extent of data coverage in our new indexer for the specified pages.
- Identify if there's a need to restructure data for enhanced querying efficiency.

## Next Steps
Based on the findings, we will start designing and implementing a new way to fetch data, probably on top of the new data client.

**Comment by vacekj** [comment]
Here are our findings: https://github.com/gitcoinco/grants-stack/blob/evaluate-data-aggregation-for-explorer-pages/docs/DATA.md
@gitcoinco/grantsstack-engineering

**Comment by gravityblast** [comment]
great job @bard @vacekj 

one thing we can remove is the matadata fetching from ipfs. in the project application page (https://explorer.gitcoin.co/#/round/42161/0x3ac78e1ae5086904d53b41c747188216789f59a7/0x3ac78e1ae5086904d53b41c747188216789f59a7-39) we fetch the metadata from ipfs for the round and the application, this can be done in one single query now. 

I also see that we fetch all the application metadata files even if we are checking one single application so we can improve decrease the number of requests as well.

**Comment by gravityblast** [comment]
what's the outcome of the research, do we need any more data in the indexer to be able to display those pages without the subgraph?

**Comment by michellema1208** [comment]
This work is in progress - closing this spike
