### ISSUE TITLE
Grant owner applied with mainnet in PGN round

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/grants-stack#2666]
### What was the URL where the error occurred?

https://builder.gitcoin.co/#/chains/424/rounds/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008

### What happened?

A grant owner was able to execute transaction using mainnet when apply to OSS round, which is deployed using PGN. 

Txid: 
https://etherscan.io/tx/0x2c1fd4d0403d32139fc33c157f3c37d0887966d80a2529b7f8a7ba7883fa6962
https://etherscan.io/tx/0x4330058805bc813a6238b9b53072524d0f56555eee482782e4a6c902a581bcb4

grant: https://builder.gitcoin.co/#/chains/137/registry/0x5C5E2D94b107C7691B08E43169fDe76EAAB6D48b/projects/110

Uploading bandicam 2023-11-21 15-13-07-771.mp4…

### What should have happened instead?

Grant owner should not be allowed to submit tx using other chain if the round is deployed in PGN. 

### Steps to Reproduce

1. Go to https://builder.gitcoin.co/#/chains/424/rounds/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008
2. Change wallet to mainner (a prompt should pop-out asking to switch chain - but in this case no)
3. Proceed with application using mainnet

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

PGN

**Comment by bhargavaparoksham** [comment]
@YukiPL Unable to reproduce the issue, I'm able to see the switch chain pop up when i try to apply from a different chain. Did the user do something else to bypass the popoup?



![Image](https://github.com/gitcoinco/grants-stack/assets/22616592/c181cb68-3748-4382-b5ea-7b6b9781fc4b)



cc: @michellema1208
