### ISSUE TITLE
investigate sentry error: WebAssembly compilation aborted

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2683]
sentry error: 

https://gitcoin-protocol.sentry.io/issues/4390585162/?notification_uuid=72a9b6f5-4260-4e60-8ab0-cb06314c5907&project=4504327111114752&referrer=pagerduty_integration

possibly related to:

https://github.com/rainbow-me/rainbowkit/issues/1374

**Comment by vacekj** [comment]
After investigating the sentry issue, and the rainbowkit issue you linked, nothing stands out to me that would suggest this is an issue on our end. If there is no direct impact on the user, and given that this happened "only" 270 times in the last 30 days, I would file this under a low-priority label.

On another note, something that would help a lot with diagnosing issues in Sentry are the sentry session replays: https://docs.sentry.io/product/session-replay/. let me know if this is something we could enable @gravityblast @gitcoinco/grantsstack-product
