### ISSUE TITLE
[BUG] 'APPLY' button not working in Explorer

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/grants-stack#2698]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/rounds?orderBy=matchAmount&orderDirection=desc&status=active%2Ctaking_applications

### What happened?

When click on the Apply button on round in https://explorer.gitcoin.co/#/rounds?orderBy=matchAmount&orderDirection=desc&status=active%2Ctaking_applications, it does not bring user to apply page. Users are not able to apply. 

User that reached out would like to apply to https://explorer.gitcoin.co/#/round/10/0x3df423b3fe4a3d549a65d8f440b43a8a6f379670

### What should have happened instead?

When click on the Apply button, it should directs user to the Application page. 

### Steps to Reproduce

1. Go to https://explorer.gitcoin.co/#/round/10/0x3df423b3fe4a3d549a65d8f440b43a8a6f379670
2. Click on apply in any round
3. See error

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

NA

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/67735?view=List

**Comment by michellema1208** [comment]
thanks @YukiPL ! As mentioned in standup, I've created a ticket to track adding the application link to Explorer here: https://github.com/gitcoinco/grants-stack/issues/2703 

Will close out this bug ticket!
