### ISSUE TITLE
"Share Profile" button on contributor page copies wrong URL

### ISSUE THREAD

**Issue by flowscience** [gitcoinco/grants-stack#2705]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/contributors/{address}

### What happened?

Clicking the "Share Profile copied the following incorrect URL to my clipboard

https://explorer.gitcoin.co#/contributors/{address}

While the actual page address is https://explorer.gitcoin.co/#/contributors/{address}

![image](https://github.com/gitcoinco/grants-stack/assets/10070465/98d59de8-2ea8-4695-8619-e88b08afe0ca)

### What should have happened instead?

The actual page address is https://explorer.gitcoin.co/#/contributors/{address}

containing a forward slash after the TLD extension.

### Steps to Reproduce

Go to profile page & click "Share Profile"

### What chain(s) did the error occur on?

PGN

**Comment by bard** [comment]
@flowscience thanks for the detailed report!
