### ISSUE TITLE
Builder: Polygon projects not loading

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2746]
### What was the URL where the error occurred?

https://builder.gitcoin.co/#/projects

### What happened?

When I load Builder, I get a message that none of my Polygon projects are loading. See console error logs below: 

<img width="1440" alt="Screen Shot 2023-12-15 at 3 40 33 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/b5dec381-a18d-489e-a3f7-7abb118a8578">

### What should have happened instead?

I should see my Polygon projects

### Steps to Reproduce

1. Go to https://builder.gitcoin.co/#/projects
2. See error that Polygon projects are not loading

### What chain(s) did the error occur on?

Polygon 

### Relevant log output

```shell
Polygon 137 Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32005,\"message\":\"eth_getLogs block range too large, range: 51171338, max: 50000000\"}}", error={"code":-32005}, requestBody="{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x0\",\"toBlock\":\"latest\",\"address\":\"0x5c5e2d94b107c7691b08e43169fde76eaab6d48b\",\"topics\":[\"0x63c92f9505d420bff631cb9df33be952bdc11e2118da36a850b43e6bcc4ce4de\",null,\"0x00000000000000000000000037e5e6eb36467f98392ebbb35f110fbb8238e6d3\"]}],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://polygon-mainnet.infura.io/v3/1e0a90928efe4bb78bb1eeceb8aacc27", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (index.ts:269:28)
    at Logger.throwError (index.ts:281:20)
    at eval (index.ts:341:28)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:1:14)
```

**Comment by vacekj** [comment]
looks like we are requesting too big of a block range for getLogs (this most likely only started happening recently because of the tip of the chain exceeding the limit) and aren't handling this error case. will fix.
