### ISSUE TITLE
USDC donations are failing on zkysync mainnet

### ISSUE THREAD

**Issue by bhargavaparoksham** [gitcoinco/grants-stack#2758]
USDC (https://explorer.zksync.io/address/0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4) donations are failing on zkSync Era. 

Debugging steps:
- [x] check that Permit version is right
- [x] check that permit nonce is right
- [x] check that there are no irregularities about the permit implementation (as is the case for example with USDC on Polygon PoS)
- [x] check that the typed data is correct
- [x] check that the mrc contract address is right

raw tx data for address `0x5f390415dB0f7d4D336095f3Fd266D6B3B616e7A`

<details>
<summary>Details</summary>

0xa710f56a0000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000026000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000f42400000000000000000000000003355df6d4c9c3035724fd0e3914de96a5a83aaf4000000000000000000000000000000000000000000000000000001934c04c000000000000000000000000000000000000000000000000000000000000000001c503e160bb9fe233d51fb962530852b63f6e01eaf64cfa421d9e449ee67e24fcf7054d47196d432c0d85eefad870f12d00f7b3ee83cd42544946f020e63e1947a000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000003355df6d4c9c3035724fd0e3914de96a5a83aaf400000000000000000000000000000000000000000000000000000000000f42400000000000000000000000005f390415db0f7d4d336095f3fd266d6b3b616e7a9a80dc96d5dd60a62bec7d0c379d92896967403311a6486388f371fa222642a4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000fa98c9e0270b925ef112329ea75e971c3b50a52000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000f4240

</details>

Create a minimal reproduction scenario
- [x] use `cast` to see the exact trace and determine the exact error
- [ ] Clone the USDC contract, fork zksync era and test against local - rules out EVM differences.
- [x] Use the [permit example app](https://github.com/vacekj/wagmi-permit/tree/main/example-app) for the simplest possible permit scenario, rule out errors in typed data and signing method.

**Comment by vacekj** [comment]
Minimal repro: https://github.com/vacekj/usdc-permit-test/tree/master

additional info:
the same code works for USDC on optimism (only changing the token address), leading me to believe that there is something different about the specific impl of usdc on Era. furthermore, all Era bridged erc20s share the same impl at `0x9A8De191644140bD874F911359B5D15BB18f8a58`, so the impl itself also shouldn't be an issue (LUSD works with the same impl). The only difference to LUSD is the configuration of the token in the proxy - name, symbol (isn't used in permit), decimals

**Comment by vacekj** [comment]
Pending decision to only integrate native USDC once it's deployed (~March)

**Comment by vacekj** [comment]
closing as wontfix, will only support native usdc
