### ISSUE TITLE
(Community / PGN) Unable to pay out round

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2761]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/round/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008?debug=true

### What happened?

1. finalized the round with COCM results using the manager fork: https://manager-staging-git-pgf-custom-results-grants-stack.vercel.app/#/round/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008
2. switched back to the default manager where the round results were updated correctly
3. Tried to fund grantees but ran into errors (pics/vids below)
4. When we hit payout we confirm the metamask transaction but then are immediately met with a red X

Overview: https://www.loom.com/share/8164693120a5479cbcdff1a459a2477e?sid=82267138-d8d7-4fea-be77-5694b6783f66

Umar was using this wallet: 0x1490bc4a47871629b3bfE9eC1c0c0C3e55df6067
@Ben West 🦋  also tried with at least 3x the needed gas in his wallet: 0x00F16EC63017b2268Bc5513aBaf841B58095104c
@coday.eth | Gitcoin tried too: 0x974BBC9C9b8A1b81e92DF9D1457D2DF98941814E

### What should have happened instead?

Round should be funded

### Steps to Reproduce

1. go to https://manager.gitcoin.co/#/round/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008
2. click fund grantees
3. try to complete payment

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

PGN

**Comment by michellema1208** [comment]
Community Round was paid out - closing this ticket
