### ISSUE TITLE
Manager: Unable to payout DG round in ETH on Base 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2770]
**Summary**
I'm not able to payout a DG round on Base in ETH. When I click on the "Payout" button, I see the following error:

<img width="1438" alt="Screen Shot 2024-01-03 at 5 06 13 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/d688d90d-eba3-4b35-89a7-bd78f32dfb66">

Round: https://manager.gitcoin.co/#/round/0x86d8ec52e204384bb8309ede902883a21356f989/application/0x86d8ec52e204384bb8309ede902883a21356f989-0

**Comment by bhargavaparoksham** [comment]
@michellema1208 If i remember correctly, we only support erc20 payouts on DG as of now. As you are trying an ETH payment its failing. ref: https://discord.com/channels/562828676480237578/1162402031848403086/1162402031848403086
