### ISSUE TITLE
[Scroll] All: Add Scroll Sepolia testnet as a network on Grants Stack 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2777]
**User Story:**
As a Grants Stack user  
I want to be able to use Grants Stack on Scroll  
So that I can run a round on Scroll 

**Acceptance Criteria**
GIVEN that I am on Grants Stack (Builder / Manager / Explorer) 
WHEN I click on the network selection toggle 
THEN I see that Scroll is a supported network 

GIVEN that I am on Manager
WHEN I am setting up a round on Scroll 
THEN I see payout token options are ETH or USDC 

GIVEN that I am on Explorer 
WHEN I am donating to projects in a round on Scroll  
THEN I can set my donations on Scroll to be in ETH or USDC

**Product & Design Links:**
N/A 

**Tech Details:**
From Allo team: 
Allo v1 contracts: https://github.com/allo-protocol/allo-contracts/blob/main/docs/CHAINS.md 
Allo graph deployments Readme: https://github.com/allo-protocol/graph/tree/main/round
Query: https://api.studio.thegraph.com/proxy/45391/grants-round-scroll-sepolia/version/latest/graphql?query=%7B%0A++programs+%7B%0A++++id%0A++%7D%0A%7D

GS team resources: 
* Chain Deploy Checklist: https://www.notion.so/gitcoin/Chain-Deploy-Checklist-d4ed8c6664f14ac3b2da0f0d9c9a6219

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by gravityblast** [comment]
closing for now since LIT doesn't support scroll testnet
