### ISSUE TITLE
Some teams unable to load rounds on Explorer

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2811]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/round/42161/0x6142eedc06d80f3b362ce43b4ac52fad679dc850

### What happened?

When loading the a round from the Explorer homepage, they get redirected to a 404 page. See Loom and console error messages below. 

Loom: https://www.loom.com/share/30c84757bf5a4d51b9d5fc042e500adb?sid=aaf3c02d-bd16-43ae-9ebb-5afbcbf673d5

**_Arc Browser_** 
![arc_errors](https://github.com/gitcoinco/grants-stack/assets/26017180/b47be671-6656-44da-bf36-fbaf89fe8d34)

**_Brave Browser_**
![brave_logs](https://github.com/gitcoinco/grants-stack/assets/26017180/568712b2-6d0f-45b5-8d38-a12dff412dd0)

**_Safari Browser_** 
![safari_logs](https://github.com/gitcoinco/grants-stack/assets/26017180/fc5b9cdf-8fea-4f41-a530-e6fcf9640a07)

Note: @michellema1208 was not able to reproduce these errors on at least Safari & Brave, but the issue was still persisting with zkSync team. 

### What should have happened instead?

The round should have loaded properly. 

### Steps to Reproduce

1. Try on the following browsers: 
2. Go to https://explorer.gitcoin.co/#/round/42161/0x6142eedc06d80f3b362ce43b4ac52fad679dc850 
3. See error 

### What browser(s) are you seeing the problem on?

Safari

### What chain(s) did the error occur on?

Any

**Comment by M0nkeyFl0wer** [comment]
had the same issue. Here is a screenshot from what I saw:

<img width="953" alt="image" src="https://github.com/gitcoinco/grants-stack/assets/91565301/3e9e1ca8-cd5e-4525-848a-6b11edb52fcf">

**Comment by vacekj** [comment]
Working on this..

**Comment by michellema1208** [comment]
Closing this out as resolved
