### ISSUE TITLE
Indexer: reduce RPC calls for live indexing

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2819]
- will reduce RPC costs (alchemy, infura)
- will speed up live indexing, when a user creates a round and projects they should show up immediately
-

**Comment by boudra** [comment]
draft PR up here: https://github.com/gitcoinco/chainsauce/pull/18

instead of implementing websockets which will require a lot more effort, we can reduce the amount of round contracts we index at one time by not indexing rounds forever

**Comment by boudra** [comment]
there's a live indexing bug that is currently affecting Sepolia, which blocks us from releasing any work that uses the indexer right now
