### ISSUE TITLE
ARB Donations not showing up on the history page

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2827]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/round/42161/0x18a72e9940fb81860a809e266ebec42a9e2c44ce

### What happened?

We have a number of users reaching out about not seeing their donations on ARB to the Lunco case study round https://explorer.gitcoin.co/#/round/42161/0x18a72e9940fb81860a809e266ebec42a9e2c44ce

User 1: https://explorer.gitcoin.co/#/contributors/0x2961F7D23b9e4c102c373411f9580F92068eD3cc
tx: https://arbiscan.io/tx/0x9585761a2deeddc84267feaca78cc39083cfbe8c10dc0865033b13b7e981267c

User 2: https://explorer.gitcoin.co/#/contributors/0x40996469139E1BC0Ce469dc6595e740bDCa6e550
tx: https://arbiscan.io/tx/0xcec533eb8371d2ac75817b316d8e21dc778cabf2fb612f08997d3566ab26005f

**Link:** [Conversation with Yahya Seven](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/69966)

**Customer:** [Yahya Seven](https://app.intercom.com/a/apps/xaafeyri/users/65a4f75168dfd2b8a28940fe/all-conversations)
**Customer ID:** 231b5419-4fbb-4d69-9ad2-2dc6d9652b6b
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/69966) when this issue is closed.

### What should have happened instead?

Donations should show up on the donations history

### Steps to Reproduce

I can't reproduce since there are no more projects in the round

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

ARB

**Comment by michellema1208** [comment]
thank you so much @jesuloluwao ! 

Sharing some additional screenshots of the errors I'm seeing -- wondering @gravityblast / @boudra if this is a matter of restarting the Indexer?

<img width="1429" alt="Screen Shot 2024-01-18 at 3 44 50 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/24f0fa89-8787-45bf-8655-618d12106b3c">

<img width="1418" alt="Screen Shot 2024-01-18 at 3 46 54 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/959e07a7-6c57-4835-a1a6-101e2ec83568">

**Comment by michellema1208** [comment]
Closing as resolved
