### ISSUE TITLE
[Builder] Update getProjects query in the DataLayer to fetch projects in one query

### ISSUE THREAD

**Issue by boudra** [gitcoinco/grants-stack#2857]
**Overview**
We're currently looping through all chains and fetching projects for each one in a separate request, the indexer should be able to provide a list of projects for a list of chains in a single query, here's an example:

```graphql
{
  projects(filter: {chainId: {in: [10,5]}}) {
    id,
    chainId
  }
}
```

- Implement the query in a single GraphQL request

**Details**
Say more

**Comment by michellema1208** [comment]
@thelostone-mc / @boudra - is this ticket still relevant / something we want to do? Seeing it's marked as "Ready" on the Builder v2 Migration board, and "Backlog" on the Grants Stack board so I'm not sure

**Comment by boudra** [comment]
moved back to in progress since the PR is still draft and there are todos in the description and in code

**Comment by boudra** [comment]
@thelostone-mc why did you move this to PR review, is this ready to review?
