### ISSUE TITLE
All Zuzalu project links redirect to explorer.gitcoin.co

### ISSUE THREAD

**Issue by MathildaDV** [gitcoinco/grants-stack#2866]
### What was the URL where the error occurred?

both Zuz rounds! (will link below)

### What happened?

https://explorer.gitcoin.co/?utm_source=grants.gitcoin.co&utm_medium=internal_link&utm_campaign=gg19&utm_content=independent-rounds#/round/10/0xd875fa07bedce182377ee54488f08f017cb163d4

https://explorer.gitcoin.co/?utm_source=grants.gitcoin.co&utm_medium=internal_link&utm_campaign=gg19&utm_content=independent-rounds#/round/10/0xf89aad3fad6c3e79ffa3ccc835620fcc7e55f919

This is happening on **all projects**. The links for their github and twitter accounts redirects to explorer.gitcoin.co. It seems like their website links are still working however.

### What should have happened instead?

Github & Twitter links should not link back to explorer.

### Steps to Reproduce

1. Go to a project in a Zuzalu round with both Twitter & Github: https://explorer.gitcoin.co/?utm_source=grants.gitcoin.co&utm_medium=internal_link&utm_campaign=gg19&utm_content=independent-rounds#/round/10/0xd875fa07bedce182377ee54488f08f017cb163d4/0xd875fa07bedce182377ee54488f08f017cb163d4-25 
2. Click on Twitter link -> notice it redirects to explorer.gitcoin.co/<username> 
3. Click on Github link -> notice it redirects to explorer.gitcoin.co/<username> 

### What browser(s) are you seeing the problem on?

All 

### What chain(s) did the error occur on?

All

**Comment by gravityblast** [comment]
fixed with https://github.com/gitcoinco/grants-stack/pull/2886
