### ISSUE TITLE
[spike] Contract changes for Manager Round Edit flow

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2890]
**Overview**

On Manager v2, is it possible to update contracts to support the following:

- [ ] Be able to edit ALL round settings anytime even if date has passed. This includes all fields such as: 

- ✅ Round name
  Saved in the metadata and can always be updated.
- ✅ Round description 
  Saved in the metadata and can always be updated.
- ✅ Support input and contact information 
  Saved in the metadata and can always be updated.
- ✅ Public/private visibility of round 
  Saved in the metadata and can always be updated.
- ✅ Eligibility requirements 
   Saved in the metadata and can always be updated.
- 🟡 (requires changes) Application period date/times (also for Direct Grants) 
   In `DonationVotingMerkleDistributionBaseStrategy.sol`, the function `updatePoolTimestamps` can be called at any time. We need to remove the check on `block.timestamp > _registrationStartTime`. This will allow to move the application end time during application time, without having to change the application start time too.
- ✅ Enabling rolling applications 
  This is already supported by the `DonationVotingMerkleDistributionBaseStrategy`. It's possible to have `_registrationEndTime > `_allocationStartTime`
- 🟡 (requires changes) Donation period date/times 
  It need to be changed together with the application period times. 
-  🛑 Payout token 
  The payout token cannot be changed after the creation of the Pool and its logic can only be changed in the core `Allo.sol` contract.
- 🟡 (requires changes in the UI) Be able to Increase or decrease matching pool amount (today, you can only increase the amount)
  We have 2 variables here:
   - `matchingFundsAvailable`: this is a number in the metadata that can be changed at any time. 🟡 we need to change the UI to allo setting any number, even decreasing the value.
   - `roundBalance`: this is the actual balance of the round in the pool tokens. This value changes after calling `fundPool` and can only increase adding tokens to the round.
- ✅ Matching cap 
  Saved in the metadata and can always be updated.
- ✅ Minimum donation threshold 
  Saved in the metadata and can always be updated.
- ✅ Sybil defense 
  Saved in the metadata and can always be updated.
- ⍰ Project Socials -- requiring Twitter/Github and verification of Twitter/Github should be able to be edited at any time
  needs to be checked where we validate in the UI but for sure it's possible to update it in the metadata
- 🟡 (requires changes in the UI)Application questions and all metadata associated with application questions as well as being able to add new application questions/remove existing questions (today, you can't edit application questions at all) 
  🟡🟡requires changes in the UI but it's always possible to update the metadata. updating questions after the application period started might mix up old/new question/answers
**Details**
Say more

**Comment by thelostone-mc** [comment]
Just reviewed this list.
This looks good to me
- The payout token changing is not something which would be possible

A quick callout:
-  Also the pool amount cannot be decreased as you would call Allo.fundPool and only when funds are transferred is it updated. If we want to support creating a round with matching amount without actually funding it . This woud have to be handled on the metadata (which means we can in theory do increase / decrease )

**Comment by gravityblast** [comment]
> Also the pool amount cannot be decreased as you would call Allo.fundPool and only when funds are transferred is it updated. If we want to support creating a round with matching amount without actually funding it . This woud have to be handled on the metadata (which means we can in theory do increase / decrease )

yes exactly, I added 2 "variables" above in the ticket. `matchingFundsAvailable` which is just a number in the metadata and can be changed any time. `roundBalance` is the actual pool balance, that can only increase. does it make sense?

**Comment by michellema1208** [comment]
thanks @gravityblast @thelostone-mc ! 

We should be good to skip being able to change payout token after a round has been created as it would require changes to Allo core contracts. FYI @meglister 

For increasing/decreasing matching funds, is it that we can change the contracts to accept increasing/decreasing matching pool amount after a round has been deployed, but once the round contract has been funded with a certain amount of tokens, we cannot allow a decrease in tokens? 

So if I have a round where my matching pool amount is 100 DAI, as long as I haven't funded my contract with 100 DAI, I could increase/decrease the matching pool amount to 90 DAI, 50 DAI, 1000 DAI, etc. But once I've funded my contract with let's say 50 DAI, I can only decrease the matching pool amount to a minimum of 50 DAI or increase my matching amount. And if I fully funded my contract with 100 DAI, I'm not able to decrease my matching amount at all, only increase?

**Comment by gravityblast** [comment]
@michellema1208 exactly!

**Comment by thelostone-mc** [comment]
Yes @michellema1208
