### ISSUE TITLE
Branding updates & Report Card integration

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#2909]
This ticket includes:

- Branding updates to the round page 
- Report card integration

Designs: [Figma](https://www.figma.com/file/5m4EgbkSCMVgc2eSAa18rB/Report-Cards?type=design&node-id=81-3287&mode=design)

**Comment by pannu5788** [comment]
Pi Network, a decentralized digital currency project, has announced that it will be launching its mainnet on December 27, 2024. This marks a significant milestone for the project, as it will transition from its current testnet phase to a fully operational network.

The Pi Network aims to create a more inclusive and user-friendly digital currency that is accessible to people around the world. By launching its mainnet, the project will be able to offer a more secure and efficient platform for users to transact and engage with the Pi cryptocurrency.

The team behind the Pi Network is excited about the mainnet launch and is confident that it will help propel the project to new heights. Users can look forward to more features, better performance, and a more robust network that will support the growth of the Pi ecosystem.

As the launch date approaches, the Pi Network team will be sharing more details and updates on what users can expect from the mainnet. Stay tuned for more information and get ready to experience the next phase of the Pi Network journey.
