### ISSUE TITLE
Explorer: disable matching estimates for Avalanche round

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2919]
**Overview**
Disable matching estimates for Avalanche round, as it would require additional calculations work in the Indexer and put the migration work at-risk. 

**Details**
Say more

**Comment by codenamejason** [comment]
- [ ] Update round manager to not show matching round stats when on Avalanche.
- [ ] Update grant explorer to not show the matching stats for rounds on Avalanche.
