### ISSUE TITLE
Explorer: Round cards on Home page are not loading

### ISSUE THREAD

**Issue by Difint** [gitcoinco/grants-stack#2921]
### What was the URL where the error occurred?

https://explorer.gitcoin.co

### What happened?

Round cards on Explorer are not loading. According to Network requests in Chrome Debug tool it stuck in infinite cycle loading rounds data from Subgraph again and again

![image](https://github.com/gitcoinco/grants-stack/assets/101790821/d93568a8-9fa4-45c1-bd88-dd0024dd2c1b)

### What should have happened instead?

Explorer Home page should show rounds

### Steps to Reproduce

Open explorer on desktop/mobile

### What browser(s) are you seeing the problem on?

Chrome, Safari

**Comment by PashaBurg** [comment]
![IMG_1874](https://github.com/gitcoinco/grants-stack/assets/107597730/c2e3f8e3-202a-4e09-bf54-e404bed19424)

The same on mobile iOS. Took around 40 seconds to appear
