### ISSUE TITLE
Explorer: donate to a round on allo V2

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2938]
(depends on #2937)

**Overview**

The goal of this ticket is to implement the Allo V2 contract interactions to donate to a round on Allo V2

**Details**

In Grants Stack we are going to support 1 donation voting strategy:

https://github.com/allo-protocol/allo-v2/blob/main/contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol

We should be able to donate:

* with a native token
* with a standard permit token
* with a token using the DAI permit implemention

**Comment by vacekj** [comment]
@gravityblast question - I see no actual donate or allocate method in the linked strategy. Is finishing the implementation of this strategy part of this ticket? I'm probably overlooking something.

**Comment by gravityblast** [comment]
@vacekj let's get familiar with the Allo protocol. 
It has an `allocate` function https://github.com/allo-protocol/allo-v2/blob/3e59eb7aed6781814bc4ddda8ba86e0df25bf43d/contracts/core/Allo.sol#L368

that forwards the data to the strategy: https://github.com/allo-protocol/allo-v2/blob/3e59eb7aed6781814bc4ddda8ba86e0df25bf43d/contracts/strategies/donation-voting-merkle-distribution-direct-transfer/DonationVotingMerkleDistributionDirectTransferStrategy.sol#L45

**Comment by vacekj** [comment]
@gravityblast thanks, I was looking in the wrong file

**Comment by vacekj** [comment]
Notes: Do we still plan on implementing MRC for allo-v2? Because if so, it would be advisable to also implement classic voting as in v1, so that MRC may call this function directly and handle permits on the MRC level. 

Donating using 2612 permit (or Permit2 for that matter) directly on the strategy is only more efficient if the user is voting on that single round, otherwise the user would be signing many more EIP-712 payloads and the UX would be terrible (not to mention less gas efficient). 
@gitcoinco/grantsstack

**Comment by gravityblast** [comment]
For Allo V2 we don't need the MultiRoundCheckout contract because Allo V2 already supports donating to multiple pools.
We already have a PR to have permit and DAI permit support on Allo V2 on top of the already supported permit2
https://github.com/allo-protocol/allo-v2/pull/472

> Donating using 2612 permit (or Permit2 for that matter) directly on the strategy is only more efficient if the user is voting on that single round, otherwise the user would be signing many more EIP-712 payloads and the UX would be terrible

There's no other way to do it without changing the core Allo contracts (that we can't change). So we must have a signed permit message for each round you are donating to. It's more signatures but only 1 actual transaction.

**Comment by gravityblast** [comment]
@vacekj @thelostone-mc let's sync in discord to understand who can deploy it to be able to test it in staging
