### ISSUE TITLE
Can't Update Round End Time in Manager - Fails when trying to sign

### ISSUE THREAD

**Issue by M0nkeyFl0wer** [gitcoinco/grants-stack#2941]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/round/0xd875fa07bedce182377ee54488f08f017cb163d4

Zuzalu Tech Round: 0xd875fa07bedce182377ee54488f08f017cb163d4
Zuzalu Events round: 0xf89aad3fad6c3e79ffa3ccc835620fcc7e55f919

### What happened?

I am in the Zuzalu round trying to extend the end date using the built in UX. I am trying to change the end time to the 23rd at 5pm (currently ends midnight utc on the 15. 

![image](https://github.com/gitcoinco/grants-stack/assets/91565301/52a31012-bfdf-4c4b-ba63-79bee2a3135d)

This is somewhat urgent because Vitalik has requested that we extend the round and it ends in about 8 hours at the time of me writing this. 

I am seeing an error message pop up almost immediately at the first step of the signature. 

![image](https://github.com/gitcoinco/grants-stack/assets/91565301/1b8e6494-01e2-4fcf-b725-795d5d7633a8)

After the failure the page reloads and it appears there are no grantees in the round which is a little scary but not an actual issue, just thought it was worth mentioning. 

Thanks for your help with this.

### What should have happened instead?

The closing date for the round should be updating but currently that isn't working. 

### Steps to Reproduce

1. Go to Manager and sign in to the round (or use the deg functionality) 
2. go to round settings and then the schedule tab and click on the edit button
3. use the drop down calendar menus to update the date and time (don't even try to just edit the numbers directly... use the GUI)
4. click save and initiate the onchain signature ... this is where it fails

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Optimism 

### Relevant log output

```shell
net::ERR_CONNECTION_RESET
instrument.ts:144 getApplicationsByRoundId TypeError: Failed to fetch
    at instrument.ts:174:28
    at fetchObservable.ts:55:45
    at O (instrumentMethod.ts:21:28)
    at El (utils.ts:114:10)
    at kU (application.ts:192:30)
(anonymous) @ instrument.ts:144
Show 1 more frame
Show less
instrument.ts:144 fetchApplicationByRoundId roundId - 0xd875fa07bedce182377ee54488f08f017cb163d4 TypeError: Failed to fetch
    at instrument.ts:174:28
    at fetchObservable.ts:55:45
    at O (instrumentMethod.ts:21:28)
    at El (utils.ts:114:10)
    at kU (application.ts:192:30)
(anonymous) @ instrument.ts:144
Show 1 more frame
Show less
provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":false}}
provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":false,"chainId":"0x1"}}
injectWalletGuard.js:1 Wallet Guard is running!
o4504301442957312.ingest.sentry.io/api/4504326431834112/envelope/?sentry_key=8e4a7b697f9845ff88b737476e32f0e0&sentry_version=7&sentry_client=sentry.javascript.react%2F7.68.0:1 
        
        
       Failed to load resource: the server responded with a status of 429 ()
```

**Comment by M0nkeyFl0wer** [comment]
Zuzalu Tech Round: 0xd875fa07bedce182377ee54488f08f017cb163d4
Zuzalu Events round: 0xf89aad3fad6c3e79ffa3ccc835620fcc7e55f919

**Comment by thelostone-mc** [comment]
@jesuloluwao Lemme know if you can reproduce this. I've tested this on local and production and cannot reproduce the error
