### ISSUE TITLE
Invalid Type Error on Local Dev Setup

### ISSUE THREAD

**Issue by owocki** [gitcoinco/grants-stack#2957]
### What was the URL where the error occurred?

http://localhost:3000/

### What happened?

Page displayed blank with a JS console error.

### What should have happened instead?

Page X should display Y

### Steps to Reproduce

1. follow dev instructions on a new mac => https://github.com/gitcoinco/grants-stack/blob/main/docs/DEV.md
2. run `pnpm start`

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

N/A

### Relevant log output

```shell
bundle.js:35132 Uncaught ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at get error (types.js:43:31)
    at ZodString.parse (types.js:143:22)
    at getConfig (config.ts:112:12)
    at eval (chains.ts:24:25)
    at ../common/dist/chains.js (bundle.js:16734:1)
    at options.factory (bundle.js:35840:31)
    at __webpack_require__ (bundle.js:35129:33)
    at fn (bundle.js:35497:21)
    at eval (allo-v1.ts:15:1)
    at ../common/dist/allo/backends/allo-v1.js (bundle.js:16644:1)
```

**Comment by gravityblast** [comment]
thank you @owocki ! if you click on `getConfig (config.ts` you should be able to see which env var is missing. in case is missing in the .dev example file we can add it

**Comment by owocki** [comment]
@gravityblast its `REACT_APP_GRANTS_STACK_SEARCH_API_BASE_URL`

but i have it defined in my .env
```
# Search API URL where the Data Layer should point to
REACT_APP_GRANTS_STACK_SEARCH_API_BASE_URL="https://d2n9vtjeq685yt.cloudfront.net"
```
...

so im not sure whats going on?


screencap:
<img width="819" alt="Screenshot 2024-03-04 at 4 54 48 PM" src="https://github.com/gitcoinco/grants-stack/assets/513929/6a34c7c1-2fbc-4f0e-85d2-b1b812a9261a">

**Comment by gravityblast** [comment]
is it possible you are running `pnpm start` at the root instead of in `packages/builder`. in that case it would start manager and it would need the same env there

**Comment by owocki** [comment]
@gravityblast ooh i was running it from root.  that gets me past the `REACT_APP_GRANTS_STACK_SEARCH_API_BASE_URL` issue!

when i run the command from `packages/builder` it says `REACT_APP_SUBGRAPH_DEV1_API` is undefind.  i dont see this in the `.env.example`. if i look at `config.ts` i see other env variables that are not in the .env.example a la `REACT_APP_SUBGRAPH_DEV2_API`

if we want ppl contributing to this repo, [it should be less than 30 mins to get a hello world up.](https://twitter.com/dabit3/status/1763652678222299428)  i feel like the repo could benefit from a pass from a core dev to make sure that its easy (and no errors) to go through https://github.com/gitcoinco/grants-stack/blob/main/docs/DEV.md + set up a fresh repo end to end.

**Comment by gravityblast** [comment]
@owocki great point, I opened a PR to add more docs and tested from scratch https://github.com/gitcoinco/grants-stack/pull/3097

**Comment by owocki** [comment]
ok i was able to get it working with info from that pr

**Comment by dylsteck** [comment]
Hey! I'm working on creating a PR to add Farcaster frames to the `grants-explorer` page but am running into this same error locally after following the steps in [#3097](https://github.com/gitcoinco/grants-stack/pull/3097) -- is there anything else I'm missing?

The steps I took were(from DEV.md):
- Clone the repo locally
- `pnpm install` at the root
- `cd packages/grants-explorer` and `cp .env.example .env`
- Fill in the appropriate .env info such as `REACT_APP_WALLETCONNECT_PROJECT_ID`, `REACT_APP_ALCHEMY_ID`, `REACT_APP_PINATA_JWT`, and `REACT_APP_PASSPORT_API_KEY`
- Run `pnpm start`

When I run start I see the error below

<img width="345" alt="Screenshot 2024-04-07 at 1 38 38 PM" src="https://github.com/gitcoinco/grants-stack/assets/12853808/b0df4009-6d26-402e-90ce-b5eb7854b1e3">

**Comment by thelostone-mc** [comment]
@dylsteck look at config.ts line 253 and you'll see it's expecting REACT_APP_PASSPORT_API_COMMUNITY_ID_AVALANCHE="000". Make sure you refer the latest .env.example
