### ISSUE TITLE
[placeholder] Add support for dates on Direct Grants rounds in Allo v2

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2984]
**Overview**
From @boudra: for the DG dates, it looks like the Allo V2 DG strategy doesn't support dates, so the chosen dates won't be picked up, we'll probably have to change that strategy contract or figure something else out, I'll catch up with @gravityblast | Gitcoin to see what we can do here

**Details**
Say more

**Comment by 0xKurt** [comment]
done @michellema1208 :
https://github.com/allo-protocol/allo-v2/pull/479

**Comment by michellema1208** [comment]
Closed with: https://github.com/gitcoinco/grants-stack/pull/3103
