### ISSUE TITLE
update sdk to accomodate the changes in DG

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#3046]
Changed needed to unblock applyToRound 

- [x] deployment and whitelist the new direct grants contract (only in mumbai)
- [x] update sdk to accomodate the changes
- [x] update indexer to index the new timestamps
- [ ] update round manager to support the new contract changes to create Direct Grants round

**Comment by 0xKurt** [comment]
whitelist proposal:
https://defender.openzeppelin.com/#/admin/contracts/mumbai-0x1133eA7Af70876e64665ecD07C0A0476d09465a1/proposals/37658aa2-4ee3-456a-8bb2-b9b1774d0e1c

**Comment by 0xKurt** [comment]
sdk updates:
https://github.com/allo-protocol/allo-v2-sdk/pull/43

New SDK version: 1.0.52
