### ISSUE TITLE
[spike] Cluster Match QF UX 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3053]
**Overview**
Answer open questions about Cluster Match QF integration that might impact UX. 

**Questions**

- [ ] Can we support cluster match QF as the algorithm for matching estimates? Or should all matching estimates by default be using basic QF? 
- [ ] What error states could occur when changing the QF algorithm at the Finalize Results step?

**Comment by gravityblast** [comment]
@michellema1208 

>  Can we support cluster match QF as the algorithm for matching estimates? Or should all matching estimates by default be using basic QF?

for now we don't have a plan for estimates with Cluster Matching, we need some input from @ufkhan97

>  What error states could occur when changing the QF algorithm at the Finalize Results step?

I think we will have a single error but multiple states for the calculations:

* not requested
* pending (requested)
* running
* failed
