### ISSUE TITLE
Manager + Indexer: Add GTC as a payment token for QF rounds on Arbitrum

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3067]
**Overview**
Add GTC as a payment token for QF rounds on Arbitrum in both Manager FE + Indexer.

**Details**
Contract on Arbitrum: https://arbiscan.io/token/0x7f9a7db853ca816b9a138aee3380ef34c437dee0

Related to: https://github.com/gitcoinco/grants-stack/issues/2305

**Comment by gravityblast** [comment]
closed with https://github.com/gitcoinco/grants-stack/pull/3068
