### ISSUE TITLE
Direct Grant program on ZKSync is not listed in Explorer

### ISSUE THREAD

**Issue by Difint** [gitcoinco/grants-stack#3071]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/round/324/0x5f398005a8a32793348dbae01a652d202e257a3e

### What happened?

Direct Grant program on ZKSync is not listed in Explorer, however there are other direct grants that are listed

### What should have happened instead?

Should be listed

### Steps to Reproduce

Go to explorer. No Direct round grant there

**Comment by thelostone-mc** [comment]
This has been fixed now
