### ISSUE TITLE
Crowdfund not working with error from web3

### ISSUE THREAD

**Issue by Difint** [gitcoinco/grants-stack#3072]
### What was the URL where the error occurred?

https://crowdfund.gitcoin.co/pool/create

### What happened?

I started to create a crowdfund on Polygon and got an error

### What should have happened instead?

Create Crowdfund should work

### Steps to Reproduce

Start createing crowdfund

### Relevant log output

```shell
Error: This API feature has been sunset, and is no longer available. To continue uploading, use the new web3.storage API: https://web3.storage/docs.
```

**Comment by PashaBurg** [comment]
The same here from Metamask and Zerion built in browsers. First no error message then if back see Error from the screenshot below

![IMG_2438](https://github.com/gitcoinco/grants-stack/assets/107597730/2cb08556-31c8-4d95-9beb-90803d1666f2)
![IMG_2439](https://github.com/gitcoinco/grants-stack/assets/107597730/8801f629-f153-4cf1-94cd-a748079d0a2b)

**Comment by thelostone-mc** [comment]
Closing as this is not on grants-stack
