### ISSUE TITLE
Indexer is down

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#3085]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/

### What happened?

Indexer is down across all apps/chains. No data is showing in our apps.

### What should have happened instead?

Indexer should not be down

### Steps to Reproduce

1. Go to explorer.gitcoin.co
2. Observe no data loads on page
3. Observe errors in console indicating that indexer is non responsive

**Comment by Difint** [comment]
Manager is not working as well
