### ISSUE TITLE
prevent applying on v2 round with v1 project / vice versa

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#3086]
Update the applyToRound page to ensure 
- only a profile on v1 can apply to v1 round 
- only a profile on v2 can apply to v2 round

**Comment by 0xKurt** [comment]
Shouldn't it be done already?
to test:
go to 
https://builder-staging-git-v2-donations-explorer-grants-stack.vercel.app/#/chains/11155111/rounds/92 
click on v1
