### ISSUE TITLE
Transaction History not showing on Polygon

### ISSUE THREAD

**Issue by SovereignSignal** [gitcoinco/grants-stack#3110]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/contributors/0x882dbB2a85053d3C620Bb308268e7ee82464EE1e?debug=true

### What happened?

user saying they can't see history on Polygon.  Here's the deets:

Wallet:
https://explorer.gitcoin.co/#/contributors/0x882dbB2a85053d3C620Bb308268e7ee82464EE1e?debug=true

txn hash:
https://polygonscan.com/tx/0x7858cf2c882b9a97ee73a02b49836f7186ae5e3169c473b33d5713a1eb781a74

### What should have happened instead?

User should be able to see transaction history

### Steps to Reproduce

Wallet:
https://explorer.gitcoin.co/#/contributors/0x882dbB2a85053d3C620Bb308268e7ee82464EE1e?debug=true

txn hash:
https://polygonscan.com/tx/0x7858cf2c882b9a97ee73a02b49836f7186ae5e3169c473b33d5713a1eb781a74

### What chain(s) did the error occur on?

Polygon

**Comment by gravityblast** [comment]
@SovereignSignal I see now the donation in the contributors page, can you confirm?

**Comment by SovereignSignal** [comment]
Yes looks good to me I just let the user know I think we are good to close this out.  Thanks ser!
