### ISSUE TITLE
Manager: frontend changes for Passport Lite x Cluster Match MVP

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#3131]
**Overview**
designs

manager: https://www.figma.com/file/bB15jl5yBhuceBS3qgXngi/Manager-S20?type=design&node-id=225-1400&mode=design

**Comment by michellema1208** [comment]
Design requests: 

* Move raw round data to left sidebar 
* Decision point for default results or custom results 
* New upload section for custom results

**Comment by michellema1208** [comment]
Engineering spike ticket - what does that table / template for file upload for custom results
