### ISSUE TITLE
Manager: on v1 QF rounds, allow application end date and round start date to overlap 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3133]
**Overview**
Follow up from: https://github.com/gitcoinco/grants-stack/pull/3090

For v1 QF rounds: 
Not able to edit round start date to be before an application end date (i.e. overlapping application and round dates), even if the current round start date has not passed

**Details**
Say more

**Comment by codenamejason** [comment]
I just tested main and with a new round you are able to update the round date to be before app end date as long as it is after current date. To confirm, create a new QF round on v1 and try to set the round start date to before the app end date. Use manager staging link on Sepolia.

**Comment by michellema1208** [comment]
@codenamejason confirming this is working on staging - closing this ticket!
