### ISSUE TITLE
Manager: for v2 QF rounds, not able to edit app or round dates

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3135]
**Overview**
Follow up from: https://github.com/gitcoinco/grants-stack/pull/3090

QF Round on v2
Not able to edit application or round dates, even if dates have not passed

Use this round: https://manager-staging-git-edit-grants-stack.vercel.app/#/round/75?debug=true 

**Details**
Say more

**Comment by codenamejason** [comment]
I was able to edit my dates on a newly created round.

**Comment by michellema1208** [comment]
closing this issue as well!
