### ISSUE TITLE
Explorer: homepage showing incorrect match amount in USD

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3141]
### What was the URL where the error occurred?

explorer.gitcoin.co

### What happened?

USDC amount is way too big. 

Context: https://discord.com/channels/562828676480237578/1111042625546485872/1217902088676311040 

### What should have happened instead?

Page X should display Y

### Steps to Reproduce

1. Go to Explorer 
2. See incorrect match amount in USDC

**Comment by thelostone-mc** [comment]
This would be fixed as a result of https://github.com/gitcoinco/grants-stack/issues/3167
