### ISSUE TITLE
wait for indexer when voting

### ISSUE THREAD

**Issue by boudra** [gitcoinco/grants-stack#3144]
we get a lot of reports from people not seeing their donation in the donation history page, waiting for the donation to be indexed in the checkout before redirecting them to the thank you page should help get reduce the amount of complaints

what to do:

- add a "waiting for indexer" step to the donation modal
- only redirect to the thank you page after the indexer has reached the transaction block
- if the indexer fails to index, we should redirect them to the thank you page anyways, since the vote will be counted and we don't want the user to think their donation failed

**Comment by gravityblast** [comment]
good point thank you @boudra ! let's keep in mind the multi round checkout scenarios where we need to wait for multiple chains to be indexed, each one with its own block. /cc @michellema1208

**Comment by thelostone-mc** [comment]
We just fixed this as part of https://github.com/gitcoinco/grants-stack/issues/3187

**Comment by michellema1208** [comment]
@thelostone-mc / @0xKurt is there additional work to do for QA? If so, can you share more details/instructions?

**Comment by thelostone-mc** [comment]
No additonal QA
