### ISSUE TITLE
when applying to a round without selecting a project it just hangs

### ISSUE THREAD

**Issue by boudra** [gitcoinco/grants-stack#3161]
### What was the URL where the error occurred?

https://grants-stack-builder-staging.vercel.app/#/chains/11155111/rounds/0xf56f62b53966874764a3563d02eea75a3f4ed13c/apply

### What happened?

submitting the form without selecting a project fails with an error in the console and modal hangs forever

<img width="410" alt="Screenshot 2024-03-20 at 14 00 18" src="https://github.com/gitcoinco/grants-stack/assets/711886/19221107-d97a-4124-aa73-f9f81058896d">
<img width="725" alt="Screenshot 2024-03-20 at 14 00 10" src="https://github.com/gitcoinco/grants-stack/assets/711886/322506a4-f9e5-40c2-acfe-e4d6171975c7">

### What should have happened instead?

probably should let the user know that the project is required

### Steps to Reproduce

1. go to https://grants-stack-builder-staging.vercel.app/#/chains/11155111/rounds/0xf56f62b53966874764a3563d02eea75a3f4ed13c/apply
2. submit the form without selecting a project

### What browser(s) are you seeing the problem on?

Firefox

### What chain(s) did the error occur on?

Sepolia

**Comment by 0xKurt** [comment]
fixed in c0fc1bb9fc82c8b316777aea37217bb3e6e8791a



![Image](https://github.com/gitcoinco/grants-stack/assets/22886639/342fc8f6-7184-4fdf-8cfe-6a5dc0469d17)

**Comment by michellema1208** [comment]
@thelostone-mc / @0xKurt is there a PR for this ticket to QA?

**Comment by michellema1208** [comment]
seeing this is fixed in prod, closing
