### ISSUE TITLE
Manager: ETH Price on Fund Contract tab is wrong

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3167]
### What was the URL where the error occurred?

https://manager-git-allo-migration-grants-stack.vercel.app/#/round/6

### What happened?

It's showing 0.01 ETH is $3317

<img width="1440" alt="Screen Shot 2024-03-20 at 3 51 43 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/ba27cd96-3a34-42a2-9d88-389824f6b9eb">

### What should have happened instead?

Should show 0.01 ETH is about $33

### Steps to Reproduce

1. Go to https://manager-git-allo-migration-grants-stack.vercel.app/#/round/6 
2. Click Fund Contract tab 
3. See incorrect prices

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum

**Comment by thelostone-mc** [comment]
```
{
  rounds(filter: {id: {equalTo: "6"}}) {
    matchAmount
    matchAmountInUsd
    matchTokenAddress
  }
}
```

Need to dig into the on how matchAmountInUsd is calculated
