### ISSUE TITLE
[builder] On project creation I have to refresh / (allo-v2 on Base)

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-stack#3185]
### What was the URL where the error occurred?

https://builder-git-allo-migration-grants-stack.vercel.app/

### What happened?

On project creation I have to refresh the page to see my new project on allo-v2.

![Screenshot 2024-03-21 at 1 36 07 PM](https://github.com/gitcoinco/grants-stack/assets/9419140/74de7a78-8737-47bf-a2a4-982c9329934a)

### What should have happened instead?

the page should have refreshed automatically.

![Screenshot 2024-03-21 at 1 39 16 PM](https://github.com/gitcoinco/grants-stack/assets/9419140/52351f62-2209-428a-ada0-cc292608e1a6)

### Steps to Reproduce

1. Create a new project on Base (make sure you are on v2)

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Base

### Relevant log output

```shell
N/A
```

**Comment by michellema1208** [comment]
Closing as resolved
