### ISSUE TITLE
Explorer: application pages are not loading

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3188]
### What was the URL where the error occurred?

https://explorer-git-allo-migration-grants-stack.vercel.app/#/round/42161/6/0

### What happened?

Application pages are not loading. 

### What should have happened instead?

I should be able to see an application page for projects accepted in rounds. 

### Steps to Reproduce

1. Go to https://explorer-git-allo-migration-grants-stack.vercel.app/#/round/42161/6/0
2. See that no data is loaded 

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum

**Comment by thelostone-mc** [comment]
![image](https://github.com/gitcoinco/grants-stack/assets/5358146/78d2fae9-5b1f-4b71-b8eb-3073b4d94124)

Fixed now

**Comment by michellema1208** [comment]
seeing this in prod - closing this ticket!
