### ISSUE TITLE
unchecking a chain in the checkout popup makes it dissapear

### ISSUE THREAD

**Issue by boudra** [gitcoinco/grants-stack#3190]
in this pop up:

<img width="540" alt="Screenshot 2024-03-22 at 14 10 46" src="https://github.com/gitcoinco/grants-stack/assets/711886/c52acd8a-06e1-4ce4-89b5-4d34462253e3">

when you uncheck a chain, it dissapears, so you cannot check the chain again:

<img width="540" alt="Screenshot 2024-03-22 at 14 10 56" src="https://github.com/gitcoinco/grants-stack/assets/711886/daf6d0ea-2db8-425d-964d-557dcdf81eee">

I expect the chain stay there and  just be unchecked

**Comment by thelostone-mc** [comment]
As per product, we are simplifying this to ensure you can't uncheck the chain when you have only 1 chain in the cart
