### ISSUE TITLE
direct grants v2 : overview

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#3204]
- [ ] #3205
- [ ] #3206
- [ ] #3207
- [x] #3208
- [ ] #3209
- [ ] #3210
- [ ] #3211

**Comment by owocki** [comment]
im a big fan of galls law: start simple + evolve more complexlity

in that spirit: why does direct grants have to be complicated...  why cant we just ;make it so you can send tokens to a grants address directly?  ethereum supports that natively already.

then we validate the market for direct grants from a sales/bd perspective and build it into allo and more complexlity from there.
