### ISSUE TITLE
review contracts to ensure payouts without milestone are possible

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#3208]

**Comment by thelostone-mc** [comment]
Based on research looks like we have a few options laid out cause the contracts and grants-stack are quite different.

**Option 1:**
- Rewrite the contract for direct grants to match the requirements of grants-stack
- Least effort but limits the ability to add new features on grants-stack at the contract level 

**Options 2:**
- Based on the original requirements 
  - there is an extra step which lets the manager say which grants are being reviewed ( extra txn)
  - there is an extra step where the manager has to submit milestones (this would have to be hidden), and we'd have to ask the manger to pre decide how many payouts they would do per grant and the amount 
  - Medium effort ( A week ) but this is just like putting a band aid over a crack
  
  **Options 3**
- We update the UI to actually implement direct grants as per spec
- This means there will be new screens 
  - to upload milestones
  -  to mark users from pending to In Review
  - to be able to let grants submit milestones once approved
  - High effort (2-3 weeks)

**Comment by meglister** [comment]
Adding the original spec for direct grants which we should use as source of truth for this project: https://docs.google.com/document/d/1NsqY1h136SeVe1NmKpKXsY5wA03nHecw-lVJl6B1Ch0/edit

Noting that we decided on Option 1 as this is the smoothest path forward. We do already have a custom status in the GS UI.
