### ISSUE TITLE
Add in-app guidance about Passport Lite x Cluster Match 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3224]
**Overview**
Context from @meglister in this [thread](https://discord.com/channels/562828676480237578/1103312675586445332/1221886500946448484): 

"I’ve got a yes-and here which hopefully isn’t too much scope creep…
- Joel pointed out that making people aware the round was Sybil protected in the background was helpful in deterring attacks. I wonder if we could incorporate some copy to this effect in the checkout process?

- I’m wondering how we can incorporate some guidance around cluster matching use in round setup. Again this should just be copy — but perhaps we expand the guidance around “yes passport / no passport” to incorporate “turn off passport to use passport lite”

**Tasks**
- [ ] Add copy / UX component (i.e. banner, alert, etc.) in checkout flow on Explorer about the round being protected by Cluster Match + Ethereum Stamp (public name for Passport Lite)

> From Michelle - some starter copy you can work off of: "This round is protected by a combination of Cluster Match Quadratic Funding and the Ethereum Stamp." 

Related resources: 
- https://gov.gitcoin.co/t/gcp-010-evolving-gitcoin-grants-the-q-e-d-quadratic-experimentation-and-development-program/14174
- https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-passport/navigating-your-ethereum-stamp-insights-and-updates

- [ ] Update copy / UX component (i.e. banner, alert, etc.) in round setup flow on Manager to inform Grant Managers about Passport vs. Ethereum Stamp as sybil defense options, perhaps also a third option that is no Passport interaction at all? (should double check with @boudra if the latter is possible today)

**Comment by michellema1208** [comment]
Edge cases: 

- I choose Passport Lite 
- Matching estimates will be 
- At Finalize - if I choose the normal calculator (instead of cluster match), then normal calculator will not know about Passport Lite

**Comment by boudra** [comment]
these edge cases and coopy are handled in the designs in this task: https://github.com/gitcoinco/grants-stack/issues/3131
