### ISSUE TITLE
Explorer: Update nav bar for GG20

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3228]
**Overview**

- [x] Add all rounds featured on https://grants.gitcoin.co/ to Explore Rounds dropdown on Explorer. See [Figma](https://www.figma.com/file/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?type=design&node-id=502-9785&mode=design) below

- [x] This ticket also includes some styling updates to fit in with broader branding updates - see [Figma](https://www.figma.com/file/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?type=design&node-id=502-9785&mode=design). These branding updates include:
- connect wallet button styling
- update to cart icon colors/fonts
- update to "explore rounds" button styling + dropdown menu

**Details**
Designs - [Figma](https://www.figma.com/file/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?type=design&node-id=502-9785&mode=design)

**Comment by thelostone-mc** [comment]
Could you drop in the links ? I'm not sure which ones we need to do / where ?  Any example would be helpful

**Comment by michellema1208** [comment]
@thelostone-mc done! It's just the rounds featured on https://grants.gitcoin.co/
