### ISSUE TITLE
v1 Direct Grants round links lead to a blank page 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3251]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/program/0xc45cd4301ee8067a874226f46678ff2c44f12715?debug=true

### What happened?

When I go to that link directly and I'm previously connected to v2 on Manager, it leads me to a blank page.

### What should have happened instead?

It should automatically switch me to v1 and show me the round page.  

### Steps to Reproduce

1. Go to https://manager.gitcoin.co/#/program/0xc45cd4301ee8067a874226f46678ff2c44f12715?debug=true
2. Notice it leads to a blank page

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum, likely all chains

**Comment by thelostone-mc** [comment]
Looks like we fixed this during final round of testing ?

![Image](https://github.com/gitcoinco/grants-stack/assets/5358146/87ef5a98-7661-4959-b72f-79b631bd7843)

![Image](https://github.com/gitcoinco/grants-stack/assets/5358146/3bc51b82-93b7-4972-9852-78eabbc1d57e)

We get a blank screen if we are connected to another chain like miannet (where this program does not exist )

**Comment by michellema1208** [comment]
@thelostone-mc good catch - it looks like this was fixed! Will close
