### ISSUE TITLE
Not seeing fully funded amount on test v2 round on Arbitrum

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3252]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/round/6

### What happened?

I funded my round on Arbitrum but I'm not seeing it in the "Amount funded" part of the UI. 

Successful transaction link: https://arbiscan.io/tx/0x73128b604faa2c1699b0cb0458fac3eda4e2b21fef803b0a46da6b7952499b5a

<img width="1432" alt="Screen Shot 2024-03-28 at 2 38 45 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/440975b2-c4f4-49ce-9291-2188119ee7e9">

### What should have happened instead?

I should see that the round is fully funded. 

### Steps to Reproduce

1. Go to https://manager.gitcoin.co/#/round/6
2. See my successful transaction link 
3. Notice that it says the round is not funded yet 

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum

**Comment by thelostone-mc** [comment]
@michellema1208 It likely just took a while 
<img width="706" alt="image" src="https://github.com/gitcoinco/grants-stack/assets/5358146/854127a0-7209-488b-9c49-aaf4f18572ce">

**Comment by michellema1208** [comment]
Closing as no longer an issue
