### ISSUE TITLE
Explorer: Update thank you page

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#3301]
**Overview**
Update the branding and styling on the thank you page after a successful checkout

Changes in this ticket:
- background image
- button styling & text
- fonts/colors

**Details**
Design here - [Figma](https://www.figma.com/file/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?type=design&node-id=468-4277&mode=design)

**Comment by thelostone-mc** [comment]
@melissa-neira Could you share the png of the background
