### ISSUE TITLE
Cannot Verify Project Twitter

### ISSUE THREAD

**Issue by rekhansejal** [gitcoinco/grants-stack#3302]
### What was the URL where the error occurred?

https://builder.gitcoin.co/#/chains/42161/registry/0x4aacca72145e1df2aec137e1f3c5e3d75db8b5f3/projects/0xda6c5f867a3f9a5faf541b688cf094a24d0093e238847f49c3369e6e53650962/edit

### What happened?

Twitter: @Sonic1337 (I have even tried to crease a new Twitter account "@SuperMajority_", but it didn't solve the problem.)

It's always the same error: "Couldn't connect to Twitter. Please try verifying again"
![Vr66K4j3Ye](https://github.com/gitcoinco/grants-stack/assets/156701045/e36692eb-8d96-4078-b1d0-379a44ba6deb)

### What should have happened instead?

Twitter account should be verified. GitHub already is. 

### Steps to Reproduce

Help with the twitter verification. 

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum

**Comment by thelostone-mc** [comment]
<img width="772" alt="Screenshot 2024-04-16 at 4 30 07 PM" src="https://github.com/gitcoinco/grants-stack/assets/5358146/dedebcc2-f709-4330-8fb3-455ae1028297">

Just tried doing it for a project on Arb and it seemed to work
Could you ask them to clear cache/storage and try again

Also worth asking them when it fails:
- Does twitter login popup
- Do they authorize the app
- Did the sign the msg post authorization 

^ knowing where it fails / a screenshot of the console would help
