### ISSUE TITLE
Project socials shows invalid after approval

### ISSUE THREAD

**Issue by rekhansejal** [gitcoinco/grants-stack#3314]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/round/27/application/10

### What happened?

After I approved the project project socials are correct, it still says invalid. 
<img width="1053" alt="Screenshot 2024-04-17 at 2 39 47 PM" src="https://github.com/gitcoinco/grants-stack/assets/156701045/3ef5b4ae-c761-4279-9914-47b94035fd39">

### What should have happened instead?

It should say 'verified'

### Steps to Reproduce

Not sure

### What browser(s) are you seeing the problem on?

Chrome

**Comment by 0xKurt** [comment]
Reason: The credentials are expired.
They were issued last year and need to be renewed every 3 month.
