### ISSUE TITLE
Donation History Not visible

### ISSUE THREAD

**Issue by rekhansejal** [gitcoinco/grants-stack#3317]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/contributors/0xB3623D62FF30fadB5B2e127C07cab0D1b0808276

### What happened?

Donation History not visible. 

Txn hash: 0x4768b7d5b449253f8b19f6bf8e5558532e63d330f30e0fbe700ca3709e22293e

### What should have happened instead?

Once donated, donation history should have been visible. 

### Steps to Reproduce

Not sure

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum

**Comment by codenamejason** [comment]
![Screenshot 2024-04-19 at 9 47 34 AM](https://github.com/gitcoinco/grants-stack/assets/9419140/eec28bd8-548d-48af-9c94-af3e60b4e3a8)
