### ISSUE TITLE
Explorer "no project/round info found"

### ISSUE THREAD

**Issue by MathildaDV** [gitcoinco/grants-stack#3355]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/

### What happened?

It comes and goes, and has been reported by a few people BUT explorer.gitcoin.co shows "no rounds found" and when I click into a project it shows "no project data found"

### What should have happened instead?

It should have displayed the project and round info. As mentioned it comes and goes but Explorer generally just feels very glitchy at the moment!

### Steps to Reproduce

go to explorer
click in on a project
<img width="1445" alt="Screenshot 2024-04-24 at 08 36 58" src="https://github.com/gitcoinco/grants-stack/assets/123002057/fd206669-2509-47ae-b7f2-8e73ef937e64">
<img width="1544" alt="Screenshot 2024-04-24 at 08 37 06" src="https://github.com/gitcoinco/grants-stack/assets/123002057/44207403-bcd4-4fb6-a27a-4fde0c84d483">
<img width="1528" alt="Screenshot 2024-04-24 at 08 37 16" src="https://github.com/gitcoinco/grants-stack/assets/123002057/d6aafedd-cb38-4e36-b48b-42223492ded6">
<img width="1544" alt="Screenshot 2024-04-24 at 08 37 06" src="https://github.com/gitcoinco/grants-stack/assets/123002057/701dac45-686d-46fa-b0b4-bfe142adbbde">

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

ARB

**Comment by codenamejason** [comment]
This was due to a degradation in one of our services we rely on for the indexer.

<img width="1301" alt="Screenshot 2024-04-24 at 5 05 59 PM" src="https://github.com/gitcoinco/grants-stack/assets/9419140/6c033414-ac90-4003-85a3-24d9cd0aadd4">
