### ISSUE TITLE
404 Error - Hackathon Alumni round

### ISSUE THREAD

**Issue by MathildaDV** [gitcoinco/grants-stack#3357]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/round/42161/23

### What happened?

Getting a 404 error
<img width="1423" alt="Screenshot 2024-04-24 at 08 47 11" src="https://github.com/gitcoinco/grants-stack/assets/123002057/da8f7978-cc3e-4df1-885f-8b2f46944e7c">

### What should have happened instead?

no 404 error

### Steps to Reproduce

go to the link
view the page

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum

**Comment by codenamejason** [comment]
Looks like it's back up now.
<img width="1170" alt="Screenshot 2024-04-24 at 5 03 12 PM" src="https://github.com/gitcoinco/grants-stack/assets/9419140/47e1eda2-ee3f-437d-bfc3-b81f5e64ef3d">
