### ISSUE TITLE
Tx are not indexed

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#3364]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/cart

### What happened?

1. Donated to two projects on Arb, tx successfully completed: https://arbiscan.io/tx/0x3c9ffd443cb9861a95c677b9a34c14c9a607e9b97ff6d67a8e8af530a698d785
2. Explorer is stuck on the completing tx step. No errors in the console 
![Screenshot 2024-04-24 at 5 53 37 PM](https://github.com/gitcoinco/grants-stack/assets/72808678/8a78fcb6-32bf-442b-85db-f9c75f47dc79)
3. When I refresh the page the same projects appear in my cart
4. My donation history page does not reflect my contributions
5. This is also impacting applications in builder (tx is processed, but application status is not reflected in app)

### What should have happened instead?

See above

### Steps to Reproduce

See above

### What chain(s) did the error occur on?

Arbitrum

**Comment by thelostone-mc** [comment]
This should be fixed
