### ISSUE TITLE
Not able to Donate

### ISSUE THREAD

**Issue by rekhansejal** [gitcoinco/grants-stack#3371]
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/cart

### What happened?

it doesn’t come to transactions, this error pops up immediately as soon as I press the pay button on the site.

i have balance --> click submit donation --> click checkout --> Error Finalize your contribution
no transactions or confirmations are sent to the wallet

![image](https://github.com/gitcoinco/grants-stack/assets/156701045/d46ac6d6-6027-40ec-a087-31556b2086d0)

### What should have happened instead?

tx should go through and should be able to donate

### Steps to Reproduce

not sure

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Arbitrum

**Comment by owocki** [comment]
@rekhansejal could you right inclick the page + click inspect + click 'console".. then try to checkout again and screencap any errors that come up?
