### ISSUE TITLE
Check to see if users have enough gas to checkout

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#3386]
**Overview**
Users frequently hit issues checking out when they don't have enough gas, but they don't understand the error in their wallet. We should prevent the tx from kicking off if they don't have enough gas.

**Details**

<img width="388" alt="gaserror" src="https://github.com/gitcoinco/grants-stack/assets/72808678/6c757679-e089-4f6e-8f79-3531c9f30a75">

**Comment by thelostone-mc** [comment]
Closing this out as the solution for https://github.com/gitcoinco/grants-stack/issues/3393 resolves this as well
