### ISSUE TITLE
Avalanche Contact not able to Access Program or Round for Review

### ISSUE THREAD

**Issue by SovereignSignal** [gitcoinco/grants-stack#3551]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/chain/43114/program/0xb3ad53550e1f79d834479f551173ac50167ead24bfba981a6cf4bf80c041ef20

### What happened?

Loom Explaining: https://www.loom.com/share/1db349a89f5c452491a429f1440e9245

### What should have happened instead?

the contact should be able to see the rounds and review/approve applications

### Steps to Reproduce

Loom describing the issue: https://www.loom.com/share/1db349a89f5c452491a429f1440e9245

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

AVAX

**Comment by thelostone-mc** [comment]
User error and hence closing it out. updated on support thread
