### ISSUE TITLE
Feature Request: allow team members to edit the project

### ISSUE THREAD

**Issue by marsrobertson** [gitcoinco/grants-stack#3576]
I'm the founding member / visionary / firestarter - it is my wallet that manages the grant.

But as the team grows - other people need to be able to make edits.

I would like to have ability to add contributors to the grant.

Currently no convenient workaround exists as sharing private key is not very OPSEC friendly.

**Comment by MasterHW** [comment]
to clarify - you mean editing project metadata?

**Comment by marsrobertson** [comment]
@MasterHW to "edit the project" I mean "add collaborator"

I would like to enable my collaborators to edit the project.

**GENUINE USE CASE:**

<img width="630" alt="image" src="https://github.com/user-attachments/assets/057961fb-bc9d-43fa-82f7-01aeb1b1ca03">

**Comment by MasterHW** [comment]
your round and program seem to both have a number of addresses listed as collaborators (members & managers). what is it they're not able to do?
![image](https://github.com/user-attachments/assets/b919568e-0a9b-414d-989a-e7b5230677d4)

**Comment by marsrobertson** [comment]
I'm not referring to "round" or "program". The wording I used is "project", now I see that I should more precise wording: "grant".

I'm glad to know that "add member" feature is already implemented elsewhere:
<img width="655" alt="image" src="https://github.com/user-attachments/assets/066b3bc2-ea54-4568-9c77-487c7f809008">

There is no option to "add member" when editing the grant project:
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/f088c30c-d67e-4155-b903-3084d8eba1d5">
