### ISSUE TITLE
Batched approval stuck in transaction

### ISSUE THREAD

**Issue by DecentralizedExchangeLTD** [gitcoinco/grants-stack#3583]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/round/14/application/8

### What happened?

1)After I did a batched approval with 3 projects, the transaction went through I believe but it did not approve. 
0xa41df017aea6a3ae94922c0154d0710bfad9c3597226a2008412c42e39d4c065

2)When I click on any of the projects, it shows pending.
3)If you click approve again, the page freezes. 
4)If I do a single approval for a different project, it will be approved. 

**Batched approval didn't work for me but single does. 

### What should have happened instead?

Projects approved and show on the approved list and explorer frontend. 

### Steps to Reproduce

click multiple projects
approve multiple

### What chain(s) did the error occur on?

Celo

**Comment by 0xKurt** [comment]
@DecentralizedExchangeLTD it this still an issue?
I saw the projects are reviewed already and I'm not able to reproduce the issue

![MNGR-2024-08-08 15-19](https://github.com/user-attachments/assets/54342491-4d60-4ab6-b097-0713ff22ac6a)
