### ISSUE TITLE
Issues downloading .CSV on Manager

### ISSUE THREAD

**Issue by wasabinetwork** [gitcoinco/grants-stack#3595]
### What was the URL where the error occurred?

https://manager.gitcoin.co/

### What happened?

Integral feedback by user

_Hey Gitcoin team. Im unable to download the .csv file of all the appications- I get promted to scan the QR code with wallet connect and I always get "Connection Failed" (tried like 50 times).. it works fine for other actions like accepting/ rejecting applications, but not for donwloading the .csv file. This started happening after all the issues last week. It works fine for my other colleagues, but it's a bit annoying to ask them every single time. Let me know if you're aware of this issue!_

### What should have happened instead?

Should allow Grant Manager to download the CSV file

### Steps to Reproduce

Browser: Chrome
Wallet: OneKey on my iphone; using wallet connect

Feedback by user
_Again, works fine for logging in, for accepting/ rejecting applications, just not for the .csv download._

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Optimism

### Relevant log output
```
"TypeError: Cannot convert undefined or null to object\n    at Function.values (<anonymous>)\n    at Module.i0 (https://manager.gitcoin.co/static/js/main.8d3f164e.js:37503:14940)\n    at https://manager.gitcoin.co/static/js/main.8d3f164e.js:38017:8572\nEnd of stack for Error object"
```

**Comment by MasterHW** [comment]
Hey, we've investigated and had some trouble reproducing this error. It seems to only occur with OneKey wallet, and for reasons not obvious to us. Is it okay to recommend user try a different wallet?
