### ISSUE TITLE
Sei Builder Profiles + Applications Not Completing

### ISSUE THREAD

**Issue by SovereignSignal** [gitcoinco/grants-stack#3598]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/chain/1329/round/9

### What happened?

Have been working with multiple users today that are having issues with builder profiles being created and then being able to apply to the round.  Many of them are showing the transactions are getting hung

Here's some example txns:
https://seitrace.com/address/0x009D0Ad5C781c8039621f8974f180C928AFE372b?chain=pacific-1

Stuck here:
![telegram-cloud-photo-size-5-6181744209090952096-y](https://github.com/user-attachments/assets/7e98dcd3-b625-4c14-b613-33786538cda4)

0x8a1bdcd7be690179aecffaf47484349d122e4d69a1b6bd29f72d25e09aab0f1e

### What should have happened instead?

People should be able to apply and use their builder profiles.  I have confirmed this is not related to the issues with compass.

### Steps to Reproduce

1) go to builder
2) create a profile (gets hung)

or
1) go to https://builder.gitcoin.co/#/chains/1329/rounds/9
2) try and apply (gets hung)

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

Sei

**Comment by MasterHW** [comment]
fixed by https://github.com/gitcoinco/grants-stack-indexer/pull/641
