### ISSUE TITLE
Redundant message if only one network

### ISSUE THREAD

**Issue by marsrobertson** [gitcoinco/grants-stack#3604]
1. Add grant on Optimism and Arbitrum
2. Remove Optimism
3. Checkout

----

**EDIT / UPDATE:** even simpler repro steps:
1. Add grant on Arbitrum
2. Checkout

_(previously I was thinking that adding multiple networks sets `multiple_networks = true` but possible to repro with single network only)_

----

This message is redundant / confusing:
> Checkout all your carts across different networks or select the cart you wish to checkout now.

<img width="993" alt="image" src="https://github.com/user-attachments/assets/6ad7d6fd-9ae3-40e8-8d57-5868a438f141">

**Comment by Ronexlemon** [comment]
can i be assign?

**Comment by eben619** [comment]
@marsrobertson @MasterHW  I'm not sure if this is the fix you are looking for? But does this address the issue?
This is a cart with contributions on more than one network.

![Screenshot 2024-10-29 115422](https://github.com/user-attachments/assets/6a68850d-3b99-454e-806e-c83a00027309)

So it rightly displays the message on the modal at checkout.

![Screenshot 2024-10-29 115524](https://github.com/user-attachments/assets/e67ce105-f0cb-4521-8d1c-991c9246c158)

The changes i've made:

![Screenshot 2024-10-29 115615](https://github.com/user-attachments/assets/9aa18ad3-92b0-4e5a-ac74-0514a291d4c1)

Conditional rendering of the message on the modal such that it does not display if the networks being chaecked out in the cart are not more than 1. Even if there are multiple projects in the cart but are on the same network.

![Screenshot 2024-10-29 115645](https://github.com/user-attachments/assets/b9ecdf0f-9184-4b7d-965b-ed9e74d11d46)
