### ISSUE TITLE
Cosmetic UI: display figures to always contain 2 decimal places for consistency

### ISSUE THREAD

**Issue by marsrobertson** [gitcoinco/grants-stack#3607]
It immediately got my attention as misaligned. Or maybe by design? I think consistency is better.

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/bac00d7f-429a-4fc8-8a86-01ac1e144d50">

**Comment by onyedikachi-david** [comment]
Can i get assigned?

**Comment by eben619** [comment]
Hey @marsrobertson, @MasterHW , I have a fix for this. To fix the display figures issue you could update the props.crowdfundedUSD component in the ViewRoundPage.tsx. file found in grants-stack\packages\grant-explorer\src\features\round\ViewRoundPage.tsx.

fix : 

`
{props.crowdfundedUSD?.toLocaleString("en-US", {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2,
                  })}
`
This approach will guarantee the amount is always shown in two decimal places on the frontend. Even if it is a whole number.

I'll go ahead and create a draft pull request for this fix.
