### ISSUE TITLE
Round Results not Uploading

### ISSUE THREAD

**Issue by SovereignSignal** [gitcoinco/grants-stack#3660]
### What was the URL where the error occurred?

https://manager.gitcoin.co/#/chain/10/round/66

### What happened?

I am trying to finalize the results of a round (Octant on OP) and the results are not uploading.  This is the attachment I am using:

[matching_distribution.csv](https://github.com/user-attachments/files/17192620/matching_distribution.csv)

### What should have happened instead?

I should be able to upload the round results

### Steps to Reproduce

go to manager
round results
upload round results csv

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

OP

**Comment by MasterHW** [comment]
issue was scientific notation on a large numerical value in the csv. pinged umar to resolve this at the source.
