### ISSUE TITLE
gg-22 testing feedback

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#3685]
GG-22 Testing Link : https://explorer-staging-8zs12atxz-grants-stack.vercel.app/

Features to test:
- Swap widget: 
  - Add any project in an active round running to your cart (make sure it's not testnet )   
  - Checkout Cart but use a token where you don't have sufficient balance 
  - The bridge/swap option should popup -> use the feature and drop in feedback / bug reports on this channel 
- Attesation
  - Once you finish your donation, you should be mint an attestation on sepolia on the thank you page
  - Follow the process and generate your attestation 
  - Head over to the my donation page to check if your attestation can be viewed
  - Additionally, try to generate an attesation for any older transaction
  
  
 Drop your issues as a comment on this thread

**Comment by owocki** [comment]
![screenshot_2024-10-14_at_8 25 40___am](https://github.com/user-attachments/assets/b25868e1-2b92-4828-ba74-6a7ea8b7dc0f)
looks like my mint worked onchain. the text overflow on long grant names isnt handled tho

**Comment by owocki** [comment]
when i try to swap from arbitrum to scroll, it says "swaps are unavailable"

<img width="1308" alt="Screenshot 2024-10-14 at 8 54 36 AM" src="https://github.com/user-attachments/assets/b3073e7c-e1dd-446b-9920-328a21edbdf2">

**Comment by owocki** [comment]
community collections are still from gg21

<img width="1203" alt="Screenshot 2024-10-14 at 8 55 25 AM" src="https://github.com/user-attachments/assets/0a0ef3e7-4d0f-443f-ac68-ccc7d7c67be0">

**Comment by thelostone-mc** [comment]
> when i try to swap from arbitrum to scroll, it says "swaps are unavailable"
shared it with the squid router team 

> community collections are still from gg21
Yup might need your hand to get it updated for gg22

**Comment by MathildaDV** [comment]
![Uploading Screenshot 2024-10-15 at 11.39.44.png…]()

when i try to swap from eth to sei it gives me a prompt to add a new wallet, which is a bit confusing and unclear as it then prompts me to connect to Cosmos

**Comment by MathildaDV** [comment]
<img width="413" alt="Screenshot 2024-10-15 at 11 56 33" src="https://github.com/user-attachments/assets/2264cceb-d527-403d-b83f-88aaa52701e0">
getting this warning within Wallet Guard when I try to submit my donation!

**Comment by MathildaDV** [comment]
<img width="351" alt="Screenshot 2024-10-15 at 11 37 41" src="https://github.com/user-attachments/assets/bf1964fa-a0ab-4005-84d4-1da3746daf04">

why is it asking me log in?

**Comment by melissa-neira** [comment]
<img width="810" alt="Screenshot 2024-10-15 at 16 40 45" src="https://github.com/user-attachments/assets/03b6f78a-9d7c-497f-9990-54d2e3b18489">

a few issues: 
- there's no stroke around the top part of the box
- the gitcoin logo looks really weird here, it looks too big for the circle it's in. let's center and resize that to fit. in figma, these were supposed to be project logos. can we still do that?
- the spacing looks really off for the top projects, they look too close together, and the bottom top round box is way too big
- if there is a singular number, like in the image "1 chains", then it should be "1 chain" instead

**Comment by meglister** [comment]
- Would be nice if the "bridge funds" text was bolded or differentiated from the rest of the box. I glazed over it
- After swapping enough to donate, I realized I didn't have enough ETH in that wallet to pay for gas. When I went back to the cart, the bridge option wasn't available. It would be nice to have this permanently available

**Comment by meglister** [comment]
- Share on X button could use a border or heavier shadow -- it doesn't look like a button to me as-is
![Screenshot 2024-10-15 at 10 46 36 AM](https://github.com/user-attachments/assets/3d48d60d-bb39-4730-a9a0-489a4c4c6f60)

**Comment by meglister** [comment]
- On a small screen view, mint your impact is way down at the bottom of the page, and i have to scroll all the way to the bottom to find the button. Would be great to bring it up higher and decrease some of the empty space
![Screenshot 2024-10-15 at 10 47 25 AM](https://github.com/user-attachments/assets/e6c34733-baf8-4b39-9587-d893aea819ab)

**Comment by meglister** [comment]
- Embed for farcaster is not working properly: https://warpcast.com/catjam/0xe82dcda7

**Comment by gnomadic** [comment]
visting the share page shows Nick's eth address hardcoded:
<img width="499" alt="Screenshot 2024-10-15 at 11 04 48 AM" src="https://github.com/user-attachments/assets/a5687ab7-cb58-429f-ab80-fc0f5fa86425">

**Comment by gnomadic** [comment]
<img width="380" alt="Screenshot 2024-10-15 at 11 11 49 AM" src="https://github.com/user-attachments/assets/dd810dc4-6577-4164-bb93-6bc377a281cc">


share on warpcast button here doesn't work

**Comment by melissa-neira** [comment]
<img width="594" alt="Screenshot 2024-10-15 at 17 11 30" src="https://github.com/user-attachments/assets/30207496-c4af-44db-b2cc-a2794c9a0c17">
 
is there any way to make the twitter share card for mint attestations bigger like this?

**Comment by veganbeef** [comment]
**Swap:**
* would be nice to have amount and destination chain auto-populate when the swap window opens 
* source and destination token should auto-populate to match the user's selected token (USDC or ETH) in the cart
* estimated transaction amount doesn't match amount in wallet client (I tried to bridge $3.50 to scroll but the total was actually $3.92 + $0.10 gas fee)
* would be nice to add a button / link to open the swap window even if the user has sufficient funds (especially _after_ the user has completed a swap already, but could even be populated before just without error highlighting)
* would be nice to have swap window automatically close after swap success and clicking "ok" button
* eth balance always shows zero in swap window (just need to display more decimals -- shown in screenshot below)
<img width="527" alt="Screenshot 2024-10-15 at 7 57 01 AM" src="https://github.com/user-attachments/assets/a25b0b3e-a8c4-4f56-a3ee-1f240fa74a43">


**Mint attestation:**
* network selector says "mainnet" but is actually showing my sepolia balance
* would be nice if color selector showed all colors instead of gray for unselected colors
* farcaster share text doesn't properly tag gitcoin and includes wrong text (shown in screenshot below)
<img width="670" alt="Screenshot 2024-10-15 at 8 08 11 AM" src="https://github.com/user-attachments/assets/6ca68dd5-bd11-4b30-9861-8b6e97b71ea2">

**Comment by ufkhan97** [comment]
Icon Loading Bug:
-  it looks like the icon for the first project (Grant Research) didn't load (or maybe it doesn't have an icon?)  and the icons for viaprize and OSO moved up to the 1st/2nd spots when they should be in 2nd/3rd
<img width="358" alt="Screen Shot 2024-10-15 at 11 51 19 AM" src="https://github.com/user-attachments/assets/b0c90780-2d52-40a2-8471-8523e82b129b">
<img width="803" alt="Screen Shot 2024-10-15 at 11 51 12 AM" src="https://github.com/user-attachments/assets/fbd7a04f-e446-484b-9770-e66cae589bfb">

**Comment by owocki** [comment]
my attestation says its from lionis.eth.  is nicks ens name hardcoded in? https://attestation.gitcoin.co/attestation/0x2f7a1f2b796328820d897399e1635501492f5958ce46680f3d10076732c15a52

also the 'view transaction' link doesnt work

![Uploading Screenshot 2024-10-15 at 3.02.27 PM.png…]()

**Comment by owocki** [comment]
the 'tweet attestation' button takes me to this.  is this really the prefilled content we expect ppl to tweet?

<img width="629" alt="Screenshot 2024-10-15 at 3 03 32 PM" src="https://github.com/user-attachments/assets/b9c19d2e-1080-4792-afc2-8052fd39ffc2">

i also see it in telegram
<img width="644" alt="Screenshot 2024-10-15 at 3 06 06 PM" src="https://github.com/user-attachments/assets/111371c0-d675-4efc-87f6-e590f2ddd491">

also there is no twitter card info.  people should be able to preview the link before clicking on it.  this is the standard for any thing optimised for social media.  its not a bell/whistle


third share button doesnt work. i click this and nothing happens

<img width="239" alt="Screenshot 2024-10-15 at 3 05 36 PM" src="https://github.com/user-attachments/assets/513ee7c9-f9fc-4c9f-9a51-217629272d18">
