### ISSUE TITLE
HNCEO 

### ISSUE THREAD

**Issue by Chief1934** [gitcoinco/grants-stack#3735]
https://objects.githubusercontent.com/github-production-release-asset-2e65be/135238564/181002c3-2fa6-45e1-bb2c-fa4ee6d42096?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241211%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241211T031751Z&X-Amz-Expires=300&X-Amz-Signature=1a36faccd0d2de2af70a69892632b172d957808c8aaedd5dfae3a21a4738868e&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Drocketpool-cli-darwin-amd64&response-content-type=application%2Foctet-stream

**Comment by MasterHW** [comment]
assumed to be spam
