### ISSUE TITLE
Verify owner signatures

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#388]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
When you apply to a round -> grant-hub sends a unique id along with the application but there is no way to authenticate the metadata is actually legit. I could pose as 

New flow:
metadata is signed by grant 
ecrecover (metadata + signature) -> returns the address which signed 
get list of owners are 


https://gitcoin.mypinata.cloud/ipfs/bafkreibo2ejivqed2x636kzfddvh22tkmlpizj4vsy5a6fedvb62n75p7y

**Comment by thelostone-mc** [comment]
This is wrapped up by @KurtMerbeth change's on the hiding invalid projects
