### ISSUE TITLE
how do i deploy this repo?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/grants-stack#589]
how do i deploy this repo?  itd be great to have some copy/pasteable instructions so i can deploy the grants protocol (this repo included) at grants.supermodular.xyz

**Comment by t-proctor** [comment]
> how do i deploy this repo? itd be great to have some copy/pasteable instructions so i can deploy the grants protocol (this repo included) at grants.supermodular.xyz

For the contracts, think [DEPLOY_STEPS.md](https://github.com/gitcoinco/grants-round/blob/main/packages/contracts/docs/DEPLOY_STEPS.md) can help. Supermodular lookin cool so far 💚

**Comment by owocki** [comment]
hey @t-proctor whats up?  thanks for this.  i'm starting to hack on this today between meetings.

are there any plans to make the deployment into one coheisve readme for deploying all of the interlinked modules, or, even better, a web-interface?   (knowing this would help me know how familiar i should get with the command line here vs wait for further tooling/docs)

**Comment by t-proctor** [comment]
> hey @t-proctor whats up? thanks for this. i'm starting to hack on this today between meetings.
> 
> are there any plans to make the deployment into one coheisve readme for deploying all of the interlinked modules, or, even better, a web-interface? (knowing this would help me know how familiar i should get with the command line here vs wait for further tooling/docs)

Not sure what the future plans are for it. I like the UI idea though and have some free time today. Were you think something  like a Github Pages w/ a single page deploy description?

**Comment by owocki** [comment]
yeah i think in order of ease of use...

1. one click deploy where i dont have to touch command line
2. github pages or other docs with a single page to deploy the suite of protocols
3. seperate repos with different deploy instructions, i have to click across + piece things together to deploy it all together
4.

**Comment by t-proctor** [comment]
Ok. I can work on 2. I think 1 would require public test env vars. @thelostone-mc, thoughts?

**Comment by t-proctor** [comment]
> yeah i think in order of ease of use...
> 
> 1. one click deploy where i dont have to touch command line
> 2. github pages or other docs with a single page to deploy the suite of protocols
> 3. seperate repos with different deploy instructions, i have to click across + piece things together to deploy it all together

Ok. I can work on 2. I think 1 would require public test env vars. @thelostone-mc, thoughts?

**Comment by t-proctor** [comment]
> yeah i think in order of ease of use...
> 
> 1. one click deploy where i dont have to touch command line
> 2. github pages or other docs with a single page to deploy the suite of protocols
> 3. seperate repos with different deploy instructions, i have to click across + piece things together to deploy it all together

Ok. I can work on 2. I think 1 would require public test env vars. @thelostone-mc, thoughts?

Also, have really enjoyed working with the Gitcoin team and am a huge fan of the product. I’m currently in the interview process with a few other opportunities, so wanted to give you the heads up that I don’t know how available I will be for volunteer work after this. I am excited to get to work on this, but just wanted to give you advanced warning as you plan future projects.

**Comment by t-proctor** [comment]
I created an example for 2 [here](https://t-proctor.github.io/grants-round/jekyll/update/2022/11/01/deploy-grants-round.html). I can add it as a PR if wanted
