### ISSUE TITLE
as a GPC lead, i want to put up ideas for our roadmap up on a grants protocol, so that we can have a more democratic/oipen way of doing roadmap planning (and dogfood grants)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/grants-stack#596]
**User Stories**
as a GPC lead, i want to put up ideas for our roadmap up on a grants 2, so that we can have a more democratic/open way of doing roadmap planning (and dogfood grants)

**Acceptance Criteria**
1. a grants 2 instance that runs (probably) QV, so that peoiple can post their ideas for what they want build into / on top of the protocol in the open
2. from there, people can allocate votes to the projects they think are important.
3. this gives owocki a place to politic for the ideas he wants out in the open (here is one idea id push for example: https://github.com/gitcoinco/passport/issues/670)
4. it gives otheres a place to politic in equal footing. and it gives GPC input on their roadmap.
5. it also dogfoods grants protocol, which creates more empathy for gitcoins customers (bc we use it ourselves)

**Comment by Kweiss** [comment]
Hey @owocki - Are there any other protocols that do something like this that we could review for inspiration in how much of the roadmap is opened up for public debate?

the example you give https://github.com/gitcoinco/passport/issues/670 feels like something anyone can do as the data is open, but perhaps there are some infrastructure missing to make that happen?

**Comment by owocki** [comment]
not sure lets see what the hivemind thinks https://twitter.com/owocki/status/1588150035350695936
