### ISSUE TITLE
Add project created date to GE project details

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#647]
**User Story:**
As a donor
I want to know how long a project has been around
So that I can assess its legitimacy

**Acceptance Criteria**
GIVEN that I am on a project's detail page on GE
WHEN I look in the project details section
THEN I see the date it was created

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A56059)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Moving to blocked until https://github.com/gitcoinco/grant-hub/issues/638 is wrapped

**Comment by hmrtn** [comment]
Is this still an issue/blocked?

**Comment by DanieleSalatti** [comment]
Looks like gitcoinco/grant-hub#638 was shipped - should we move back to backlog?
