### ISSUE TITLE
Add project created date to RM application details

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#648]
**User Story:**
As a Round Operator 
I want to know when a project was created
So that I can make a well-rounded decision 

**Acceptance Criteria**
GIVEN a Round Operator is on an application details page
WHEN browsing
THEN the Round Operator should see when a project was created next to social links

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2426%3A17635&t=qIdMWkdBnxQRUapm-4)

**Tech Details:**
- [Grant hub story](https://github.com/gitcoinco/grant-hub/pull/625)
- [discussion thread on Discord](https://discord.com/channels/562828676480237578/1039929390265536543/1039929392366882867)

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Moving to blocked until https://github.com/gitcoinco/grant-hub/issues/638 is wrapped

**Comment by DanieleSalatti** [comment]
gitcoinco/grant-hub#638 was shipped - should we move back to backlog?
