### ISSUE TITLE
qv contracts: define gatekeeper interface

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#773]
### Description

- [ ] Build out an interface for the gatekeeper
- [ ] Have a variable to store a reference to the votingStrategy contract
- [ ] Define a function which would set / update the votingStrategy
- [ ] Define a function which checks if caller is approved to vote
- [ ] Define a function which checks if given address is approved to vote

Use IVotingStrategy.sol as a reference

**Comment by thelostone-mc** [comment]
This just defines an interface. Just a code review would suffice
