### ISSUE TITLE
as a user, id like you to guide me through the confirmation process.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/grants-stack#799]
on this page, im not sure what to do at first glance.  there is a lot of info on the page.

after clicking arou8nd and thinking about it a lot, i see i need to 
(1) click the "add all" button
(2) click the "final donation" apply to all button
(3) click "submit yo8ur donation"

is there a way we can put the call to actions above the fold, put them in in sequential order visually, or otherwise guide my eyes to the things i need to do on the page?

![screencapture-grant-explorer-gitcoin-co-2022-12-09-09_14_17](https://user-images.githubusercontent.com/513929/206744953-c579321a-2690-49bd-9f48-a15c22e84a4a.png)

**Comment by gravityblast** [comment]
closing as we added a different checkout experience
