### ISSUE TITLE
Populate Overview stats

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#811]
**User Story:**
As a round operator
I want to see my round stats
So that I can monitor progress of my round

**Acceptance Criteria**
GIVEN that I am on the round stats tab
WHEN I look at Est. Donations Made
THEN I see the total USD value of donations made in the round

GIVEN that I am on the round stats tab
WHEN I look at Matching Funds Available
THEN I see the total USD value of the matching pool

GIVEN that I am on the round stats tab
WHEN I look at Unique Contributors
THEN I see the total number of unique wallets that have donated

GIVEN that I am on the round stats tab
WHEN I look at No. of Contributions
THEN I see the total number of contributions (contributions = unique wallet donating to one project)

**Product & Design Links:**
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=208-21959&t=OmGjFYjhb8zvYEhF-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
as part of this - modify the client.

**Comment by vacekj** [comment]
@melissa-neira what should the tooltips for the stats cards be?

**Comment by melissa-neira** [comment]
@vacekj no need for tooltips for the stat cards! The cards feel pretty self-explanatory. I'll update the designs 🫡
