### ISSUE TITLE
Populate Matching Stats

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#814]
**User Story:**
As a round operator
I want to see my round stats
So that I can monitor progress of my round

**Acceptance Criteria**
GIVEN that I am on the round stats tab
WHEN I look at Current Matching stats
THEN I see a column for "Projects"
AND I see a scrollable list of all projects accepted to my round

GIVEN that I am on the round stats tab
WHEN I look at Current Matching stats
THEN I see a column for "No of Contributions"
AND I see a scrollable list of the number of contributions for each project

GIVEN that I am on the round stats tab
WHEN I look at Current Matching stats
THEN I see a column for "Est Matching"
AND I see a scrollable list of the estimated matching percent for each project

**Product & Design Links:**
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=208-21959&t=OmGjFYjhb8zvYEhF-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
preview in #1270
