### ISSUE TITLE
chore: see if funds sent to optimism contract for UNICEF can be recovered

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#860]
### Description 

- Work with @gravityblast and work through process on how to get the funds back 
- @bhargavaparoksham should be the one running the deploy 

But the crux of this issue:
Create a new hardhat project

- Write a dummy factory contract
- Write a dummy implementation which would get created 
- Have a method in the implementation to send funds back to the multisig
- Test the deploy on goerli 

Now do the thing on optimism and create a new implementation until  we can deploy the contract at the same address as  
https://optimistic.etherscan.io/address/0xdf75054cd67217aee44b4f9e4ebc651c00330938

**Comment by thelostone-mc** [comment]
Factory: 0x862D7F621409cF572f179367DdF1B7144AcE1c76
Implementation: 0xd39b40aC9279EeeB86FBbDeb2C9acDF16e16cF89
Dummy : 0x15630aDFD3A0F07aDe4575A1d08f627A0186ebbC


Commands:

```
yarn run deploy-factory goerli
yarn run deploy-implementation goerli
# update link.ts and create.ts with deployed factory and implementation
yarn run link goerli
yarn run create goerli
```

**Comment by vacekj** [comment]
@thelostone-mc were those funds ever rescued, or did we just reimburse UNICEF?

**Comment by thelostone-mc** [comment]
We paid out those donations on our behalf. The funds need to be rescued

**Comment by michellema1208** [comment]
@gravityblast is this something we can still do / should prioritize?
