### ISSUE TITLE
Minimum contribution amount 

### ISSUE THREAD

**Issue by imranmahmudshoiball** [gitcoinco/grants-stack#882]
**User Story:**
As a gitcoin contributor, I saw gitcoin UNICEF round don't have minimum contribution amount.
I want to tell the team that, we need to set a minimum contribution amount.
So that, keep it in knowledge.

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by GouravSen56** [comment]
Grante Round end????

**Comment by imranmahmudshoiball** [comment]
Today is last date.

**Comment by GouravSen56** [comment]
![Screenshot_20221221_174124](https://user-images.githubusercontent.com/102718653/208914760-b1e869d5-0037-4667-a6d7-2d1987b8d4c1.jpg)
![Screenshot_20221221_174107](https://user-images.githubusercontent.com/102718653/208914789-452cfc55-dd2c-4498-822e-f6454fc38e8f.jpg)
My Donation failed everytime
 please help me 🙏😭

**Comment by imranmahmudshoiball** [comment]
Yesterday my donation was successful at first time.

**Comment by GouravSen56** [comment]
Donation failed everytime please contact grants round
