### ISSUE TITLE
Add finalized state to Funding Admin page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#893]
**User Story:**
As a round operator
I want to know what I finalized for my round
So that I can know when my round is closed

**Acceptance Criteria**
GIVEN that I have finalized my round's distribution
WHEN I go to the Funding Admin tab
THEN I see the finalized distribution state

GIVEN that I am on the Funding Admin tab in the finalized distribution state
WHEN I click on the "view on etherscan" button
THEN a new tab opens to my round's finalization transaction on the appropriate block explorer

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=3372%3A46160&t=MgTuspmLWbZM3U2Y-4)

**Tech Details:**
Once the distribution is uploaded into contract, the user on revisiting the funding admin tab should see the upload results.  From a technical perspective
- Existing view is replaced by new table where data is populated from payout contract metaPtr
- Anytime user refreshes -> the information displayed always is fetched from the contract metaPtr

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by hmrtn** [comment]
depends on #869
