### ISSUE TITLE
PLACEHOLDER: Additional donation page banners

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#930]
**User Story:**
As a donor
I want to know if I'm not eligible for matching funds
So that I can take steps to be eligible

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=2699%3A74101&t=u18NBKdK0QBjPZGk-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by gravityblast** [comment]
closing since we have a passport banner
