### ISSUE TITLE
[Spike] Frontend <> Bad API

### ISSUE THREAD

**Issue by vacekj** [gitcoinco/grants-stack#940]
**Overview**
The goal of this spike to see how our frontends react to the API going down or malfunctioning. 
- Are we re-trying requests?
- Are we alerting the user when something goes wrong?
- Do we communicate what the next steps are for the user in case of an error?
- Are we logging the errors appropriately, both on the frontend and API side? (this is going a bit out-of-scope, but worth checking since it would be in the same place as error handling logic anyway)
- Are our errors standardised and well-defined? (recall confusion about Pulumi errors causing a 404)
- Are all current sad paths handled?
- Are we proactively working with sad paths when writing our stories / implementing them?

I estimate this to be a 2-pointer for each of our frontends, so two devs should suffice.

**Comment by gravityblast** [comment]
@vacekj can we close this ticket?

**Comment by vacekj** [comment]
@gravityblast the ticket is still very relevant, but needs renaming from Bad API to Bad APIs plural, meaning subgraph, indexer and others. all the points still stand.
