### ISSUE TITLE
mob: explore rewrite of program using swr

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#953]
### Description

The goal is here is mob with the team and explore the ease of building an already existing feature using swr.
The team would work on this to rebuild :

- fetching programs
- creating programs 
- writing tests 

Once this is wrapped up, we will decide the pros/cons against the existing architecture and if the migration makes sense, we'
ll create follow up tickets

**Comment by vacekj** [comment]
Edited this to mention swr instead of react-query, as react-query is most likely overkill for what we are trying to do. The migration path from swr to rq is straightforward if we ever feel the need to upgrade.
